### ISSUE TITLE
Comment positions not preserved when preceded by a brace (`{`)

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/styler#1004]
For example, in `{lintr}`, you can include directives in comments that instruct if the line of code in question should not be linted with a certain linter, etc. But `{styler}` changes positions of such comments, which means these directives will no longer work:

``` r
styler::style_text(
  "T_and_F_symbol_linter <- function() { # nolint: object_name.
  }"
)
#> T_and_F_symbol_linter <- function() {
#>   # nolint: object_name.
#> }
```

<sup>Created on 2022-09-19 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by lorenzwalthert** [comment]
uups that's actually pretty bad...
