### ISSUE TITLE
FR: Ignore entire files via `.stylerignore`

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/styler#1024]
IINM, this isn't currently supported. 

I think this is a more convenient way to ignore files instead of adding styler ignore directives at the start and end of each file that needs to be ignored while styling.

If you agree, I can work on this.

**Comment by lorenzwalthert** [comment]
You mean a file called `.stylerignore` that lists these files?

**Comment by IndrajeetPatil** [comment]
Yea, exactly.

**Comment by lorenzwalthert** [comment]
I am not sure we should create a separate file. This might be related to #319 and could be stored alongside with other config. Or in `DESCRIPTION`?
