### ISSUE TITLE
If not present, insert blank lines between different Markdown elements

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/styler#1040]
cf. https://yihui.org/en/2021/06/markdown-breath/

This can cause issues, and it will be good to have an automated way to do this for `.Rmd` and `.qmd` docs via `{styler}`.

**Comment by lorenzwalthert** [comment]
Thanks. I am not sure formatting no-code element in markdown is in scope of {styler}. I started {stylermd} but I quickly realised that it's a complicated thing in it's own right.  I think for markdown formatting, we better rely on other tools, in particular the formatter that RStudio uses for the visual editor, which I could not figure out how it works quickly and hence asked RStudio to expose it: https://github.com/rstudio/rstudio/issues/11039.

**Comment by IndrajeetPatil** [comment]
Okay, sounds reasonable. Then let's punt this to `{stylermd}`, if and when ready.
