### ISSUE TITLE
CRAN re-submission

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/styler#1044]
Dear maintainer,

Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_styler.html>.

Please correct before 2022-11-09 to safely retain your package on CRAN.

The CRAN Team

Seems like only occurring on R devel with fedora flavor. Also, it's not clear if the problem was already present for version 1.7.0, as the below screenshot has no data for 1.7.0 anymore. @IndrajeetPatil did you check the CRAN results page before 1.8.0 wsa released?

<img width="588" alt="Screenshot 2022-10-29 at 15 40 53" src="https://user-images.githubusercontent.com/10477073/198834783-cc07336a-8368-45c1-acf5-9c6fcce74fd4.png">

**Comment by lorenzwalthert** [comment]
This seems like a needle in the heystack thing to find -.-
Potential sources:
* opening web browser: https://stackoverflow.com/questions/62456137/r-cran-check-detritus-in-temp-directory
* parallel testing: https://stackoverflow.com/questions/72677239/how-do-i-solve-this-two-notes-from-r-package-auto-check

**Comment by lorenzwalthert** [comment]
I am trying to reproduce the problem with r-hub with `rhub::check(platforms = 'fedora-gcc-devel')`, logs at:    https://builder.r-hub.io/status/styler_1.8.0.9000.tar.gz-d6a944f58f3940c9a4e8fd2a312837d5

**Comment by lorenzwalthert** [comment]
@krlmlr I guess here we might need your help.

**Comment by krlmlr** [comment]
Do I understand correctly that none of these checks have shown the error? 

Is there a way to find out when this error started to occur? A hint in the most recent R-devel changes? Unfortunately, the Wayback Machine is of no help here, they don't archive CRAN check results.

**Comment by IndrajeetPatil** [comment]
> @IndrajeetPatil did you check the CRAN results page before 1.8.0 wsa released

IIRC, yes, I did. But there was only the `NOTE` about `is_shebang.Rd` file; nothing about detritus in the temp directory.

Is the problem that we are leaving the cache directory behind, or something similar?

Btw, we error on a `NOTE` in `R CMD check` run on GHA, and the fact that it's still not showing errors makes me think that this is a change that was very recently introduced in R-devel, and we may start seeing this failure on GHA soon.

https://github.com/r-lib/styler/blob/4c1cb51ad7fe485873f1728804f3614241be1916/.github/workflows/check-full.yaml#L59

**Comment by lorenzwalthert** [comment]
> Do I understand correctly that none of these checks have shown the error?

yes. 

> Wayback Machine is of no help here, they don't archive CRAN check results.

yes, tried that also.

**Comment by lorenzwalthert** [comment]
> Is the problem that we are leaving the cache directory behind, or something similar? 
I don’t think so, these problems looked differently: https://github.com/r-lib/styler/issues/836

**Comment by krlmlr** [comment]
These machines are fairly special:

- https://www.stats.ox.ac.uk/pub/bdr/Rconfig/r-devel-linux-x86_64-fedora-gcc
- https://www.stats.ox.ac.uk/pub/bdr/Rconfig/r-devel-linux-x86_64-fedora-clang

Maybe we can even replicate the problems locally?

**Comment by lorenzwalthert** [comment]
Mirracles happen. r-devel-linux-x86_64-debian-gcc  no longer shows a note. 😮. Maybe it was just a bug in R devel.

**Comment by lorenzwalthert** [comment]
@krlmlr do you think we should to write on r devel? I have never done that before. 7 days till removal.

**Comment by krlmlr** [comment]
Let's wait for five more days, and then push an update to CRAN if the failures persist. This will buy us a bit more time.

**Comment by lorenzwalthert** [comment]
Ok, and what update should we push if we don't even know what the root cause is?

**Comment by krlmlr** [comment]
We could disable all tests to see if problems still occur. Then, we at 
least know if it's the tests or the examples.

Another thing to try would be to run R CMD check on Linux devel with the 
flags described in 
https://www.stats.ox.ac.uk/pub/bdr/Rconfig/r-devel-linux-x86_64-fedora-gcc 
. It puzzles me that _R_CHECK_THINGS_IN_TEMP_DIR_ is set to "true" both 
here and in the other custom Fedora setting, but the other Fedora 
setting now works. I really hope this is a transient thing.

**Comment by krlmlr** [comment]
Also, the last checks with this R version ran with

> using R Under development (unstable) (2022-10-21 r83155)

Let's give it some more time.

**Comment by lorenzwalthert** [comment]
For your last point: Agree, all other checks have newer R versions.

**Comment by lorenzwalthert** [comment]
@krlmlr days passed and the NOTE still appears on one machine, which uses the same old 20222-10-21 R devel. Should we re-submit with all tests skipped? How would I do that? Just comment out the code in `tests/test that.R`?

**Comment by krlmlr** [comment]
Commenting out sounds good. The error is on CRAN's end, but we don't want styler to be pulled, which is likely to happen automatically if we don't act. And acting means resubmitting, e-mails are likely to be ignored.

**Comment by IndrajeetPatil** [comment]
Update is on CRAN! 🎉

**Comment by lorenzwalthert** [comment]
and all checks green: <img width="561" alt="Screenshot 2022-11-08 at 08 34 53" src="https://user-images.githubusercontent.com/10477073/200502190-0def5d38-edd4-4b99-bbfb-dc508451d884.png">
