### ISSUE TITLE
unused argument (encoding = "native.enc") 

### ISSUE THREAD

**Issue by DaveJarvis** [r-lib/styler#1050]
## Replicate

Install styler:

``` bash
sudo su -
R
install.package( "styler" )
```

Use styler:

``` bash
cd /tmp
wget https://raw.githubusercontent.com/DaveJarvis/keenwrite/master/R/possessive.R
R
library( "styler" )
style_file( "possessive.R" )
```

## Expected

File is reformatted.

## Actual

File is not reformatted.

```
Styling  1  files:
 possessive.R ⚠ 
────────────────────────────────────────
Status	Count	Legend 
✔ 	0	File unchanged.
ℹ 	0	File changed.
✖ 	1	Styling threw an error.
────────────────────────────────────────
Warning message:
When processing possessive.R: unused argument (encoding = "native.enc") 
```

## Environment

```
$ R --version
R version 4.2.2 (2022-10-31) -- "Innocent and Trusting"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
```

**Comment by lorenzwalthert** [comment]
Thanks @DaveJarvis. There seem to be multiple problems that we should address (warning, no info about the error, error itself etc.). One to quickly fix is a minimal version requirement for {withr}. Can you download at least version 2.3 and retry and we see if it solves at least one of the problems?

**Comment by DaveJarvis** [comment]
>  Can you download at least version 2.3 and retry and we see if it solves at least one of the problems?

I'm not super skilled with R. If you provide the _exact set_ of R commands to execute, I'll try them.

**Comment by lorenzwalthert** [comment]
Sure. Easiest is to just get the latest version with 
```
install.packages('withr')
```
And then re-start the R session.

**Comment by DaveJarvis** [comment]
Worked.

```
> style_file( "possessive.R" )
Styling  1  files:
 possessive.R ℹ 
────────────────────────────────────────
Status	Count	Legend 
✔ 	0	File unchanged.
ℹ 	1	File changed.
✖ 	0	Styling threw an error.
────────────────────────────────────────
Please review the changes carefully!
```

**Comment by lorenzwalthert** [comment]
We've added a minimal version requirement for {withr} in #1051. Hence I propose to close this issue.
