### ISSUE TITLE
When Roxygen comment block ends with a tag, the stylerignore directives are ignored

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/styler#1067]
This was difficult to track down, but I finally have a minimal reprex to show the issue.

----

When the Roxygen comment ends with a tag (any tag), the stylerignore directives are ignored. 

For example, here the Roxygen comment block is surrounded by the stylerignore directives, and yet the code in examples is styled. 

``` r
styler::style_text(
  "# styler: off
#' @examples 
#' x=1
#' @export
# styler: on"
)
#> # styler: off
#> #' @examples
#> #' x <- 1
#> #' @export
#> # styler: on
``` 

And I think that this has something to do with the tag at the end, because if you relocate it to any other position in the comment block, we get the expected behaviour.

``` r
styler::style_text(
  "# styler: off
#' @export
#' @examples 
#' x=1
# styler: on"
)
#> # styler: off
#> #' @export
#> #' @examples 
#> #' x=1
#> # styler: on
```

<sup>Created on 2022-11-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by lorenzwalthert** [comment]
Thanks for the reprex. I agree, this is not what we are after.

**Comment by lorenzwalthert** [comment]
To me, it seems rather that roxygen code sequences are not recognized as such [if they don't end with an `@` tag after the example section, code or a blank line](https://github.com/r-lib/styler/blob/acfb42acc2e558e7b57ef133f1470df78b5093fd/R/roxygen-examples-find.R#L13-L14).
``` r
styler::style_text(
  "
#' @export
#' @examples 
#' x=1
"
)
#> #' @export
#> #' @examples
#> #' x=1
```

<sup>Created on 2022-12-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by IndrajeetPatil** [comment]
> I am not even sure roxygen code comments are stylerignored in any way.

I think they are: https://github.com/r-lib/styler/pull/1085#issuecomment-1365717001

**Comment by lorenzwalthert** [comment]
Should the issue be reopened or did #1089 fully solve the issue?
