### ISSUE TITLE
Combination of stylerignore directives and `local()` leads to problematic styling

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/styler#1072]
## Problem

The following code 

``` r
# styler: off
skip_if_not_installed("tibble")
local({
  x <- 1
})
# styler: on
```

is styled to-

```r
# styler: off
local({
  x <- 1
})
skip_if_not_installed("tibble")
local
# styler: on
```

Note how `skip()` and `local` change their positions.

## How to reproduce

Run the example code in interactive mode.
If you are looking for a more realistic example, run `styler:::style_active_file()` on [this](https://github.com/r-lib/lintr/blob/main/tests/testthat/test-implicit_integer_linter.R) file.

## Note

It's interesting that I can reproduce the issue in the minimal example posted above in the _interactive_ mode, but not in a reprex.

<img width="306" alt="Screenshot 2022-11-26 at 08 54 23" src="https://user-images.githubusercontent.com/11330453/204078636-f0e2bc0f-2189-417e-87bb-8446d51b0dc8.png">

**Comment by lorenzwalthert** [comment]
Full reprex: 

``` r
full <- c(
  '# styler: off',
  'skip_if_not_installed("tibble")',
  'local({',
    'x<-1',
  '})',
  '# styler: on'
)
without_ignore <- full[c(-1, -length(full))]
styler:::local_test_setup(cache = TRUE)
styler::style_text(without_ignore)
#> skip_if_not_installed("tibble")
#> local({
#>   x <- 1
#> })
styler::style_text(full)
#> # styler: off
#> local({
#> x<-1
#> })
#> skip_if_not_installed("tibble")
#> local
#> # styler: on
```

<sup>Created on 2022-12-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by lorenzwalthert** [comment]
Tough one o tell you… these interactions between caching and stylerignore are hard to get right, but I think I found a solution after hours of digging. Will push later.
