### ISSUE TITLE
Support styling one-line example code included in Roxygen `@example` tag?

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/styler#1075]
## Works for `@examples`

``` r
styler::style_text(
  "#' @examples x=1
  #' @keywords internal"
)
#> #' @examples x <- 1
#> #' @keywords internal
```

## But not for `@example`

``` r
styler::style_text(
  "#' @example x=1
  #' @keywords internal"
)
#> #' @example x=1
#> #' @keywords internal
```

<sup>Created on 2022-11-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

That said, I am not sure with what frequency is the `@example` used in the wild.

**Comment by lorenzwalthert** [comment]
I don't think your use of `@example` is valid, it expects a path: https://roxygen2.r-lib.org/reference/tags-rd.html to a file, not a literal example.
