### ISSUE TITLE
Interactions and compatibility with {codegrip}

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/styler#1078]
At least it should not destroy them, in particular the double indention for function declaration.
https://github.com/lionel-/codegrip

**Comment by IndrajeetPatil** [comment]
True, both of these packages currently seem to undo each other's formatting:


https://user-images.githubusercontent.com/11330453/207355271-c872f8c8-f0a7-4447-8bbc-7260d2f982e7.mov

**Comment by lorenzwalthert** [comment]
I think we can close this as per #1083.
