### ISSUE TITLE
New double-indented function style gets undone, causing lint

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/styler#1092]
I tried to adjust a wide function declaration to use the new double-indented style:

```r
# before
xxxxxxxxxx_xxxxxxxxxxx <- function(yyyyyyyyyy.yyyy = c(
                                     "aaaaaaaaaa", "bbbbbbbbb", "cccc"
                                   )) {
  ...
}

# after
xxxxxxxxxx_xxxxxxxxxxx <- function(
    yyyyyyyyyy.yyyy = c("aaaaaaaaaa", "bbbbbbbbb", "cccc")) {
  ...
}
```

But under styler 1.9.0 this gets edited:

```r
styler::style_text('
xxxxxxxxxx_xxxxxxxxxxx <- function(
    yyyyyyyyyy.yyyy = c("aaaaaaaaaa", "bbbbbbbbb", "cccc")) {
  ...
}
')
# xxxxxxxxxx_xxxxxxxxxxx <- function(yyyyyyyyyy.yyyy = c("aaaaaaaaaa", "bbbbbbbbb", "cccc")) {
#   ...
# }
```

AFAICT the `after` style is style guide compliant (https://style.tidyverse.org/functions.html#long-lines-1); the key may be:

> Prefer function-indent style to double-indent style when it fits.

Under the tidyverse guidance of 80 characters per line, the function _doesn't_"fit" in function-indent style, hence double-indenting is OK.

**Comment by lorenzwalthert** [comment]
> Under the tidyverse guidance of 80 characters per line

For that we can't account https://github.com/r-lib/styler/issues/247.
