### ISSUE TITLE
No write permission ~/.cache/R/R.cache/styler

### ISSUE THREAD

**Issue by vvarik** [r-lib/styler#1099]
On Linux, trying to install `styler` fails with:
`Error: package or namespace load failed for ‘styler’:`
`.onLoad failed in loadNamespace() for 'styler', details:`
`  call: getWritablePathname.Arguments(static, file = "dummy-not-created", `
`  error: No write permission for directory: /home/varik/.cache/R/R.cache/styler`

Sure enough:
`~/.../R/R.cache$ ls -l`
`drwxr-xr-x 3 root root 4096 Oct 18  2021 styler`
`-rw-r--r-- 1 root root  431 Jun  8  2021 README.txt`

Any other packages install fine.

---
Ubuntu 20.04.6, R 4.2.3

**Comment by lorenzwalthert** [comment]
Can you install {R.cache}? Because that function trace is from it.

**Comment by vvarik** [comment]
Yes, could install `R.cache` without any problems. Tried to install `styler` after that, same 'no write permission' issue. Tried to load first `R.cache` and install then `styler`, same issue.

**Comment by lorenzwalthert** [comment]
Also see https://github.com/r-lib/styler/issues/871 and links there. I think you might have a non-standard permission setup here. Who owns the directory? The user? If not, maybe just create that directory manually?

**Comment by vvarik** [comment]
Alright, as suggested in [#871](https://github.com/r-lib/styler/issues/871), overriding `R` folder permissions fixed the problem:

`cd ~/.cache`
`sudo chown -R <username> R`

I might have inadvertently created root owned `R` folder in `~/.cache/` a while ago -- there is plenty of confusion online about whether Linux users should install R packages with `sudo` or not (the answer is not, but I did not know any better initially).
