### ISSUE TITLE
Replace deprecated `rlang::with_handlers()`

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/styler#1102]
cf. https://rlang.r-lib.org/reference/with_handlers.html

This is generating a ton of warnings when tests are run.

**Comment by MichaelChirico** [comment]
I'm a bit loath to use something marked as experimental, what's wrong with the base functions?

**Comment by IndrajeetPatil** [comment]
I don't think they behave the same. I tried using `withCallingHandlers()`, but a lot of tests were failing and I couldn't figure out exactly why.

**Comment by MichaelChirico** [comment]
ok, sg in that case

**Comment by lorenzwalthert** [comment]
Alternatively, we can also look into using base replacements for `with_handlers()` if #1104 does not help us fix the performance problem in benchmarking. I might be able to help where the errors come from that you could not fix.
