### ISSUE TITLE
[Testing] Poor parallelism of test-public_api.R

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/styler#1106]
Much like #1105, we can improve the performance of the styler suite by reducing imbalance across test shards (i.e. files).

No individual `test_that()` unit is as slow as that in #1105, but taken as a whole, test-public_api.R takes much longer than any other file.

The proposed solution here is simpler -- subdivide test-public_api.R into a few files, e.g. test-public_api-{0,1,2}.R, or subdivide by functionality.

Happy to help filing a PR based on the desired subdivision.

**Comment by lorenzwalthert** [comment]
Open to that one.
