### ISSUE TITLE
Release for rlang 1.1.0 deprecation tweaks?

### ISSUE THREAD

**Issue by kyleam** [r-lib/styler#1117]
On the current tip of main (8e9ac82), the styler check performs much better, in terms of memory usage and runtime, than the latest styler release (see r-lib/rlang#1626).  The removal of deprecation warnings by 99d502fc (Replace usage of deprecated rlang::with_handlers(), 2023-04-01, #1103) looks to be a large part of that.

I'm not sure how much any of this is relevant for regular usage (versus a test setting, where code paths are being hit repeatedly), but, even based on the check performance alone, it seems like it might be worth cutting a new styler version.  Are there plans to release soon?

(Thanks for maintaining styler.)

**Comment by lorenzwalthert** [comment]
Thanks for the report here and in {rlang}. Current `main` also contains considerable speed improvements for regular usage as you can see in the release benchmark in  #868, mainly stemming for replacing {base} functionality with {vctrs} equivalents. From that point of view, it would be worth cutting a new release too. If we withhold the release for a little longer, is it blocking your work?
