### ISSUE TITLE
Add newline after standalone closing parenthesis with comma?

### ISSUE THREAD

**Issue by krlmlr** [r-lib/styler#1133]
I'm confused by the following behavior:

``` r
styler::style_text("
list(
  c(
    a
  ), c(
    b
  )
)
")
#> list(
#>   c(
#>     a
#>   ), c(
#>     b
#>   )
#> )
```

<sup>Created on 2023-06-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Should styler add a newline here? What's a precise description of the rules to be applied here?

**Comment by lorenzwalthert** [comment]
I think if there is a line break, it won’t remove it, so think the behavior works for both cases. Maybe we can also add an argument to `tidyverse_style()` to enforce adding one.

**Comment by krlmlr** [comment]
I wonder if there are legitimate cases where a line break is *not* desired here.

**Comment by MichaelChirico** [comment]
Adding a newline for cases like this tends to create a lot of wasted whitespace.

I might choose to add a newline myself, but styler's defaults should be non-invasive -- unless there's a specific rule, don't do anything.

If there's a gap in the style guide, the fix should start from there:

https://github.com/tidyverse/style/issues
