### ISSUE TITLE
wrong behavior with pipes for multiline lhs 

### ISSUE THREAD

**Issue by moodymudskipper** [r-lib/styler#1153]
``` r
requireNamespace("styler")

# minimal
structure(
  c("(x\n) |>", "  fun()"),
  class = "vertical"
)
#> (x
#> ) |>
#> ) |>n()

# use case
structure(
  c("(function(x) {\n  x\n}) |>", "  (`environment<-`)(.GlobalEnv)"),
  class = "vertical"
)
#> (function(x) {
#>   x
#> }) |>
#>   x`environment<-`)(.GlobalEnv)
```

<sup>Created on 2023-11-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by lorenzwalthert** [comment]
I don't get it. Please descrite input, output and expected output. If applicable, please supply a reference to the tidyverse style guide what is _wrong_ here.

**Comment by moodymudskipper** [comment]
The issue is that for these provided inputs the output is not syntactic and not faithful to the input, but I see now that it's a {prettycode} issue, not directly {styler}
