### ISSUE TITLE
Double indentation should be an opt-in/out rule

### ISSUE THREAD

**Issue by mcanouil** [r-lib/styler#1157]
Styler "recently" enforces a rule that double indent function declaration.
Let's say you have the following.

```r
f <- function(
  x,
  y
) {
  "content"
}
```

It will be "messed up" (sorry, personal opinion on double indentation) as:

```r
f <- function(
    x,
    y) {
  "content"
}
```

I know there is #1137 open for few months now, but regardless of this PR, I do believe double indent rule should be as other rules an opt-in/out rule.

Thanks for considering this.

**Comment by lorenzwalthert** [comment]
Hi @mcanouil. {styler} implements the tidyverse style guide and your code does not correspond to that style. As you can read in various issues, I am not the biggest fan of double indent, but there is another way
```r
function(x = 1, 
         y = 2) {
  NULL
}
```
These are the two [officially supported styles](https://style.tidyverse.org/functions.html#long-lines-1) and styler adheres to those.

**Comment by mcanouil** [comment]
I know that's a "new" tidyverse style guide rule, but that is not the point.

My question is why is it not controlled by a rule/transformer that can be opt-out? https://styler.r-lib.org/articles/remove_rules.html

**Comment by lorenzwalthert** [comment]
I am happy to review and merge a PR that refactors existing rules such that the removal of the double indention is possible in an easier way, e.g. by simply remove the rule, but I won't contribute this change.

**Comment by lorenzwalthert** [comment]
Sure. Thanks @mcanouil for understanding that catering to all user requests here is difficult and my time is limited since no one pays me to work on {styler}.
