### ISSUE TITLE
Document options

### ISSUE THREAD

**Issue by JosiahParry** [r-lib/styler#1185]
It appears that styler has options that can be set and read. These are not documented. Consider documenting them similar to `{cli}` https://cli.r-lib.org/reference/cli-config.html

https://github.com/r-lib/styler/blob/634dce16918c4c8edcafbc2eb0083da04124ee72/R/zzz.R#L8-L16

**Comment by lorenzwalthert** [comment]
Some of them are documented but it’s very scattered. So I agree that documenting all options in one place would be a good idea.
