### ISSUE TITLE
Styler and lintr disagree on what happens after a linebreak

### ISSUE THREAD

**Issue by dsweber2** [r-lib/styler#1188]
Styler auto-formats to:
```r
  if (TRUE ||
    FALSE) {
    TRUE
  }
```
While linter prefers:
```r
  if (TRUE ||
        FALSE) {
    TRUE
  }
```

I don't really have strong opinions on which of these should happen, I would just like my tools to not contradict each other. It makes CI a mess. 
paired issue https://github.com/r-lib/lintr/issues/2535

**Comment by dshemetov** [comment]
My workaround for this has been
```r
if (
  TRUE ||
    FALSE
) {
  TRUE
}
```

**Comment by MichaelChirico** [comment]
possible duplicate of #1065, which also points to an open issue in the style guide about trying to clarify such cases upstream: https://github.com/tidyverse/style/issues/197

**Comment by IndrajeetPatil** [comment]
Yes, duplicate of #1065
