### ISSUE TITLE
Don't force line break for unnamed 1st argument

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/styler#1190]
I think the style guide is being mis- or over-interpreted here:

https://style.tidyverse.org/syntax.html#long-lines

{styler} does the following:

```r
styler::style_text('
c(a,
  b
)
')
# c(
#   a,
#   b
# )

styler::style_text('
c(a,
  b = c
)
')
# c(a,
#   b = c
# )
```

It looks like {styler} has decided that unnamed arguments are _only_ allowed on the first line _if_ arguments on subsequent lines are named, but I don't see that explicated anywhere in the text.

{styler} is meant to be minimally-invasive, i.e. only make changes that are explicitly required by the style guide, hence I think this is a bug.

**Comment by lorenzwalthert** [comment]
I think given the context from this [issue](https://github.com/tidyverse/style/issues/39), it should be come evident what the intention was and I think styler is compliant with that.

**Comment by lorenzwalthert** [comment]
Thanks @MichaelChirico. I don’t see a lot of responsiveness at the moment upstream so I don’t know when this will be resolved there. But anyways it can’t hurt to file it. I don’t have bandwidth to work on styler much these days so sorry if I am a bit passive or defensive of tie current behavior. In general, I think if there is bit rule in the style guide and styler has a certain behavior, it is up to the person who wants to change that behavior to enforce a decision upstream. Just as you did now.
