### ISSUE TITLE
Reconsider storing code tree structure for tests by default

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/styler#1206]
That is, consider whether setting `write_tree = FALSE` in `test_collection()`, and maybe turn it on to `TRUE` only in interactive contexts where these structures might help debug some issue?

The current approach tends to produce large git diffs for even minor changes in test code.

Is there any downside to doing so?

**Comment by lorenzwalthert** [comment]
Taking a closer look at the diff, many seem unrelated to your changes, and more related to some changes in {data.tree} or the parser itself.
<img width="773" alt="Screenshot 2024-05-13 at 10 03 32" src="https://github.com/r-lib/styler/assets/10477073/e82614e4-61fd-488e-bc0d-b4b48ac2a52b">


I have hardly ever used these tree files in practice. And they are also `.Rbuildignore`d. I think people can generate them if they need, as you said, so we could `.gitignore` them and make the default `write_tree = FALSE` (currently `NA`, which accounted for the fact that {data.tree} is only available for R >= 3.2, which is irrelevant nowadays).

**Comment by lorenzwalthert** [comment]
Once this is done, we can rebase #1195 on `main` to avoid its large tree diff.
