### ISSUE TITLE
Change default indentation from 2 to 4

### ISSUE THREAD

**Issue by nickhir** [r-lib/styler#1218]
Hello,

I am trying to change the default indentation from 2 spaces to 4 spaces, however I am unable to find an option for this.
The solution outlined [here](https://forum.posit.co/t/change-default-indent-in-styler-to-4-spaces-vs-2/18474) does not seem to work anymore.

Any help is much appreciated!

**Comment by IndrajeetPatil** [comment]
``` r
library(styler)

style_text(
  "{ x <- 1}",
  transformers = tidyverse_style(indent_by = 2L)
)
#> {
#>   x <- 1
#> }
```

``` r

style_text(
  "{ x <- 1}",
  transformers = tidyverse_style(indent_by = 4L)
)
#> {
#>     x <- 1
#> }
```

<sup>Created on 2024-06-25 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by nickhir** [comment]
Thank you for your quick answer! Could you also elaborate, how I can make sure that the add in (`Style active file`) uses the "new" style (i.e. the one with 4 whitespaces)?

**Comment by IndrajeetPatil** [comment]
You need to use the following option to change addin behaviour: 

```r
options(addins_style_transformer = "styler::tidyverse_style(indent_by = 4L)")
```

If this is in the context of a project, you could also put this in `.Rprofile`.

**Comment by IndrajeetPatil** [comment]
Ah, I forgot to include `styler.`:

```r
options(styler.addins_style_transformer = "styler::tidyverse_style(indent_by = 4L)")
```

All of this is documented here: https://styler.r-lib.org/dev/reference/styler_addins.html
