### ISSUE TITLE
style from clipboard

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/styler#122]
As  with `formatR::style_source()`, the default for `style_text()` could be the clipboard.

**Comment by krlmlr** [comment]
Yeah, but clipr should be a `Suggests` only I think.

**Comment by lorenzwalthert** [comment]
Also, potentially write the styled output to the clipboard.

**Comment by lorenzwalthert** [comment]
Reference: https://github.com/eddelbuettel/crp/commit/0c28586924a50c1ee545607192a4a10b3e165ebf
