### ISSUE TITLE
Force removing line break before function declaration?

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/styler#124]
@krlmlr removed line breaks manually [here](https://github.com/yihui/tikzDevice/commit/81e41fdc1e4007984bc6a5fd17278327db10f6c1). I am not sure whether there should be a rule to remove these, since if I have a very long function name like this
```r
abckdjy <- function() {
  a_very_long_function_name <- function(xdkajfi, 
                                        adfasdf) {
    x
  }
} 
```
And potentially many nested  levels (so the declaration itself is indented), so I am not sure whether such a rule is a good idea.

**Comment by krlmlr** [comment]
Even if line breaks are not removed, indention shouldn't add up:

```r
# good
fun <- function(x) {
  body
}

# arguable (but not necessary for the tidyverse)
fun <-
  function(x) {

  body

}

# bad
fun <-
  function(x) {
    body
  }
```

**Comment by lorenzwalthert** [comment]
Ok. I think the tidyverse style guide does not cover that case. However, your `#bad` example is the way RStudio formats things and I feel like it is natural because every line that contains a token that triggers indention is indented, and indention can only be one level per line. Anyways, if we force `function(` on the same line as `<-`, we get rid of the problem anyway.

**Comment by krlmlr** [comment]
Maybe we can settle for

```r
fun <-
function(x) {

  body

}
```

?
