### ISSUE TITLE
Export style_active_file()?

### ISSUE THREAD

**Issue by fh-mthomson** [r-lib/styler#1243]
The RStudio add in for `styler` -> "Style active file" sends `styler:::style_active_file()` (not exported) to the Console for execution:
![image](https://github.com/user-attachments/assets/ba0753b1-22fe-4c9a-9f79-68e3d7ada84f)
![image](https://github.com/user-attachments/assets/b07f8447-a9d9-48ee-a5ce-006c6b6ccffd)

After making some changes to the file, I tried to call`styler::style_active_file()` via the Console, assuming it was exported, to learn it wasn't:
![image](https://github.com/user-attachments/assets/ebbb219b-7257-4831-b123-30c197f257dc)

If this is a function we'd expect users to be able to call directly, I'd kindly suggest exporting it, for convenience.

**Comment by lorenzwalthert** [comment]
Thanks. The function is not exported becayse it _should not_ be called by the user directly.

**Comment by fh-mthomson** [comment]
Thanks for clarifying and considering! 

I'd note this is slightly at odds with the `testthat::test_active_file()` add-in that _is_ exported:
![image](https://github.com/user-attachments/assets/bcdeec14-178c-4f60-8f04-4a2972dddb03)

**Comment by lorenzwalthert** [comment]
I see. What would we gain from exporting the function? There are 52 other issues in this repo and I don't see how exporting this function is solving any problem.

**Comment by fh-mthomson** [comment]
I fully agree the benefits are marginal (and fall below priority of most other open issues): 
1. _slightly_ easier to find / run the function via the Console (e.g., via `styler::` or, more meaningfully, if `library(styler)` is called, the function is then globally available)
2. consistency with `testthat`

I was initially scratching my head when I couldn't find a function that I knew RStudio had indirectly called, so I'd started the discussion via this issue once I figured it out (quickly).

Totally reasonable if you or others wouldn't find this worth the effort, since it's slightly more than adding `@export` to the current function definition!

Either way, a **huge** thank you for such a useful _and_ performant package! It's made a step change in our package development workflows.

**Comment by lorenzwalthert** [comment]
Do you see a usecase where a user would call this function directly? Does it even work? If yes, then we can export it, I don't have strong feelings.

**Comment by fh-mthomson** [comment]
> Do you see a usecase where a user would call this function directly? 

I personally have been finding it helpful to call directly, since I slightly prefer key strokes / hot keys over button clicks (or re-running multiple times by hitting the up arrrow after making minor changes).

> Does it even work? 

It does! 
<img width="440" alt="image" src="https://github.com/user-attachments/assets/33ca44bf-35e5-4600-b9a6-44e855c2565e" />
