### ISSUE TITLE
{ / } and line breaks in function calls

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/styler#125]
The tidyverse style guide states in section 2.4 that 

A `}` should always go on its own line, unless it’s followed by `else` or `)`. 

So that's why we implemented `remove_line_break_before_round_closing()` which is responsible for
the line breaks removed in [tikzDevice](https://github.com/yihui/tikzDevice/commit/1e4c965d4b3873966109bfc8b877ae7b8fbdfbeb). 

I personally think that's fine, but we may only include this rule if `strict = TRUE`.

Also it says that  a `{` should never go on its own line and should always be followed by a new line, so 
```r

tryCatch(
{
  ...
} 
```
from the above-referenced commit is in my eyes not compliant with the tidyverse style guide.

**Comment by krlmlr** [comment]
The rules might need a refinement. In [this example](https://github.com/yihui/tikzDevice/commit/1e4c965d4b3873966109bfc8b877ae7b8fbdfbeb#diff-9162005f07b9d7b776be882dbf341544R298), the closing brace `}` belongs to an argument that is indented already, which is why indenting the closing parenthesis looks wrong:

```r
# good
fun(
  arg,
  {
    block
  }
)

fun(
  {
    block
  },
  {
    another_block
  }
)

# bad

fun({
  block
},
{
  another block
})

fun(
  arg,
  {
    another block
  })
```

**Comment by lorenzwalthert** [comment]
I am not sure whether I understand you correctly. Why is 

```r
fun(
  arg,
  {
    block
  }
)
```
a good example with regard to the second rule cited? Shouldn't it be

```r
fun(
  arg, {
    block
  }
)
```
or even
```r
fun(
  arg, {
    block
})
```


Also

```r
fun(
  arg,
  {
    another block
  })
```
is bad, I agree, but I thought
```r

fun(
  arg, {
    another block
})
```
would be correct, so `}` is unindented since ) follows.

**Comment by krlmlr** [comment]
I haven't found a specification for long function calls in the tidyverse guide. Maybe we could contribute one, that also covers complex function arguments that consists of whole blocks?

No need to hurry though, I'm fine with this limitation for now.

**Comment by krlmlr** [comment]
Attempt to formulate a line-break rule:

> A multi-line argument to a function must start on a new line, unless it's the last argument (like `test_that(..., {})` *and* all other arguments fit on one line.

**Comment by krlmlr** [comment]
Another potential exception, perhaps if *all* arguments are multi-line?

```r
tryCatch({
  block
},
error = function(e) {
  handler
},
finally = {
  cleanup
})
```

**Comment by lorenzwalthert** [comment]
I suggested a function to add a line break after the opening parenthesis if the expression is a function call, see https://github.com/krlmlr/styler/issues/118#issuecomment-322052062. Should we implement that for the CRAN milestone or not? Otherwise, 


```r
long_call(1, 
          k * 3)
```

Will become just
```r
long_call(1, 
  k * 3)
```

**Comment by krlmlr** [comment]
Did you mean

```r
long_call(
  1,
  k * 3
)
```

?

**Comment by lorenzwalthert** [comment]
In the meanwhile, I implemented #149, which does what you wrote, yes. Otherwise, just removing the rule we had (`update_indention_ref_fun_dec()`) would result in what I wrote.

**Comment by lorenzwalthert** [comment]
Reference: #255 .

**Comment by lorenzwalthert** [comment]
Reference: #254.
