### ISSUE TITLE
tidyeval

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/styler#14]
* I was wondering how we aim to replace standard evaluation functions like `select_(~xyz)` with the upcoming release of dplyr 0.6.0 and associated. Is it via `rlang .data$xzy`, i.e. `select(.data$xyz)`? I think we should aim for consitency and change it in a single commit or PR.
* In addition, I think we need to consider that not all packages from the tidyverse support tidyeval yet, e.g. see [this PR for tidyr](https://github.com/tidyverse/tidyr/pull/301). I could not find out when that will be the case. Hence, the question is when the ideal point of transition is.

@krlmlr maybe you can advise on that.

**Comment by krlmlr** [comment]
The `select_()` wrappers will remain compatible for some time, but we should definitely aim for replacement once dplyr 0.6.0 hits CRAN. We can use `select(!!"xyz")`, this is both safe and compatible to R CMD check.

**Comment by krlmlr** [comment]
As for tidyr, we can upgrade the tidyr calls one it's been updated to tidyeval, too.

**Comment by lorenzwalthert** [comment]
Ok, thanks. I guess it would be nice to have something like the [roxygen2md](https://github.com/r-pkgs/roxygen2md) package since a lot of code (in general) needs to be converted eventually but if you don't know of efforts towards that I will just do it manually, for `styler` it's not gonna be that much as you know.

**Comment by lorenzwalthert** [comment]
As tidyr seems to be ported to the tidyverse i.e this [PR](https://github.com/tidyverse/tidyr/pull/301) is closed, should we change our function calls to `select(!!"xyz")` or `select(.data$xyz)`? I think in the dplyr [vignette](https://cran.r-project.org/web/packages/dplyr/vignettes/programming.html), they advise `.data$xyz`, not sure why not `!!"xyz"`...

**Comment by lorenzwalthert** [comment]
Well anyways we probably want to wait until it is released on CRAN anyways...

**Comment by krlmlr** [comment]
_tidyr_ with tidyeval should be on CRAN by now, let's take another look.

**Comment by lorenzwalthert** [comment]
Well we've not used tidyr directly because of the dplyr dependency. They were ported from tidyr to the file `compat-tidyr`. So not sure how to proceed

**Comment by krlmlr** [comment]
Fine with the current state.
