### ISSUE TITLE
Adding roundtrip for nested processing

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/styler#140]
Might be implemented similar to depreciated flat roundtrip
```r
#' Verify parse data modifications
#'
#' @description Check whether serializing the parse data results in the same
#' number of lines as the initial data that should be styled.
#' @param pd_flat A parse table.
#' @param text A character vector with the initial text to compare against.
#' @return If the verification is successful, `pd` is returned, with empty
#'   lines at the end of `text` stripped. \cr
#'   Otherwise, an error is thrown.
#' @seealso [serialize_parse_data_flat()]
verify_roundtrip <- function(pd_flat, text) {
  roundtrip <- serialize_parse_data_flat(pd_flat)

  if (length(roundtrip) < length(text)) {
    stopifnot(text[-seq_along(roundtrip)] == "")
    text <- text[seq_along(roundtrip)]
  }

  stopifnot(identical(text, roundtrip))
  text
}
```

**Comment by lorenzwalthert** [comment]
Reference: #85.

**Comment by lorenzwalthert** [comment]
Related: #216.

**Comment by lorenzwalthert** [comment]
I wonder how that should be implemented. Because with reference to #85, I think it would make sense to not just test parsing and serialising (because that almost certainly works now), but also whether the code is still valid after tokens were inserted, compare #259. So a simple parse statement of the output could check that.

**Comment by lorenzwalthert** [comment]
Can we postpone this?

**Comment by krlmlr** [comment]
Sure.

**Comment by lorenzwalthert** [comment]
Reference: #280.

**Comment by krlmlr** [comment]
Have we implemented roundtrip checking by now?

**Comment by lorenzwalthert** [comment]
In #287, we implemented verifying whenever possible (`can_verify_roundtrip`), which seems to be the case whenever we don't have any token manipulators.

**Comment by lorenzwalthert** [comment]
Reference: #368.
