### ISSUE TITLE
make package CRAN-ready

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/styler#145]
- [x] Get rid of notes.
- [x] Consider changing api tests to not format in temp dir since it creates problems with appveyor.
- [x] Make tests passing quickly enough?
- [x] Wait for krlmlr/utf8 to be released on CRAN and remove `Remotes:` in DESCRIPTION
- [x] Clarify LICENCE with `usethis()`? ([Link](http://r-pkgs.had.co.nz/release.html))
- [x] Completing cran-release-notes.md
- [x] Update NEWS.md (describe every exported function in order of relevance, see pillar).
- [ ] Create a pre-release.
- [x] Bump version to 0.1.0
- [x] `devtools::check_spelling()`
- [x] Delete all man files for unexported functions.
- [x] Make sure every man page of exported functions has an example.

**Comment by lorenzwalthert** [comment]
@krlmlr What else do we need to do here?

**Comment by krlmlr** [comment]
We need to release utf8. How long are the tests running, will this be a problem for CRAN?

**Comment by lorenzwalthert** [comment]
It takes about one minute on my machine. In the [CRAN Submission Policy](https://cran.r-project.org/web/packages/policies.html#Submission) it only says:
> Checking the package should take as little CPU time as possible, as the CRAN check farm is a very limited resource and there are thousands of packages. Long-running tests and vignette code can be made optional for checking, but do ensure that the checks that are left do exercise all the features of the package.

So I don't really know what that means but I think one minute is too much. Can we define a few tests that cover all rules?

**Comment by hadley** [comment]
A minute should be ok

**Comment by lorenzwalthert** [comment]
@krlmlr can you tell me whether we need to further specify the licence (see this [link](http://r-pkgs.had.co.nz/release.html))?

**Comment by krlmlr** [comment]
I think the license entry in `DESCRIPTION` is fine.

**Comment by lorenzwalthert** [comment]
Coo, thanks. One more check.

**Comment by krlmlr** [comment]
I updated NEWS, but we should start from scratch for the first CRAN release. For pillar, another new release, I started with the `API` file and briefly described each entry point.
