### ISSUE TITLE
Renaming

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/styler#16]
# Naming of data
At the moment, for the parse table returned by utils::getParseData and 
processed through various functions, we use many different names in different 
functions for essentially this (flat) table:

* pd (all rules in rules.R)
* parse_data (serialize_parse_data)
* parse_data_with_ws (serialize_parse_data_flat)
* data (create_filler)

I think it would simplify things to just use one variable name throughout. I
suggest parse_data. We could use `parse_data_flt` for the flat version and and 
`parse_data_nstd` for the nested version for situations where the processing
differs.

# Naming of functions
As far as I understand, the terminology around `ws` is more of a legacy thing, i.e. in the functions `compute_parse_data_flat_with_ws` or `add_ws_to_parse_data` since it is not really just white space information that is affected by these functions, but rather a bunch of preprocessing Hence, I would suggest to rename the latter to `pre_process_parse_data` and the former to `compute_parse_data_flt` for now.

**Comment by krlmlr** [comment]
A consistent name is a good idea. Can we simply use `nested` and `flat`, or perhaps standardize on `pd` for parse data and use this as a prefix or suffix?

**Comment by lorenzwalthert** [comment]
Ok yes, let us just use `pd` then and use `flat` and `nested` as  suffix.

**Comment by lorenzwalthert** [comment]
Reference: https://github.com/krlmlr/styler/pull/146#discussion_r134675202.

**Comment by lorenzwalthert** [comment]
So as stated in https://github.com/krlmlr/styler/pull/146#discussion_r134675202, should we use `nest` for "a parse table at one level of nesting, which always represents a complete expression", and `pd_nested` for the whole nested structure, i.e. the parse table at the top level of nesting?

**Comment by lorenzwalthert** [comment]
This includes documentation also obviously.

**Comment by krlmlr** [comment]
Yes, we can keep the terms "parse data" and "nested parse data" for simplicity. The latter consists of multiple interlinked nests, this is the only new term.

**Comment by lorenzwalthert** [comment]
Reference: #132

**Comment by lorenzwalthert** [comment]
Reference: #132.

**Comment by lorenzwalthert** [comment]
# Renaming of files

* `modify_pd.R` -> `indent.R`
* `nested.R` -> `nest.R`
* `ws.R` -> `ui.R`
* `style_md.R` -> `transform-code.R`.
* `transform.R` -> `transform-files.R`

**Comment by krlmlr** [comment]
Do we need to change anything here, short of renaming the files as you suggested?

**Comment by lorenzwalthert** [comment]
Seems no, if we want to leave the rest (`pd`, `pd_flat`, `pd_nested` etc.) as is. However, I think we should change it too for consistency. Not all of it though, e.g. `flattened_pd` is not a nest anymore.

**Comment by lorenzwalthert** [comment]
- [ ] serialized_tests.R to serialized-tests.R
- [ ] style_guides.R to style-guides.R
- [ ] move stop_insufficient_r_version() to communicate.
