### ISSUE TITLE
Consider outlining a means of crediting the package

### ISSUE THREAD

**Issue by boshek** [r-lib/styler#184]
Because this is a package that performs a task on code but once it is finished, it isn't required to be part of a package, I am wondering if it would be worthwhile to include a suggested means of crediting the package. One option might be to have a badge:

https://img.shields.io/badge/style_guide-tidyverse-orange.svg?style=plastic

This would have a two fold effect:
 - First it would give the package credit and direct people who want the service to the right place
 - Second it would also let people know that they are going to working with code in a particular style.

Whatever the case, I think it would be advantageous to have a standard method of communicating how their code has been formatted. 

Also nice package!

**Comment by lorenzwalthert** [comment]
Thanks for your input @boshek. @krlmlr what do you think? I think this is a good idea. Shall we adapt the README accordingly?

**Comment by krlmlr** [comment]
I'm not sure, I think a [`PULL_REQUEST_TEMPLATE.md`](https://github.com/blog/2111-issue-and-pull-request-templates) would be the right place to educate users about how to formatting the code.

**Comment by lorenzwalthert** [comment]
Ok. So that would be up to the repo maintainers then, so if I get you @krlmlr right, there is no need to adapt our README?

**Comment by krlmlr** [comment]
Well, we could add instructions on how to enhance/create your `PULL_REQUEST_TEMPLATE.md` to the README.

**Comment by lorenzwalthert** [comment]
I have tried extend the README in this regard and tried to add a shields badge as proposed by @boshek. However, it did not render correctly, which may be related to https://github.com/jgm/pandoc/issues/3936. Maybe we just wait for pandoc 2.0 with that.

**Comment by krlmlr** [comment]
On which branch did you try to extend the README?

**Comment by lorenzwalthert** [comment]
Haven't pushed anything, just tried to render locally and it did not work.

**Comment by lorenzwalthert** [comment]
Ok, now it works on this [branch](https://github.com/lorenzwalthert/styler/tree/contrib_guide). However, I wonder whether that is really  a styler issue or whether that should not be something stated in the tidyverse style guide itself. Also, once styler is on CRAN, maybe we can link it from the tidyverse style guide.

**Comment by lorenzwalthert** [comment]
@boshek Would you mind opening an issue there and referencing the discussion here? As far as directing people to this repo goes, we wanted to suggest to link styler in the tidyverse style guide once it is on CRAN.

**Comment by boshek** [comment]
@lorenzwalthert Sure - but can you clarify where you think I should be opening an issue? The tidyverse repo?

**Comment by lorenzwalthert** [comment]
You can open the issue in the github repo tidyverse/style.
