### ISSUE TITLE
Tab conversion

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/styler#213]
Tabs used to be converted to spaces, e.g. 10a3c68b.
```r
make_transformer_nested <- function(transformers) {
  function(text) {
    text <- gsub(" +$", "", text)
    text <- gsub("\t", "        ", text)

    pd_nested <- compute_parse_data_nested(text)
    transformed_pd_nested <- visit(pd_nested, transformers)
    # TODO verify_roundtrip
    new_text <- serialize_parse_data_nested(transformed_pd_nested)
    new_text
  }
}
```
* The tidyverse [style guide](http://style.tidyverse.org/syntax.html#indenting) does encourage the use of spaces, not tabs.
* We'd principally prefer an approach that operates on the parse table and not on the text input, so third-party style guides could leave tabs untouched.
* There seems another bug in the [parser](https://github.com/jimhester/lintr/blob/aa70430282852afa15a61cc69771e71dd32e1aec/R/get_source_expressions.R#L210) that might be relevant for this.

**Comment by lorenzwalthert** [comment]
Reference: #100.

**Comment by krlmlr** [comment]
This already works for me:

``` r
styler::style_text("if (TRUE) {\n\tNULL\n}")
#> if (TRUE) {
#>   NULL
#> }
```

The code just made sure that the roundtrip check isn't fooled by the automatic conversion from tabs to spaces, because we can't distinguish them from the `getParseData()` output.

**Comment by lorenzwalthert** [comment]
Ok, and due to the way we serialise, the output will never contain tabs anymore, right? The parser bug remains: 
> getParseData() counts 1 tab as a variable number of spaces instead of one

That might get unexpected results with `strict = FALSE`, e.g. where spaces around operators are to be preserved and tabs are not interpreted as two spaces. Should we neglect that?

**Comment by krlmlr** [comment]
To support this we'd need to be able to tweak the number of spaces per tab. We might look into this if this turns out to be an important use case, but currently this seems rather low priority.
