### ISSUE TITLE
Feature suggestion: un-style R code

### ISSUE THREAD

**Issue by jonmcalder** [r-lib/styler#220]
Issue #22 suggests a code corrupting function (just for fun), but got me thinking that a function which does the opposite of `style_file()` might actually be useful.

It could be used for example to create "dirty" files from clean code - as used in the README, vignettes etc or just for the purposes of illustration when teaching R to show the detrimental effects of poor style on code comprehension/readability.

It might also prove useful for testing - e.g. checking that `style(unstyle(x)) = style(x)`

**Comment by lorenzwalthert** [comment]
Thanks Jon, I think that would be funny. I guess we can randomly add and remove line breaks and spaces while taking advantage of the existing infrastructure of styler. As far as testing goes, we already have a system with `test_colelction()` that seems to work fairly well so I am not sure how much benefit such functionality can add.

**Comment by lorenzwalthert** [comment]
Reference: #22.
