### ISSUE TITLE
Operators starting a line in an expression with parentheses

### ISSUE THREAD

**Issue by krlmlr** [r-lib/styler#255]
``` r
styler::style_text("function() {\n (a\n||b)\n}", strict = FALSE, scope = "line_breaks")
#> function() {
#>   (a
#>   || b)
#> }
```

This is rather low priority, just mentioning it for completeness.

**Comment by lorenzwalthert** [comment]
So do you mean the operator should be moved one line up or?

**Comment by krlmlr** [comment]
I'm not sure, maybe if we had a rule in tidystyle that forbids starting a line with a binary operator?

**Comment by lorenzwalthert** [comment]
I think there is no rule. Should I propose one or is is a sufficiently rare case?

**Comment by krlmlr** [comment]
Good idea.

**Comment by lorenzwalthert** [comment]
Issue filed.

**Comment by lorenzwalthert** [comment]
In tidyverse/style#45, it was not considered to be worth to mention in the style guide since such lengthy conditions are considered to be undesirable in the first place.

**Comment by lorenzwalthert** [comment]
So I suggest to either move the infix operators one line up anyways (for `scope >= "line_breaks"`) or just leave them as is.

**Comment by krlmlr** [comment]
Can we leave them unchanged and just add a level of indention?

**Comment by lorenzwalthert** [comment]
Ok, I think we could, it's just we have never done it that way so far I think. So we'd have to add one level of indention only to the token `||` and leave everything else unchanged since indention is already added (but not active) for all tokens after `||`.

**Comment by krlmlr** [comment]
But then it seems easy to also add indention for the operator token itself, I understand it will be inactive in most cases?

**Comment by krlmlr** [comment]
And this probably generalizes to other operators?

So, if we are processing `(a + b)`, the `+` and the `b` gets indention, which is then activated if there's a newline before either?

**Comment by lorenzwalthert** [comment]
No, the triggering token itself does (currently) not get indention, only the ones following it. So in your example, b gets indented only because the closing brace is not in the same nest. It was done that way because braces trigger indention, but they should not be indented. I.e, you don't want
```r
{
  2
}
```
To become
```r
  {
  2
}

**Comment by lorenzwalthert** [comment]
However, your case seems a special case. Need to look into it further.
