### ISSUE TITLE
pkgdown style and links

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/styler#266]
Now that `styler` is an r-lib package, I was wondering whether and how we should adapt the pkgdown page to match the tidyverse style (like the one of testthat). Also I think we should change the link at the main page of the GitHub repo at the very top next to "Non-invasive pretty printing of R code" to the pkgdown page instead of the GSoC Proposal. I don't have the permissions to do that, so maybe @krlmlr can?

**Comment by krlmlr** [comment]
Happy to change the link once the website is up.

**Comment by krlmlr** [comment]
We may need a `CNAME` so that http://styler.r-lib.org works. Getting HTTPS to work may be a bit trickier (and isn't done yet either for e.g. https://dplyr.tidyverse.org and https://testthat.r-lib.org).

**Comment by krlmlr** [comment]
Added CNAME, doesn't need a DNS entry. Also added code that should create a `CNAME` when the package is auto-built, not tested: 115b183dea.

**Comment by lorenzwalthert** [comment]
Ok, pkgdown theme is blocked by tidyverse/tidytemplate#4. We can nevertheless update the link though I believe.

**Comment by krlmlr** [comment]
Updated link.
