### ISSUE TITLE
allow rmd styling also via style_dir() and style_pkg()

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/styler#291]
`style_dir()` and `style_pkg()` should gain a new argument `extension` (that defaults to `c("R")`) to indicate which types of extensions should be styled. It should handle:
* just R files (`extension = "R"` or `extension = c("R")`).
* just Rmd files (`extension = "Rmd"` or `extension = c("Rmd")`).
* both (`extension = c("Rmd", "R")`).

The case should be ignored, i.e. `extension = c("rMd")` should be accepted. Nice to have: a trailing dot is removed (i.e. `extension = c(".Rmd")` also works).

**Comment by krlmlr** [comment]
Do you want to include this in the first CRAN release?

**Comment by krlmlr** [comment]
Oh, I missed the open PR. Fine with me.

**Comment by krlmlr** [comment]
Closed by #292.
