### ISSUE TITLE
Adding functionality to use styler in a CI check 

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/styler#302]
As envisioned in https://github.com/r-lib/styler/issues/181, styler could be used in continuous integration in a similar fashion as `lintr::expect_lint_free()` to style all files and check whether anything changed. Not sure whether the changes made through styling should be discarded or not, which is not easily possible with the current implementation of `style_pkg()`. Since `testthat::expect_known_output()` also change files in place, I think it should be fine if styler also changes the files in place.

**Comment by lorenzwalthert** [comment]
Not actually sure whether that is useful at that stage since there are still a few cases styler can't handle properly and that won't be fixed anytime soon. Probably re-open after we resolved some more of the `Status: Postponed` [issues](https://github.com/r-lib/styler/issues?utf8=✓&q=label%3A%22Status%3A+Postponed%22). There is WIP @ https://github.com/lorenzwalthert/styler/tree/expect-style.

**Comment by lorenzwalthert** [comment]
Might be re-considered as a git pre-commit hook run with pre-commit.ci

**Comment by MattCowgill** [comment]
Have there been any developments on this? Is there a supported way to use `styler::style_pkg()` within a test?

**Comment by MattCowgill** [comment]
Thanks. Ideally though I would like to be able to have a regular `{testthat}` unit test that runs `styler::style_pkg()` and fails if any code that doesn't conform to the style guide is found. For example: 

```
test_that("code in package is appropriately styled", {
  result_of_style <- styler::style_pkg(dry = "on")
  expect_true(all(result_of_style$changed))
})
```
This doesn't work in `R CMD check` because `rprojroot` can't find the package directory

**Comment by lorenzwalthert** [comment]
I don't think {styler} should run as part of a unit test (because it's conceptually not a unit test). Also, the implementation is complicated for the reasons you outline. Suggestions are hence to 1) include a note in the README of your repo that you use the tidyverse style guide, 2) use the {precommit} package locally to lower the cognitive burden. You can also use the `\style` command in your PRs if you have the respective action installed. See details in this [vignette](https://styler.r-lib.org/articles/third-party-integrations.html).
