### ISSUE TITLE
ignore knitr chunks that use a non-R engine such as sql

### ISSUE THREAD

**Issue by jkgrain** [r-lib/styler#312]
styler is choking on a chunk that contains a sql code block.  I would suggest that styler ignore non-R code.

**Comment by lorenzwalthert** [comment]
Dear @jkgrain, thanks for filing that issue. I will have a look.

**Comment by lorenzwalthert** [comment]
You can use 
```r
remotes::install_github("r-lib/styler#313") 
```
To use the patch #313 until its merged into master or a new release is available on CRAN.
