### ISSUE TITLE
Newlines added at EOF

### ISSUE THREAD

**Issue by crew102** [r-lib/styler#314]
Looks like when styler is altering the style of an expression that occurs at the end of a file it's inserting a newline right after the expression, which results in an EOF newline. This would normally be OK for users who implement EOF newlines, but for those who don't, it can result in random EOF newlines throughout their project. 

Awesome package by the way.

**Comment by lorenzwalthert** [comment]
Thanks @crew102. I think with `enc::write_lines_enc()` (which styler uses), it is not possible to specify whether or not to add a line break at the end of the file. However, I think it makes sense to follow this convention since it matches the [POSIX definition](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206) and many editors and IDEs (e.g. RStudio) automatically add a line break at the end of the file if there is none. 
@krlmlr should we aim to support other line definitions than POSIX or not? This would involve adding the corresponding functionality to `enc`.

**Comment by krlmlr** [comment]
Thanks. We can discuss this when the functionality is available in the enc package (probably via an attribute attached to the character vector returned or accepted by `read_...()` and `write_...()`), happy to review a PR there.

**Comment by crew102** [comment]
> However, I think it makes sense to follow this convention since it matches the POSIX definition and many editors and IDEs (e.g. RStudio) automatically add a line break at the end of the file if there is none.

I agree. I guess my question is whether styler should add a newline on the last line of those files that it doesn't make any style changes to (i.e., those files that it doesn't have to re-write using write_lines_enc). In other words, should styler consider POSIX line definitions as desired style? If so, maybe it should add EOF newlines to all files, even those in which no other styling is required, so that all files follow the same policy. This would be the desired behavior from my perspective.

**Comment by lorenzwalthert** [comment]
Ok, right I agree that after styling, all files should have EOF line breaks. Again this is primary an `enc` issue. However, we could use `transform_lines_enc(..., write_back = FALSE)` to check whether the contents have changed ("actual code changed") and then always use `transform_lines_enc()` to write back to ensure EOF line breaks. Then, adapt the table to to include a new category:
```r
────────────────────────────────────────
Status	Count	Legend 
✔ 	5	File unchanged.
ℹ 	1	File changed (code changed).
ℹ 	1	File changed (EOF line break added only).
✖ 	0	Styling threw an error.
────────────────────────────────────────
```

**Comment by lorenzwalthert** [comment]
Ok, it seems as it's  infeasible to do what I outlined above since it would involve transforming the file contents twice, which means styling would take about twice as long.

**Comment by krlmlr** [comment]
Maybe just compare before-after file hashes with `tools::md5sum()`?
