### ISSUE TITLE
spacing around tilde

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/styler#315]
I think styler should make sure there is at least one space around the tilde operator.
``` r
library(styler)
style_text("lm(a~b, data = x)")
#> lm(a~b, data = x)
style_text("lm(a~b, data = x)")
#> lm(a~b, data = x)
style_text("map2(
  x, y,~lines[seq2(.x + 1, .y - 1)]
)")
#> map2(
#>   x, y, ~lines[seq2(.x + 1, .y - 1)]
#> )
```

Created on 2018-01-06 by the [reprex
package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by lorenzwalthert** [comment]
@krlmlr do you agree on adding a space around `~`? I think it's not covered in the tidyverse style guide because it's not particularly relevant since lazy evaluation is mostly substituted with tidyeval in many places these days. Or should we request to extend the examples in the style guide?

**Comment by krlmlr** [comment]
Thanks, missed that. How do we treat formulas without LHS?

**Comment by lorenzwalthert** [comment]
I'd suggest we don't add a space on the left hand side as it's currently implemented.

``` r
styler::style_text("(~k)")
#> (~ k)
```

Created on 2018-01-15 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by lorenzwalthert** [comment]
Ok, brace was a bad example, because we *do* add a space in general
``` r
styler::style_text("(a~k)")
#> (a ~ k)
```

Created on 2018-03-13 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by krlmlr** [comment]
Reopening, because we're not covering rhs-only formulas yet (also in the tests).

**Comment by lorenzwalthert** [comment]
Reference: https://github.com/tidyverse/dplyr/commit/0818cab40c109b88777b7c4e9e6b768dcca4e8c0#r28070282
