### ISSUE TITLE
storing styler config in a yaml file

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/styler#319]
Repo may include a file `.styler.yaml` that contains a configuration for styling, like this:
```r
style_guide:
  source: styler
  style: tidyverse_style
  options:
    strict: TRUE
    scope: tokens
```

When `styler::style_pkg()` is run, such a config file is looked for in the root directory and if one is found, the options specified there should be given precedence over what is specified in the function call. Or something like that. WIP @ https://github.com/lorenzwalthert/styler/tree/config

**Comment by lorenzwalthert** [comment]
Maybe also non-hidden `styler.yaml`. Also needs new infrastructure in root directory as #320.

**Comment by pat-s** [comment]
Are there any plans to tackle this again in the future? The ideal case would be that RStudio also picks up this settings file.

**Comment by lorenzwalthert** [comment]
Also, consider how other formatters have solved this problem, e.g. https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/

**Comment by lorenzwalthert** [comment]
This is also relevant for the save on styling functionality provided via an environment variable (`$save_on_styling`.) without namespace or language prefix.

**Comment by lorenzwalthert** [comment]
Until we make progress here (if at all), you can also use [RStudio snippets](https://support.rstudio.com/hc/en-us/articles/204463668-Code-Snippets) to store your preferred styler command, e.g. with
```r
snippet style
	styler::style_file(${1:file}, strict = TRUE, scope = "spaces", indent_by = 4)
```

You can type `style` in the RStudio console and it would expand to the command above. Just to save typing

**Comment by pat-s** [comment]
Note that you can also run R code within a snippet. The placeholder inside the snippet could default to the file that is currently opened in your editor. 

Then it almost behaves like a keybinding without the need to specify the file again 🙂

**Comment by eitsupi** [comment]
Hello.
As with many auto-formatters, it would be great to be able to change the behavior in the definition file.
It looks like you haven't made progress for a while, do you have something like a todo list?

Thanks for all the great work you do.

**Comment by lorenzwalthert** [comment]
I think I’d prefer to solve this outside {styler}, eg with {fallback} as referenced above. I am happy to transfer the repo to someone else if they want to continue work on it, because I don’t have time.

**Comment by lorenzwalthert** [comment]
Maybe {renv} would want to expose their mechanism so we don't have to re-invent the wheel? Upvotes welcome 😀  https://github.com/rstudio/renv/issues/1865
