### ISSUE TITLE
Memorize which files were not changed since last styling

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/styler#320]
Could significantly speedup `style_file()` and `style_dir()` when used often as well as pre-commit hooks. ~Needs new infrastructure `.styler` folder in root directory.~

**Comment by lorenzwalthert** [comment]
@krlmlr I think this is worth exploring, it goes into the same direction as parallelization. There are quite a few design questions involved with this, so I'd like to hear your opinion on this. Should we use a `.styler` file? Or store the hashes of the files in a `config.styler` file, along with some configs?

**Comment by krlmlr** [comment]
A directory or a separate file would be better, we don't want to mix config data and hash data.

**Comment by lorenzwalthert** [comment]
Also, let's compare our ideas with other source code formatters: black uses a non-portable file stored in some cache, the path to which is system dependent: https://github.com/ambv/black.

**Comment by lorenzwalthert** [comment]
We can use the [R.cache](https://cran.r-project.org/web/packages/R.cache/index.html) package to make sure we cache things in the right location OS-independently. Then follow: https://github.com/psf/black/issues/109#issuecomment-379127533. We can store version of styler as well as the hash of the file content (requires reading them, as opposed to use file size and modification time), then. 

* read file and hash contents.
* check if hash is already in cache (including error handling when cache can't be read properly). Potentially using the R package storr for this.
* if it is, skip that file. 
* if it is not, style and add the hash to the data base.
* make sure the cache does not grow infinite.

Benefits of this are outlined here: https://github.com/psf/black/issues/109#issuecomment-380047491
