### ISSUE TITLE
styler has an implicit dplyr dependency

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/styler#323]
If you run styler without dplyr installed, in some cases the following error message appears:

``` r
styler::style_text("a = b")
#> Error: `map_df()` requires dplyr
```

> Created on 2018-01-18 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Resolution**: Install the *dplyr* package via `install.packages("dplyr")`.

## Details

As reported [here](https://github.com/r-lib/usethis/pull/197#issuecomment-358430640), styler depends on dplyr via `purrr::map_dfr()` which we need to fix asap. Potentially this affects the upcoming [reprex](https://github.com/tidyverse/reprex) release that lists styler under suggests and the planned dependency in [usethis](https://github.com/r-lib/usethis/pull/197).
cc: @krlmlr

**Comment by krlmlr** [comment]
Can we implement our own version of `map_dfr()`? Need to take special care of the corner case of zero-length input, is this tested anywhere (implicitly or explicitly)?

**Comment by krlmlr** [comment]
FWIW, this problem seems to affect only users that don't have dplyr installed *and* use `=` for assignment in their code. So, we should update soon, but in the meantime it feels enough if the problem is discoverable. I adapted the description of this issue to that effect.

**Comment by krlmlr** [comment]
Zero-length input doesn't seem to be relevant for our use case here.

**Comment by lorenzwalthert** [comment]
Yes, thanks @krlmlr. I think the error is pretty informative, so it's not too bad. However, only if `style_text()` is used, in the other cases (e.g. with `style_dir()`) it will simply show in the summary table that there was an error with styling without further explanation. So this is unsatisfactory.

**Comment by lorenzwalthert** [comment]
@krlmlr maybe you can have a look at #324 where I simply c/p purrr code and import the required functions from purrr. `bind_rows()` was already implemented when we removed the dplyr dependency in #182.  It seems pretty straight forward.

**Comment by krlmlr** [comment]
Should we show a summary of the error messages with `style_dir()`?
