### ISSUE TITLE
Cascading assignment with "=" causes unclear error and can't convert to "<-"

### ISSUE THREAD

**Issue by aaronrudkin** [r-lib/styler#327]
This is valid R code:
```
j = k = l = NULL
```

Running styler's current CRAN version on it will cause it to error:
> Error in if (any(pd_flat$spaces < 0L)) { : 
>   missing value where TRUE/FALSE needed

I assume the cascading assignment tricks the parser into thinking one or more of these is a function argument, but I'm not certain.

**Comment by lorenzwalthert** [comment]
Thanks @aaronrudkin  for reaching out. Indeed that's a bug. I think I found the root of the problem and opened #328, which I will merge as soon as all CI checks pass.

**Comment by lorenzwalthert** [comment]
If you want to try yourself now, you can install this patch with:
```r
remotes::install_github("r-lib/styler#328")
```
Or once it's merged into master via 
```r
remotes::install_github("r-lib/styler")
```

**Comment by lorenzwalthert** [comment]
The problem was actually detected in [#276](https://github.com/r-lib/styler/pull/276#discussion_r149887954) but for some reason I forgot to fix it there before we merged.
