### ISSUE TITLE
Line broken again after first named argument

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/styler#342]
The below code should not be modified by styler.
``` r
styler::style_text(
"call(
  a, b = 3
)")
#> call(
#>   a,
#>   b = 3
#> )
```

Created on 2018-02-05 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

It seems as this undesired behaviour was introduced with #318.

**Comment by lorenzwalthert** [comment]
Similarly here, there is no reason to put a line break before the first named argument

``` r
styler::style_text(
"call(
  a, b, c, d, e = 3
)")
#> call(
#>   a, b, c, d,
#>   e = 3
#> )
```

Created on 2018-02-05 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by lorenzwalthert** [comment]
Ok, maybe that needs to depend on the `strict` option.

**Comment by lorenzwalthert** [comment]
In fact, solving this issue properly also needs #357, because a line break after the opening brace / or before the first unnamed argument also required an up-to-date `multi-line` attribute for a line break transformer.

**Comment by lorenzwalthert** [comment]
Reference: #357

**Comment by krlmlr** [comment]
I rather like this particular behavior, even if it was introduced by accident ;-)

Everything seems to work right for single-line argument lists:

``` r
styler::style_text(
"call(a, b, c, d, e = 3
)")
#> call(a, b, c, d, e = 3)
```

> Created on 2018-02-26 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by lorenzwalthert** [comment]
Haha ok. Even the example you just created was not indented 😊. However, I think the current behaviour does not reflect the [tidyverse style guide](http://style.tidyverse.org/syntax.html#long-lines). In particular, see https://github.com/tidyverse/style/issues/39.

**Comment by lorenzwalthert** [comment]
I mean it's not really a conflict, but in tidyverse/style#39, the idea was to keep the first few unnamed arguments on the same line as the opening parenthesis. Like
```r
map(x, f, 
  another_arg = 3
)
```

So far so good. However, if the code looks like this

```r
call(
  a, b = 3
)
```
styler should probably just leave it as is or move the a one line up, but it adds a line break after `a,` without removing the one before `a`.

```r
call(
  a,
  b = 3
)
```

So here, it's not the case that the first few unnamed arguments are on the same line as the opening brace.

**Comment by lorenzwalthert** [comment]
I mean if you think that's fine, we can leave it, but I think the preferred behaviour would be to either move the first argument one line up or leave the code unchanged, but not add a line break after a without removing it before it.

**Comment by lorenzwalthert** [comment]
Blocked by #357.

**Comment by krlmlr** [comment]
I thought the preferred styling would be

```r
call(
  a,
  b = 3
)
```

and we use 

```r
call(a,
  b = 3
)
```

only in exceptional situations?

**Comment by lorenzwalthert** [comment]
It depends on the initial formatting.
```r
call(
  a,
  b = 3
)
```
should be returned unchanged. Also,
```r
call(a,
  b = 3
)
```
So should
```r
call(
  a, b = 3
)
```
But 
```r
call(a, b = 3, 
  c = 3
)
```
should be turned into

```r
all(
  a, b = 3
)
```

And 
```r
call(
  a, b = 3
)
```

should be left untouched and not turned into 
```r
call(
  a, 
  b = 3
)
```

That's my understanding of tidyverse/style#39.

**Comment by krlmlr** [comment]
I don't mind the added newline when styling

```r
call(
  a, b = 3
)
```

because it's consistent with having named arguments on a separate line, similarly for the other example. But I think

```r
call(
  a, b =
    3
)
```

needs a line break before the `b`.

**Comment by lorenzwalthert** [comment]
I agree with the last example. The first one seems debatable to me. But with current `HEAD`, we at least don't change 
```r
call(a, 
  b = 3
)
```

Conclusion: Since the tidyverse style guide is not very clear on it and I just looked at it from a different angle than you, I think we can leave it for now.
