### ISSUE TITLE
style_file breaks hash-bang statement at top of script

### ISSUE THREAD

**Issue by jjramsey** [r-lib/styler#344]
If at the top of a script, there's a line that reads "#!/usr/bin/env Rscript", style_file will change it to

    # !/usr/bin/env Rscript

with a space after the "#". This prevents the script from being executed unless that extra space is removed. Not the end of the world but really annoying.

**Comment by lorenzwalthert** [comment]
Thanks @jjramsey, I did not think of that use case when I implemented that functionality. We could use regex to filter has-bang statements from the comments and avoid adding spaces to them after `#`. I outlined that in #345. Your comments, especially with regard to the proposed regex are welcome.
