### ISSUE TITLE
Style syntactically invalid files

### ISSUE THREAD

**Issue by krlmlr** [r-lib/styler#346]
lintr has infrastructure for extracting partial parse data from invalid source files, we could borrow that.

1. Create a `srcfile()`: https://github.com/jimhester/lintr/blob/e926089a0187aac01ce6981a798c5dc22e3a4273/R/get_source_expressions.R#L7
2. Use `tryCatch()` with `parse()` and this `srcfile`, this populates the parse data which then can be extracted:  https://github.com/jimhester/lintr/blob/e926089a0187aac01ce6981a798c5dc22e3a4273/R/get_source_expressions.R#L80

See examples in [`?parse`](https://www.rdocumentation.org/packages/base/versions/3.4.3/topics/parse).

**Comment by lorenzwalthert** [comment]
This is complicated by the fact that we don’t just read but also write back.
