### ISSUE TITLE
Supporting / handling indention with tabs

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/styler#347]
At today's Google Summer of Code Meetup, someone asked whether styler can also convert from tabs to spaces an vice versa, or simply use tabs for indention. I promised to open an issue 😄.
I think this is feasible, but the infrastructure needs some adaption. Do you @krlmlr consider this to be worth the effort? I don't know how urgent this is, but it would be a nice feature I think.

**Comment by krlmlr** [comment]
Tabs in source code can go wrong at so many levels, I'd rather not spend time thinking about this.

**Comment by lorenzwalthert** [comment]
Ok, we can close it and decide later.

**Comment by cadnza** [comment]
> Tabs in source code can go wrong at so many levels, I'd rather not spend time thinking about this.

At least [as of 2017 the majority of developers preferred tabs over spaces](https://insights.stackoverflow.com/survey/2017#:~:text=good%2C%20noisy%20debate.-,Tabs%20or%20Spaces%3F,-All%20Respondents). I've always loved the idea of styler, but every time I start working on a formatter, I'm turned off by the fact that it doesn't let me indent with tabs. This issue might be worth reopening.

**Comment by lorenzwalthert** [comment]
You can create your own style guide to do that pretty easily:
``` r
library(styler)
tab_style <- function() {
  sg <- tidyverse_style(indent_by = 1L)
  sg$indent_character <- "\t"
  sg
}

style_text('{\n1}', transformers = sg) |>
  as.character()
#> Error in eval(expr, envir, enclos): object 'sg' not found
```

<sup>Created on 2023-06-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Please also refer to https://styler.r-lib.org/articles/distribute_custom_style_guides.html for distribution.

**Comment by cadnza** [comment]
> You can create your own style guide to do that pretty easily:
> 
> ``` r
> 
> library(styler)
> 
> tab_style <- function() {
> 
>   sg <- tidyverse_style(indent_by = 1L)
> 
>   sg$indent_character <- "\t"
> 
>   sg
> 
> }
> 
> 
> 
> style_text('{\n1}', style = tab_style) |>
> 
>   as.character()
> 
> #> [1] "{"   "\t1" "}"
> 
> ```
> 
> 
> 
> <sup>Created on 2023-06-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
> 
> 
> 
> Please also refer to https://styler.r-lib.org/articles/distribute_custom_style_guides.html for distribution.

… Well shoot, that works perfectly. Thanks!
