### ISSUE TITLE
Pipe with conditions

### ISSUE THREAD

**Issue by vnijs** [r-lib/styler#355]
Styler is great. Makes my students' code easier to read.

When using pipes it is quite common (at least for me) to include conditions. Something like the code below, for example. Styler turns that into the 2nd code chunk below which I'm not a big fan of. I this the intended behavior? If so, is there a way to avoid it :)

```r
library(dplyr)
x <- 3
y <- x %>% {ifelse(. > 5, NA, .)}
```

```r
library(dplyr)
x <- 3
y <- x %>% {
  ifelse(. > 5, NA, .)
}
```

**Comment by lorenzwalthert** [comment]
Well, I think there are multiple solutions to that:
* Most obvious to me: Use `scope = "indention"`, which also means that you will turn of all line break rules, probably not exactly what you want.
* Manually remove the rule from the tidyvese style guide that forces a line breaks around curly braces. 
``` r
library(styler)
tidy_style_guide <- tidyverse_style()
tidy_style_guide$line_break$`partial(style_line_break_around_curly, strict)` <- NULL
style_text("
  library(dplyr)
  x <- 3
  y <- x %>% {ifelse(. > 5, NA, .)}
  ",
  scope = "line_breaks", transformers = tidy_style_guide)
#> 
#> library(dplyr)
#> x <- 3
#> y <- x %>% {ifelse(. > 5, NA, .)}
```

Created on 2018-02-24 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

Note that the name of the rule `partial(style_line_break_around_curly, strict)`  should actually be 
`style_line_break_around_curly` (#356), which we are very likely to change in the upcoming release (See Mile Stone styler 1.0.1).

None of the two solutions is probably exactly what you want though. I think you want to preserve curly brace expressions if they are not multi-lined. This is actually a bit more tricky. I opened #357 to discuss it.

**Comment by vnijs** [comment]
Thanks for the detailed reply and explanation @lorenzwalthert. Very useful. I really like the line breaks enforced by `styler` for curly braces for function calls, if-else, etc. However, I was wondering if curly braces, when used in a pipe, could (should?) be an exception to this rule (e.g., if burly braces are preceded by a pipe operator leave as-is).

**Comment by lorenzwalthert** [comment]
To be honest, I think we should encourage the use of the pipe with curly braces. I don't see it anywhere in the tidyverse. In your particular case, I could even imagine styler removing the obsolete curly braces and hence we'd get rid of the problem 😊 .

**Comment by lorenzwalthert** [comment]
Another way to go about it would be to adapt the rule for line breaks and curly braces to not break the line if the token right before it is a pipe. I experimented a bit with it and works in devel mode, I just have not posted it here because something else really strange goes on if I declare such a rule in the global environment without having styler loaded with `devtools::load_all()`. May open another issue at some point if I find time.

**Comment by vnijs** [comment]
Thanks for looking into this @lorenzwalthert! The extra rule (or condition) would be great. Below an example where you do need the { }

dc <- sapply(mtcars, class)
dc %>% {which(. %in% c("numeric", "integer"))}

**Comment by lorenzwalthert** [comment]
Yes, there are examples where you need them, agree 😊. Are you happy to close that for now and label it with `Status: Postponed` so we can come back to that if time permits?

**Comment by vnijs** [comment]
Sure. Thanks @lorenzwalthert
