### ISSUE TITLE
How to Debug Failures

### ISSUE THREAD

**Issue by fny** [r-lib/styler#360]
I've got an Rmd document that fails when being processed by styler, even though it's compiled by knitr without any issues.

> Warning message:
> When processing example.Rmd: Malformed file! 

Is there a verbose mode that exists to diagnose what might be happening?

**Comment by lorenzwalthert** [comment]
Not (yet) really. The reason for that failure is that, apparently, you don't have the same number of code chunks headers and footers (the lines that open/ close code chunks using back ticks). 
You could `debug(styler:::identify_r_raw_chunks()`, run styler again and further down in the code, `starts` identifies the lines which are taken as headers, and `stops` the ones that are footers. Do you have headers/footers that don't match the regex pattern used in the aforementioned function?
I agree though that the error message could be a bit more informative.
cc: @jonmcalder

**Comment by lorenzwalthert** [comment]
You could also do c/p to a separate file and do binary elimination (i.e. deleting the second half of they file, try stying, if it works, look at the first quarter of the file etc.)

**Comment by lorenzwalthert** [comment]
Did that help?

**Comment by fny** [comment]
Just got a chance to give things ago. I'll let you know tomorrow how things go. Thanks!

**Comment by lorenzwalthert** [comment]
Also, maybe use the devel version because I just saw that we updated the regular expression pattern in 1e381d92.

**Comment by fny** [comment]
Appears to be resolved now when using the development version.
