### ISSUE TITLE
Guarantee of correctness?

### ISSUE THREAD

**Issue by HenrikBengtsson** [r-lib/styler#368]
First timer of pkg (which looks really neat) here.  Without having looked into the details of the code myself, is the following statement correct:

  The code produced by `styler` will _always_ have the same AST ("parse tree") as the code going in?

If the above is correct, do `styler` functions validate this - something like `all.equal(ast_out, ast_in)` - before returning?

The reason why ask, is because when I get a big "hard-to-read" set of R code handed to me, I'd like to run it through a code formatter without having to worry that it might introduce bugs on top of what's already in the code.  If I know `ast_in` and `ast_out` are guaranteed to be identical (formally - not just "yeah, they should be the same") then I don't have to worry about that part.

Thanks

**Comment by HenrikBengtsson** [comment]
Hmm... maybe this cannot be guaranteed, e.g. since `x = 1` is reformatted as `x <- 1`:
```r
> styler::style_text("x = 1")
x <- 1
```
we don't get the same AST:
```r
> str(as.list(parse(text = "x = 1")[[1]]))
List of 3
 $ : symbol =
 $ : symbol x
 $ : num 1

> str(as.list(parse(text = "x <- 1")[[1]]))
List of 3
 $ : symbol <-
 $ : symbol x
 $ : num 1
```

However, I wonder if there are other cases like this, or the assignment operators `=` / `<-` are unique in this sense.  If the latter is the case, I guess I could set up a "styler" that preserves `x = 1` as is and then I can validate the correctness. Only then, as a last step, I can do transformation of any `x = 1` to `x <- 1`.  I really would like to be able to do re-formatting at scale / automatically without having to worry about correctness.

**Comment by lorenzwalthert** [comment]
> Only then, as a last step, I can do transformation of any x = 1 to x <- 1.

Exactly. Styler validates if it can validate, which is the case if you set `scope = "line_breaks"`. The corresponding source code is  [here](https://github.com/r-lib/styler/blob/master/R/transform-files.R#L119) and [here](https://github.com/r-lib/styler/blob/master/R/transform-files.R#L201-L211).

 Hence, I suggest you to:

1. Check initial code into git. 
2. Get the brand new styler 1.0.1 from CRAN with some relevant enhancements you can find in the [release notes](https://github.com/r-lib/styler/releases/tag/v1.0.1).
3. First style with `scope = "line_breaks"` and hope you don't get the error mentioned above (to my best knowledge, no one ever reported that error, so I am confident styler does indeed not change the AST). Also, have a look at the other options of the style guide with `?tidyverse_style` such as `strict` before you style.
4. Review and commit changes styler made to your code.
5. Style with `scope = "tokens"` and manually inspect the changes. Should not be that many I hope.

**Comment by lorenzwalthert** [comment]
For reference: Early discussion of so-called roundtrip validation were brought up in #85 and later in #140. Roundtrip validation was introduced in mainly in  #287, tests were added in #289.

**Comment by lorenzwalthert** [comment]
For completness: Note that there are other transformations apart from `=` to `<-` that styler performs with `scope = "tokens"` that change the AST. Here a few examples:

* Adding curly braces to if statements (if there are none) that are multi-line.
* Put statements separated with `;` on two lines.

In addition, for all levels of scope, comments that are not shebang, knitr chunk headers or roxygen comments are forced to start with at least one space, i.e 

``` r
styler::style_text("#a", scope = "line_breaks")
#> # a
```

Created on 2018-03-13 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

Maybe that should not be the case for `scope < "tokens"`. Note that this does not trigger a validation error because we compare two parsed objects (with `styler:::expressions_are_identical()`), which drops all comments.

**Comment by lorenzwalthert** [comment]
Do you @HenrikBengtsson think we should add a note in the documentation about when a verification can be expected?

**Comment by lorenzwalthert** [comment]
The message
> Please review the changes carefully!

is deliberately only printed for `scope = "tokens"` and only if the AST was changed. I think we'll add an note in the helpfiles. So I don't understand what your last code example is about? Is there a problem with the changed wholeSrcef?

**Comment by HenrikBengtsson** [comment]
Thanks for confirming.

My code examples are just for others stumbling upon this thread and for my future self - everything works as expected.  The last piece using `diffobj::diffDeparse()` is just to show what those 30 diffs look like (i.e. `=` updated to `<-`) plus it's a neat way to view the diff from within R (as an alternative to `diff` / `git diff`).   (I didn't look into the details how to `diffDeparse()` how to not compare `srcref` - if that was you question).

**Comment by lorenzwalthert** [comment]
Ok. Well my question was just about the very last line. It seemed spurious that `1070L`, and `1038L` are flipped. But I concluded from your response that this is not of any relevance at this point, right?

**Comment by HenrikBengtsson** [comment]
You're saying you'd expect `1038L` vs `1070L` rather than `1070L` vs `1038L`?  I used "after" vs "before" when diffing.  The "tokens" output got more lines (1070) than the "line_breaks" output (1038) because of changes like:
```r
            if(rmoutlier){Po=fcorrect(pbin,Po)}
```
to
```r
      if (rmoutlier) {
        Po <- fcorrect(pbin, Po)
      }
```
