### ISSUE TITLE
Issues with Rmd Styling

### ISSUE THREAD

**Issue by ramnathv** [r-lib/styler#385]
I am running into an `Error: Malformed file` while trying to style Rmd files with non-R code chunks. Here is a reproducible example that throws this error.

    ---
    title: My Document
    ---

    This is a code chunk with YAML

    ```
    key: 1
    value: 20
    ```

**Comment by lorenzwalthert** [comment]
Thanks for reporting this. Seems as we don't currently support code chunks that don't have an engine. Will looki into it next week. cc: @joncalder
