### ISSUE TITLE
pkgdown Changelog page not reflecting NEWS.md

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/styler#392]
@krlmlr any ideas why this is not in sync?

**Comment by krlmlr** [comment]
Maybe it works better if `NEWS.md` uses first-level headers for the version (styler x.y.z ...)?

**Comment by lorenzwalthert** [comment]
Just tried that, let's see what happens.

**Comment by lorenzwalthert** [comment]
Unfortunately, now we can't even deploy master successfully with tic at release -.-

**Comment by lorenzwalthert** [comment]
I managed to build successfully locally and the headers are now right.

**Comment by lorenzwalthert** [comment]
fixed in 7bb978be05dc2987eeb606995aa8bab781738608
