### ISSUE TITLE
Inconsistent styling of infix operator "^"

### ISSUE THREAD

**Issue by dchiu911** [r-lib/styler#394]
Not sure if this is a `styler` or `lintr` issue, but there seems to be some inconsistency in styling spaces around `^`.
``` r
styler::style_text("2 ^ 4")
#> 2^4
lintr::expect_lint("2 ^ 4", NULL)
utils::packageDescription("styler")$RemoteSha
#> [1] "b5a462c0844b4b7ac41f893317df56fd32f51a42"
utils::packageDescription("lintr")$RemoteSha
#> [1] "fe4104a2d1c5c6ae9ad8daa79925c9d11127c142"
```

Created on 2018-05-30 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by lorenzwalthert** [comment]
Right. I think we updated styler according to https://github.com/tidyverse/style/pull/46/ in https://github.com/r-lib/styler/pull/308.
cc: @jimhester.

**Comment by dchiu911** [comment]
New PR jimhester/lintr#321
