### ISSUE TITLE
Try getting fork commits merged into master if useful

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/styler#398]
There are currently 25 forks. In a few of them, useful features were implemented. We should: 

1. Figure out what features are implemented in forks and which ones are potential candidates to be merged with upstream.
2. Figure out why people have not (yet) created pull requests in the upstream repo. **If you have forked and not submitted a PR, you are welcomed to comment bellow.** We'd love to have more contributors in general if the contributions meet requirements outlined in `CONTRIBUTING.md`.
3. Try to motivate the people of concern to submit PRs.

In all cases, we need to synchronize with the release schedule (#397).

**Comment by riccardoporreca** [comment]
@lorenzwalthert, see my [comment](https://github.com/r-lib/styler/issues/340#issuecomment-398660024) in #340 for the context around fork [miraisolutions/styler](https://github.com/miraisolutions/styler).

**Comment by lorenzwalthert** [comment]
Think we are good for now.
