### ISSUE TITLE
Fails: styler::style_text("a = 1; b = c = 1")

### ISSUE THREAD

**Issue by maurolepore** [r-lib/styler#403]
Is this behaviour expected ?

``` r
# Fails
styler::style_text("a = 1; b = c = 1")
#> Error in if (any(pd_flat$spaces < 0L)) {: missing value where TRUE/FALSE needed
# Passes
styler::style_text("b = c = 1")
#> b <- c <- 1
```

Created on 2018-07-06 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0.9000).

**Comment by lorenzwalthert** [comment]
No this should definitively not happen. Thanks for reporting, will look into it.
