### ISSUE TITLE
Integrating stylermd into styler

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/styler#410]
@krlmlr what do you think? I am not talking of now, we need a lot more people using [stylermd](https://github.com/lorenzwalthert/stylermd), providing feedback so we can get into a stable life cycle, but eventually I think these two packages belong together :-)

**Comment by krlmlr** [comment]
Not sure, why not add a line break after each full stop?

**Comment by lorenzwalthert** [comment]
?

**Comment by lorenzwalthert** [comment]
Sorry, stylermd is not for code files and it can't (yet) style comments in pure code .R files. But it can style non-code elements, which are also prevalent in directories involving R code, e.g. README, NEWS, vignettes, bookdown projects, blogdown projects etc.

**Comment by lorenzwalthert** [comment]
> #' I try to avoid this problem altogether by adding a line
#' break after each full stop.
#' This means that edits in previous sentences do not 
#' affect the indentation of the current sentence.
#' But I agree that _stylermd_ is still useful here because
#' it can wrap the individual sentences.

Anyways, that's a good way of writing. Never thought of it. 👍

**Comment by krlmlr** [comment]
Bottom line: the functionality still feels useful, why not merge it with _styler_ at some point?

**Comment by lorenzwalthert** [comment]
Ok. Cool. Will reconsider after stylermd is past beta testing.

**Comment by lorenzwalthert** [comment]
In the meantime, feedback is welcomed.

**Comment by lorenzwalthert** [comment]
In fact, we could already integrate it in some branch which we keep rebasing on master, so people can use the functionality as part of styler before we merge the two packages.

**Comment by lorenzwalthert** [comment]
Done. You can install it like this: 

```r
devtools::install_github("lorenzwalthert/styler@integrate-stylermd")
```

Note that this adds a dplyr dependency to styler which we eventually need to get rid of. I created the integration because it's easier for testing to have just one API for styling files. Far from merging this into upstream.

**Comment by lorenzwalthert** [comment]
The question is how the API should change for `style_dir` and friends. @krlmlr any ideas? Because we have the argument `file_type` defaulting to `"R"`. Integrating stylermd into styler would mean it can style any extension which is kind of awkward. I think `style_dir()` and friends should only style R related files. Otherwise, we might end up with people styling YAML files unintended, so we'd only need to change `style_file()`. The current API is
```r
style_file(path, ..., 
  style = tidyverse_style, 
  transformers = style(...), 
  include_roxygen_examples = TRUE
)
```

So should we just leave it as is? Because only `style_dir()` and friends have an argument `file_type`:

```r
style_dir(path = ".", ..., 
  style = tidyverse_style, 
  transformers = style(...), 
  filetype = "R", 
  recursive = TRUE, 
  exclude_files = NULL, 
  include_roxygen_examples = TRUE
)
```

**Comment by lorenzwalthert** [comment]
Out of scope since {stylermd} not developed anymore.
