### ISSUE TITLE
syntax highlighting in print.vertical()

### ISSUE THREAD

**Issue by wlandau** [r-lib/styler#417]
It would be nice to see syntax highlighting when I print out styled code in the console and in `knitr` / R Markdown reports:

```r
styler::style_text("
function(x){
  x * (sqrt(5) + 1) / 2 
}
")
#> 
#> function(x) {
#>   x * (sqrt(5) + 1) / 2
#> }
```

Motivating use case: https://github.com/ropensci/drake/issues/489. Packages that may help:

- [`fansi`](https://github.com/brodieG/fansi)
- [`prettycode`](https://github.com/r-lib/prettycode)
- [`crayon`](https://github.com/r-lib/crayon)
- [`highlight`](https://github.com/romainfrancois/highlight)
- [`highr`](https://github.com/yihui/highr)
- [`colorout`](https://github.com/jalvesaq/colorout)

**Comment by lorenzwalthert** [comment]
Thanks for raising the issue and putting all the references here, really appreciate that. In fact, this should be straightforward. See my branch [highlight-print-vertical[(https://github.com/lorenzwalthert/styler/tree/highlight-print-vertical) for a primer. Using `prettycode::highlight()` seems to be a good solution. Have not tested the others. The dependency would probably be added under `Suggests`.
