### ISSUE TITLE
Incomplete "Styling roxygen..." vignette/article

### ISSUE THREAD

**Issue by ClaytonJY** [r-lib/styler#420]
You probably know this, but I didn't see a related issue so I thought I should point out [this page](http://styler.r-lib.org/articles/styling-roxygen-code-examples.html) is essentially empty, because the associated vignette is essentially empty. Possibly a mis-commit?

**Comment by lorenzwalthert** [comment]
Thanks, I forgot about this. Not sure if we should remove the vignette completely or write a high-level overview of how #381 works.

**Comment by ClaytonJY** [comment]
Unfortunately I don't know enough to help; trying to see if I can grok the parse tree enough to add some additional pedantry to tidy style, and saw this while clicking through the pkgdown site articles. Good luck!

**Comment by lorenzwalthert** [comment]
Ok thanks. Well I did not expect you to contribute, so no worries, I rather thought you just wanted to bring up the fact that i should be either deleted or completed. If I find time I may compete it at some point.  Thanks.

**Comment by lorenzwalthert** [comment]
Lets delete the vignette for now.

**Comment by lorenzwalthert** [comment]
Was removed in 9458f8ac.
