### ISSUE TITLE
Braces in function calls

### ISSUE THREAD

**Issue by krlmlr** [r-lib/styler#428]
Can we keep the newline after `(` here?

``` r
text <- '
eventReactive(
  {
    code()
  },
  {
    code()
  }
)
'

styler::style_text(text)
#> 
#> eventReactive({
#>   code()
#> }, {
#>   code()
#> })
```

<sup>Created on 2018-09-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by lorenzwalthert** [comment]
Maybe. I liked it that way more though, it's more compact. Is there a rule in the tidyverse style guide that discourages this use? Note that with `strict = FALSE`, the output is not as desired, i.e. there should be indention for the braces: 
``` r
text <- '
eventReactive({

    code()
},
    {
    code()
    }
    )
    '

styler::style_text(text, strict = FALSE)
#> 
#> eventReactive({
#> 
#>   code()
#> },    {
#>   code()
#> }
#> )
```

<sup>Created on 2018-09-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by krlmlr** [comment]
It's more compact, but it's much less readable, because it's very easy to overlook the `}, {` . And when you find it, you wonder what the meaning is.

I'm not aware of any specific rule.

**Comment by krlmlr** [comment]
We only have a contradicting rule in 2.4:

> Code that is related to a brace (e.g., an if clause, a function declaration, a trailing comma, …) must be on the same line as the opening brace.

The two braces are not related, one could argue that they shouldn't be on the same line by negation.

If we add additional arguments, indentation starts looking really weird, although no rule seems to specify this either:

``` r
text <- '
eventReactive(
  {
    code()
  },
  {
    code()
  },
  label = "label"
)
'

styler::style_text(text)
#> 
#> eventReactive({
#>   code()
#> }, {
#>   code()
#> },
#> label = "label"
#> )
```

<sup>Created on 2018-10-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

The style guide seems to prefer brevity over comprehensiveness. If we want a comprehensive style guide, we could add an appendix where all the rules are formalized. Or we just use common sense and agreement :-o

**Comment by krlmlr** [comment]
Also interesting:

``` r
text <- '
library(dplyr, warn.conflicts = FALSE)
tibble(x = 1) %>% 
  mutate(y = { x <- 2; x }, z = x)
'

styler::style_text(text)
#> 
#> library(dplyr, warn.conflicts = FALSE)
#> tibble(x = 1) %>%
#>   mutate(y = {
#>     x <- 2
#>     x
#>   }, z = x)
```

<sup>Created on 2018-10-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

I think that function arguments that consist of a braced expression always need to start on a new line, unless it's the last argument and all other arguments fit on the line of the function call:

```r
tryCatch(
  {
  },
  error = function(e) {
  }
)

with_envvar(c(ENV = "var"), {
})

test_that("test", {
})
```

**Comment by krlmlr** [comment]
Working on that Shiny code now, letting _styler_ have its way even if I don't like the formatting because I'm tired of undoing... (And we called it "non-invasive" ;-) )

Any chance we can achieve consensus here?

**Comment by lorenzwalthert** [comment]
Note that we pretty much had this discussion before: https://github.com/r-lib/styler/issues/125.

**Comment by lorenzwalthert** [comment]
I think this is the rule that makes sense once #347 is resolve from above: 

> function arguments that consist of a braced expression always need to start on a new line, unless it's the last argument and all other arguments fit on the line of the function call:

**Comment by lorenzwalthert** [comment]
It seems as we don't need #357 anyways because the line break is added in the same nest as the check for multi-line (via column `lag_newlines`) happens in other places.
