### ISSUE TITLE
Set transformers for RStudio addin or for all styler functions?

### ISSUE THREAD

**Issue by courtiol** [r-lib/styler#436]
Hi there,

Perhaps I missed it in the doc, but I did not get how to setup one's favorite style so that it can be used with the addin (style selection). Or more generally, since not all functions take "style" as input, would there be a way to declare as an R option or something the style one wants to apply to any styler function?

In any case, a truly useful package!!

Tx

Alex
PS: @krlmlr perhaps consider presenting it a R meetup Berlin (if you have not done so...).

**Comment by lorenzwalthert** [comment]
There is indeed currently no way in the upstream repo to set the style guide for the Addin. There is a fork that implements that and an issue to merge back useful features from forks (#398).

As far as setting defaults go, there are also considerations, e.g. #319. This is not likely to be implemented soonish, i.e. not by the end of the year. For now, you can write your own wrapper or use `purr::partial()` if you find yourself using different defaults all the time. Sorry for the inconvenience.

**Comment by riccardoporreca** [comment]
@lorenzwalthert, the fork was rebased, see the corresponding PR #463.

**Comment by lorenzwalthert** [comment]
Closed with #463.
