### ISSUE TITLE
`styler` and `lintr` interaction

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/styler#437]
If I have a code like this in `R` script 
```r
italic(chi) ^ 2
```
and I run `styler`, it is changed to
```r
italic(chi)^2
```

But this conflicts with `lintr::lint_package()` recommendation- 

> Put spaces around all infix operators.

Not sure what's the correct way here, if there is one.

**Comment by lorenzwalthert** [comment]
There is one. We had an issue about it which I could not find quickly but I think both styler and linter adapted to the rule in section [2.2.3](https://style.tidyverse.org/syntax.html#infix-operators) to not place a space around some operators, including ^.

**Comment by IndrajeetPatil** [comment]
Gotcha! 

This also explains a peculiar thing I've noticed. If I create sections in my `R` scripts using-

```r
    #===================== plot ==============================
```
`styler` add a space at the beginning. 

```r
    # ===================== plot ==============================
```

I am guessing it thinks that this is `==`? Because it doesn't do this when I use-
```r
    #----------------------------------- plot ------------------------------------------------------
```

**Comment by IndrajeetPatil** [comment]
I downloaded the development version of `lintr` and I no longer get this conflict.
