### ISSUE TITLE
conflict between `lintr` and `styler` about curly brackets

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/styler#438]
If I have a code like the following-
```r
  iris %>% 
  {if (x != 2) {
    dplyr::select(.data = ., -Species) %>%
      tibble::as.tibble(.)
  } else {
    tibble::as.tibble(.)
  }}
```

And style it using `styler`, it changes to-
```r
  iris %>%
  {
    if (x != 2) {
      dplyr::select(.data = ., -Species) %>%
        tibble::as.tibble(.)
    } else {
      tibble::as.tibble(.)
    }
  }
```

But this produces the following marker from `lintr`:
```r
Opening curly braces should never go on their own line and should always be followed by a new line.
```

**Comment by lorenzwalthert** [comment]
Thanks. I can't reproduce it on Windows 10 with the CRAN version of styler (1.0.2) using `style_text` or the Addin. Which styler version are you using?

**Comment by lorenzwalthert** [comment]
Thanks. Will look into this later this week but as a warning, R devel and styler are currently not guaranteed to work well together because of #419.

**Comment by nlarusstone** [comment]
I'm encountering the same issue in R 4.0.3. Package versions:
```
> packageVersion("lintr")
[1] ‘2.0.1’
> packageVersion("styler")
[1] ‘1.3.2’
```

**Comment by lorenzwalthert** [comment]
Thanks. I refer to https://style.tidyverse.org/syntax.html#indenting, in particular 2.4.1:

> Curly braces, `{}`, define the most important hierarchy of R code. To make this hierarchy easy to see:
> * `{` should be the last character on the line. Related code (e.g., an if clause, a function declaration, a trailing comma, …) must be on the same line as the opening brace.
> * The contents should be indented by two spaces.
> * `}` should be the first character on the line.

```r
# good
tryCatch(
  {
    x <- scan()
    cat("Total: ", sum(x), "\n", sep = "")
  },
  interrupt = function(e) {
    message("Aborted by user")
  }
)
```

For that reason, styler formatting matches the tidyverse style guide. Note that Jim Hester already disagreed on that edge case before in https://github.com/r-lib/styler/issues/549#issuecomment-537199860.

**Comment by nlarusstone** [comment]
Sorry -- my message wasn't clear. I don't have strong opinions about the right way to do this in R and I don't have this exact code, I simply had the issue where `styler` would auto-correct code and then `lintr` would fail.

It looks like the recommend solution is:
```r
tryCatch(
  expr = {
    ...
  }
)
```

It's kind of difficult to figure that -- perhaps this could be a docs issue?

**Comment by lorenzwalthert** [comment]
Not sure why we should document it in styler. Once you run styler, it will result in correct formatting. I believe the solution to this is that lintr does stop complaining about this formatting, because it is Tidyverse style compliant. For that, you'd have to open an issue in lintr (or simply deactivate this particular rule). So what I am trying to say is that this is not a styler issue when lintr complains.

**Comment by IndrajeetPatil** [comment]
You can have a `.lintr` like the following to avoid this issue:

```
linters: with_defaults(open_curly_linter = NULL, closed_curly_linter = NULL)
```
