### ISSUE TITLE
Get rid of enc package

### ISSUE THREAD

**Issue by krlmlr** [r-lib/styler#439]
As a stop-gap, we can use `xfun::read_utf8()` and `xfun::write_utf8()`. There's `fs::dir_map()` which we can use for iterating over files.

**Comment by lorenzwalthert** [comment]
Do you plan to no longer maintain the `enc` package or what is the rationale behind moving to `xfun`?

**Comment by lorenzwalthert** [comment]
I am planning to do a CRAN submission in the next 5 days because of #419. It needs to be resolved in the CRAN version by Nov 20 to *safely retain the package on CRAN*. Should we substitute `enc` before that?

**Comment by krlmlr** [comment]
That would be great. I'm no longer sure _enc_ has a purpose.

We can move the relevant parts from _enc_ to _styler_.
