### ISSUE TITLE
styler result different for strings depending on type of enclosing quote

### ISSUE THREAD

**Issue by wdearden** [r-lib/styler#458]
The result of 
```
styler::style_text(
"
\"SELECT *
FROM table
\"
"
)
```
is 
```
"SELECT *
FROM table
"
```
but the result of 
```
styler::style_text(
"
'SELECT *
FROM table
'
"
)
```
is 
```
"SELECT *\nFROM table\n"
```

I think the preferred behavior should be the first result.

**Comment by lorenzwalthert** [comment]
Thank. A related issue is that `\n` is always resolved into an actual line break:

``` r
styler::style_text("\"SELECT *\nFROM table\n\"\n")
#> "SELECT *
#> FROM table
#> "
```

<sup>Created on 2019-01-18 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

We can solve the problem outlined by @wdearden with a solution that does not affect the problem presented just above so I think we should do it.
