### ISSUE TITLE
CI builds keep failing

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/styler#46]
Since I [added](https://github.com/krlmlr/styler/pull/40/files) pkgload, all builds keep failing. Also see #43. You can see the history [here](https://ci.appveyor.com/project/lorenzwalthert/styler-bp2vm/history). Travis builds don't fail. I was wondering why. The error is also not always the same. It is either 
after trying to install [`r-pkgs/callr`](https://ci.appveyor.com/project/lorenzwalthert/styler-bp2vm/build/1.0.79) (which should actually be `r-lib/callr`) or [`r-pkgs/pkgbuild`](https://ci.appveyor.com/project/lorenzwalthert/styler-bp2vm/build/1.0.78). Maybe it is due to the wrongly specified dependencies in pkgload with r-ib / r-pkgs, so I created two PRs for 
[pkgbuild](https://github.com/r-lib/pkgbuild/pull/7) and [pkgload](https://github.com/r-lib/pkgload/pull/37) to fix the DESCRIPTION file. It might be unrelated though since Travis does not fail.

**Comment by krlmlr** [comment]
Thanks. The r-pkgs queries should be forwarded to r-lib, but it's good to have it corrected. Looking into AppVeyor failures.

**Comment by krlmlr** [comment]
Seems we need to wait for https://github.com/r-lib/remotes/issues/41.

**Comment by lorenzwalthert** [comment]
Now we even have failing travis builds. Seems related to tic, as it says [devtools is missing](https://travis-ci.org/krlmlr/styler/builds/249328989#L1804) for deployment.

**Comment by krlmlr** [comment]
Yes, we need to replace devtools with pkgload in the README.Rmd file and also fix the code, because it's rendered for tags.

**Comment by lorenzwalthert** [comment]
The appveyor build keeps [failing](https://ci.appveyor.com/project/krlmlr/styler/build/1.0.69), this time due to the remote dependency`utf8`. Isn't `tic` installing the remote dependencies?

**Comment by lorenzwalthert** [comment]
travis also keeps failing, probably also a [`tic`](https://travis-ci.org/krlmlr/styler/builds/251979400#L2169) issue.

**Comment by krlmlr** [comment]
I fixed the build to create the pkgdown only for tags, and fixed tic to install the package in a temporary library before building the pkgdown. Let's see.

**Comment by krlmlr** [comment]
I've also looked into fixing AppVeyor.

**Comment by lorenzwalthert** [comment]
Cool, now it seems all builds pass and the badges are correct. Thanks @krlmlr 😊

**Comment by krlmlr** [comment]
Yeah, but we need to keep an eye on these tests, because they seem to be too forgiving now.

**Comment by lorenzwalthert** [comment]
We currently have failing travis builds due to a vignette build error
> Error in loadVignetteBuilder(vigns$pkgdir) : 
  vignette builder 'knitr' not found
Calls: <Anonymous> -> loadVignetteBuilder

Same problem occurs in my [fork](https://ci.appveyor.com/project/lorenzwalthert/styler-bp2vm#L299).

A failing travis build probably due to wrong R internals version. It was suggested to simply [empty the cache](https://github.com/tidyverse/lubridate/issues/578#issuecomment-334610454) for pre-installed packages.

@krlmlr any ideas why these, in particular the first problem, occur? Also, can you grant me admin rights to the appveyor CI?

**Comment by krlmlr** [comment]
Can you try removing the `cache` setting in `appveyor.yml`? I'm not sure how to grant you admin access, now the package is part of the r-lib organization.

**Comment by lorenzwalthert** [comment]
Ok, did so and pushed to my fork so we can try there before pushing to upstream.

**Comment by lorenzwalthert** [comment]
Any idea about the first problem? Should I try an older version of tic?

**Comment by lorenzwalthert** [comment]
I added code to manually install knitr in the before_install: step but it did not help.

**Comment by krlmlr** [comment]
Very strange, *knitr* seems to be installed indeed. No idea, perhaps this issue will vanish if we wait a few days?

**Comment by lorenzwalthert** [comment]
Ok. Just re-triggered the build and it's now only failing for R versions before current release.

**Comment by lorenzwalthert** [comment]
Ok, appveyor removing the cache worked. 😊 Will try the same with travis.

**Comment by krlmlr** [comment]
Seeing this in dplyr now. Debugging the job on Travis to see what's going on.

**Comment by krlmlr** [comment]
@gaborcsardi: This looks like an *rcmdcheck* problem: On R 3.3 (tested in a Travis session) and earlier (not yet tested), `rcmdcheck::rcmdcheck()` can't find the vignette builder even though it's installed. Does this ring a bell?

Working on replicating the problem locally.

**Comment by gaborcsardi** [comment]
rcmdcheck just calls  `R  CMD check`, so I am not sure why this should happen. It does juggle with environment variables, etc. so I am not saying it is impossible.

**Comment by krlmlr** [comment]
Can't replicate locally. Noticed that Travis CI has `R_LIBS_USER` set to the path for cached packages, and R 3.3 puts this path last in `.libPaths()`.

I'll resume debugging in Travis CI tomorrow.

**Comment by lorenzwalthert** [comment]
👍 thanks.

**Comment by lorenzwalthert** [comment]
Yet another issue: https://travis-ci.org/r-lib/styler/jobs/383405658#L5167

**Comment by lorenzwalthert** [comment]
Closed for now with #407.

**Comment by lorenzwalthert** [comment]
It seems as there is a new on travis when trying to install a package is not available for a certain R version. 

> Error: (converted from warning) package ‘DiagrammeR’ is not available (for R version 3.1.3)

How should we handle this? @krlmlr any experience from tibble or dplyr with it?

**Comment by lorenzwalthert** [comment]
FYI: For everyone else who watches this *repo* and who does not want to get notifications about this *issue* (or any other issue), you can mute individual issues on the right side of the page, below the labels. This issue is likely to be closed and opened a few times in the feature.
