### ISSUE TITLE
Integration with ALE

### ISSUE THREAD

**Issue by wmayner** [r-lib/styler#465]
Since `styler` seems to be the best option for R code fixing, it would be great for Vim users if it were integrated with [ALE](https://github.com/w0rp/ale/), a code linter and fixer for Vim.

See also the [related issue in ALE](https://github.com/w0rp/ale/issues/1483).

**Comment by lorenzwalthert** [comment]
Cool. I think it would be a nice if ALE would use styler. However, I am not a VIM user, so I am not sure what I can contribute. How the styler API works should be clear I guess, I am happy to assist on this part though.

**Comment by tvatter** [comment]
I just made a PR for such an implementation. I don't know much about vim script, so it is really minimal (i.e., it uses the tidyverse style and does not offer the possibility of using options), but it works. Don't hesitate to use my fork while waiting for @w0rp to accept/reject it.

**Comment by w0rp** [comment]
I'll have a look when I'm back from my holiday.

**Comment by tvatter** [comment]
No problem, it's not urgent at all.

**Comment by lorenzwalthert** [comment]
Awesome, happy to see this happening.

**Comment by tvatter** [comment]
The PR has been merged to the master branch of ALE. I think that this resolves this issue.

**Comment by lorenzwalthert** [comment]
Pretty cool.

**Comment by wmayner** [comment]
Awesome!
