### ISSUE TITLE
Move leading commas to end of previous line

### ISSUE THREAD

**Issue by rjake** [r-lib/styler#477]
Similar to #402 I would like for arguments on a new row that begin with a comma to move up to the previous line

![image](https://user-images.githubusercontent.com/14003618/54061281-287f2380-41ce-11e9-9852-9924f5734d69.png)

When I use this code:
```r
x <-
    "mpg %>%
    summarise(avg_cty = mean(cty)
              , avg_hwy = mean(hwy)
              , n = n()
              , n_class = n_distinct(class))"

style_text(x)
```

I get this result:

![image](https://user-images.githubusercontent.com/14003618/54061349-772cbd80-41ce-11e9-9679-68f93d65271e.png)

**Comment by lorenzwalthert** [comment]
Thanks @rjake. Indeed, #402 was only solved partially. Now I hope with #479 we can cover it fully.
