### ISSUE TITLE
Indent to end of previous function

### ISSUE THREAD

**Issue by rjake** [r-lib/styler#478]
I accustomed to this convention where all additional arguments are aligned with the first.

![image](https://user-images.githubusercontent.com/14003618/54061674-d8a15c00-41cf-11e9-845d-fbdc798aa365.png)

Currently, this code:
```r
x <-"
    mpg %>%
    summarise(avg_cty = mean(cty), 
              avg_hwy = mean(hwy),
              n = n(), 
              n_class = n_distinct(class))

    "
style_text(x)
```
comes back as 
![image](https://user-images.githubusercontent.com/14003618/54061680-e22ac400-41cf-11e9-8f85-dac95e6088f8.png)

**Comment by lorenzwalthert** [comment]
Thanks. Unfortunately, this is not in line with the guidelines in the tidyverse style guide, see section [2.5](https://style.tidyverse.org/syntax.html#long-lines) of the style guide. For this reason, we do not support this in `tidyverse_style()`.

**Comment by rjake** [comment]
I see, I'll work to use that style. Thanks for the good work. This package it's excellent!
