### ISSUE TITLE
Ignore bash (.sh) scripts?

### ISSUE THREAD

**Issue by skirmer** [r-lib/styler#487]
After linting a folder, I found that it had impacted my .sh files, which I think is not the desired effect. Am I right that styler should skip these? Specifically, it added a space before `$` which made quite a bit of difference in the bash scripts. (Love the package, thank you for all the work that went into this!)

**Comment by skirmer** [comment]
By the way, if my interpretation is correct, I'd be happy to submit a PR to fix it.

**Comment by skirmer** [comment]
Upon a second try, I can't actually seem to replicate the issue, so closing this. Sorry!

**Comment by lorenzwalthert** [comment]
No problem 😄. Note that #345, #344 are somewhat related. However, file with extensions other than R or Rmd should not ever be styled.
