### ISSUE TITLE
Support stdin and stdout as input file and output file in command line?

### ISSUE THREAD

**Issue by yech1990** [r-lib/styler#494]
will it be possible?

my solution: (require readr package)

```bash
cat test.R| R --slave --no-restore --no-save -e "styler::style_text(readr::read_file((file(\"stdin\"))))"
```

**Comment by lorenzwalthert** [comment]
Thanks for clarifying. I think an alternative would be the following: 

* Put an executable R script with shebang in a place that is part of your PATH or in a new directory and add that directory to your path. I am on Mac, so I put `export PATH = $PATH:~/custom_bin`  in `.bash_profile` and then put the following script in the `custom_bin` directory: 
 
* Extend your PATH  variable permanently

**Comment by yech1990** [comment]
How about adding stdin argument into styler.

It is possible to do that in formatR.

```bash
cat test.R | R --slave --no-restore --no-save -e "formatR::tidy_source('stdin')" 
```

**Comment by yech1990** [comment]
For vim plugin support, the formatter tool should be a single excutable or a one liner code. 
Packing styler into script not a good solution, cause you need to generate the script manually when you start a new environment.

**Comment by lorenzwalthert** [comment]
> For vim plugin support, the formatter tool should be a single excutable or a one liner code.
Packing styler into script not a good solution, cause you need to generate the script manually when you start a new environment. 

Ok. So we have support for styler in ale, just added a few days ago, which is a  VIM Plug-in: https://github.com/w0rp/ale/pull/2401#issuecomment-485942966. Maybe this is what you are looking for?

**Comment by yech1990** [comment]
I also push a commit for styler support in neoformat, but it is not perfect. I need readr for styler.

**Comment by lorenzwalthert** [comment]
But why not using the approach I used above with readLines(file(„stdin“)) instead of the approach with readr?

**Comment by yech1990** [comment]
I forget to close file, and got some error in the first attempt. 

It works fine now. Thank you @lorenzwalthert 

---
BTW, the performance of styler is a little slow.  Even if the file is well formatted.

styler::style_text (for 20 lines of R code)

```
cat test.R  0.00s user 0.00s system 79% cpu 0.001 total
R --slave --no-restore --no-save -e   0.40s user 0.02s system 100% cpu 0.411 total
```

black formatter of python (for a large file)

```
> time black -l 79 test.py
reformatted test.py
All done! ✨ 🍰 ✨
1 file reformatted.
black -l 79 test.py  0.14s user 0.02s system 38% cpu 0.406 total

> time black -l 79 test.py
All done! ✨ 🍰 ✨
1 file left unchanged.
black -l 79 test.py  0.07s user 0.01s system 99% cpu 0.082 total
```
