### ISSUE TITLE
R CMD CHECK ERROR on r-devel-linux-x86_64-debian-clang 

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/styler#497]
Most likely due to the charset changed from UTF-8 to ISO8859-15 and special characters printed with the cli packge, which does [not fail](https://cran.r-project.org/web/checks/check_results_cli.html) on the aforementioned flavor. 
Seems to appear in other repos also, e.g. [pillar](https://cran.r-project.org/web/checks/check_results_pillar.html) and was discussed on [r-devel](https://stat.ethz.ch/pipermail/r-package-devel/2019q2/003755.html), but I don't know which conclusions to draw from it. One potential fix is to skip tests on CRAN if the encoding is not UTF8, but this seems not an ideal solution. It was done [here](https://github.com/davidgohel/fpeek/commit/e45d74acad073b223ac36908461a962e01efdf68) for example.

This is how the output of styler looks in case things are going well: 
![Screen Shot 2019-04-25 at 22 57 39](https://user-images.githubusercontent.com/10477073/56768036-8a5f1100-67ad-11e9-8c9e-4e16f714f943.png)

I don't know how to fix this. We are required to submit a new version of styler to CRAN for other reasons, namely #490, until May 10, so I thought we could fix this as well until then (if we knew how). 

cc: @krlmlr, @gaborcsardi, @davidgohel.

**Comment by gaborcsardi** [comment]
cli does not output the UTF-8 characters if the locale is not UTF-8. So one fix is to call `cli::is_utf8_output()` and if `FALSE`, then you need to use the ASCII output in the expectation.

**Comment by lorenzwalthert** [comment]
Thanks for the prompt answer :-) I am not sure I fully understand. My usecase is
```r
cli::cat_bullet(bullet = "info")
```

So do think the best ways to handle this situation is to do something like

```r
if (cli::is_utf8_output()) {
  cli::cat_bullet(bullet = "info")
} else {
  cat("[info]") # or any other ASCII character that is *close* to the info bullet?
}

```

**Comment by gaborcsardi** [comment]
No, you only need to change the tests. cli automatically changes the output if there is no UTF-8 support. You just need to change the test strings you compare against.

**Comment by gaborcsardi** [comment]
```r
❯ cli::symbol$bullet
[1] "●"

❯ withr::with_options(list(cli.unicode = FALSE), cli::symbol$bullet)
[1] "*"
```

**Comment by lorenzwalthert** [comment]
Ok, now with the example I think I get it: I just make sure the reference value in the test is depending on whether or not UTF-8 is available, right?

**Comment by gaborcsardi** [comment]
Right.

**Comment by lorenzwalthert** [comment]
I appreciate your help Gabor. Thanks.

**Comment by gaborcsardi** [comment]
NP. Note that you can test this on R-hub before you submit.
```r
❯ rhub::platforms()
debian-clang-devel:
  Debian Linux, R-devel, clang, ISO-8859-15 locale.
...
```

**Comment by lorenzwalthert** [comment]
Yes I saw that on twitter. Will definitively make use of it 👍 .
