### ISSUE TITLE
Escaping string characters in roxygen @examples

### ISSUE THREAD

**Issue by rorynolan** [r-lib/styler#505]
Hi there,
The following file doesn't make it through `styler`. It throws a warning message:
`When processing r.R: '\.' is an unrecognized escape in character string starting ""\." `

```
#' Function.
#'
#' Details.
#'
#' @param x Only argument.
#'
#' @examples
#' \dontrun{
#' funfunfun("\\.txt$")
#' }
#' @export
funfunfun <- function(x) {
  invisible(x)
}
```

Is this a bug, or am I missing something?

Thanks, love styler,
Rory

**Comment by lorenzwalthert** [comment]
Sorry for the late reply. I looked into it for some time but the final fix was easy. See #512.

**Comment by rorynolan** [comment]
Thank you! Pretty quick response in my experience.
