### ISSUE TITLE
Cancelling new addin causes crash

### ISSUE THREAD

**Issue by oliverbeagley** [r-lib/styler#510]
The new addin does not exit properly when cancel is pressed.

Then console lines switch to starting with `?`, pressing enter does nothing and typing any garbage in causes the session to crash.

Using `esc` to exit this state works though

Session info if required:

```r
sessionInfo()
#> R version 3.6.0 (2019-04-26)
#> Platform: x86_64-apple-darwin18.5.0 (64-bit)
#> Running under: macOS Mojave 10.14.4
#> 
#> Matrix products: default
#> BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
#> LAPACK: /usr/local/Cellar/openblas/0.3.6_1/lib/libopenblasp-r0.3.6.dylib
#> 
#> locale:
#> [1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods  
#> [7] base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] compiler_3.6.0  backports_1.1.4 magrittr_1.5   
#>  [4] tools_3.6.0     pillar_1.3.1    rstudioapi_0.10
#>  [7] tibble_2.1.1    crayon_1.3.4    styler_1.1.1   
#> [10] pkgconfig_2.0.2 rlang_0.3.4     purrr_0.3.2    
```

Screenshots of the problem:

<img width="931" alt="Screenshot 2019-05-09 at 10 54 51" src="https://user-images.githubusercontent.com/50335017/57445140-9afd9580-7249-11e9-8812-a2cce80c589e.png">
<img width="932" alt="Screenshot 2019-05-09 at 10 55 01" src="https://user-images.githubusercontent.com/50335017/57445141-9afd9580-7249-11e9-9aa2-dfa2efc89f90.png">
<img width="930" alt="Screenshot 2019-05-09 at 10 55 08" src="https://user-images.githubusercontent.com/50335017/57445143-9afd9580-7249-11e9-9be0-e54713db7035.png">
<img width="931" alt="Screenshot 2019-05-09 at 10 55 23" src="https://user-images.githubusercontent.com/50335017/57445144-9b962c00-7249-11e9-9689-25af95e8f41a.png">
<img width="929" alt="Screenshot 2019-05-09 at 10 56 58" src="https://user-images.githubusercontent.com/50335017/57445145-9b962c00-7249-11e9-89af-951b01e8576a.png">

**Comment by lorenzwalthert** [comment]
Thanks for reporting @oliverbeagley. I noted that during testing, but I thought it was a problem related to `rstudioapi` and I thought it will be fairly rare, so I did not look into it further. However, I was wrong. We can handle the exit properly in styler. Surprising that the ill-behaved state occurs only within `with_handlers`, and not before.

```r
with_handlers({
      transformers <- eval(parse(text = new_style))
      style_text(c("a = 2", "function() {", "NULL", "}"))
    },
    error = function(e) {
      abort(paste0(
        "The selected style transformers \"",
        new_style, "\" is not valid: ", e$message
      ))
    }
    )
```

I have not experienced a crash of R tough. Just errors. Anyways, it should be fixe with #511. Do you want to test it?

**Comment by oliverbeagley** [comment]
Yeah, thats fixed it on my end as well now.

For me it didn't crash the first few times, only when I restarted RStudio, then I couldn't get it to not crash.

**Comment by lorenzwalthert** [comment]
Ok, thanks. I'll close that then.
