### ISSUE TITLE
Consider using {pkgfiles}

### ISSUE THREAD

**Issue by krlmlr** [r-lib/styler#515]
The job of the [pkgfiles](https://github.com/krlmlr/pkgfiles) package is to classify files in an R project according to their use. It helps distinguishing R scripts and Rmd files from other files. Using it would relieve {styler} from the responsibility to enumerate and filter files.

Most useful after https://github.com/krlmlr/pkgfiles/issues/1 is implemented.

Needs some mulling over.

**Comment by lorenzwalthert** [comment]
I see. However, I am not sure why enumerating and filtering files should be off-loaded to another package that extends the dependency graph. It's just a few lines of code to list all files in a directory and then doing a regex to filter out `.R` files for example.

**Comment by krlmlr** [comment]
[It depends](https://github.com/jimhester/itdepends).

{pkgfiles} could be made smart about finding files in nonstandard locations and double-checking the file contents. Currently there's not much added value, but it might improve.

Another way to achieve collaboration here would be to make sure that calling e.g. `styler::style_file()` from {pkgfiles} is a smooth experience, especially regarding the output.

**Comment by lorenzwalthert** [comment]
> Currently there's not much added value, but it might improve.

Then I suggest to re-open this issue when this is the case. For me, the current implementation satisfies all requirements. 

If you want to call {styler} from {pkgfiles}, I am happy to discuss.
