### ISSUE TITLE
styler in Emacs via reformatter

### ISSUE THREAD

**Issue by Emiller88** [r-lib/styler#517]
Just an FYI, I've written a small snippet to use styler in Emacs. 

Issue about it in `reformatter.el`
https://github.com/purcell/reformatter.el/issues/11#issuecomment-495459306
`snippet`
https://github.com/Emiller88/doom-emacs-private/blob/6aedee9bb7a5624f1dd63fcd5b6534aad400101a/config.org#reformatter

If you're reading this and you're not a Doom emacs user, `def-package!` is just a very thin wrapper around `use-package`

**Comment by lorenzwalthert** [comment]
Cool. Interested in making a PR to add a reference to the README (Rmd and knit to md) about how to use it (like the one for ale for VIM)?

**Comment by Emiller88** [comment]
Sounds good!

**Comment by lorenzwalthert** [comment]
Still interested? You can also post it here and I'll add it. Just don't know anything about Emacs so I think I can't write it myself.

**Comment by Emiller88** [comment]
Yes, I was just saving this for Hacktoberfest :stuck_out_tongue:

**Comment by lorenzwalthert** [comment]
Perfect.

**Comment by Emiller88** [comment]
To summarize this issue:
In `init.el` or where ever you load your config from
```elisp
(use-package reformatter
  :config
  (defconst Rscript-command "Rscript")
  (reformatter-define styler
    :program Rscript-command
    :args (list "--vanilla" "-e" "con <- file(\"stdin\")
out <- styler::style_text(readLines(con))
close(con)
out")
    :lighter " styler"))
```
In `.dir-locals.el` of your project:
```elisp
((ess-r-mode
  (mode . styler-on-save)))
```
