### ISSUE TITLE
style guide for code chunk comments in R Markdown 

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/styler#518]
I used `styler` addins `style active file` option on an `.Rmd` file which formatted the following code chunk comments:

![image](https://user-images.githubusercontent.com/11330453/59197572-9e917e80-8b5f-11e9-9d30-d55e06046a38.png)

to the following style:

![image](https://user-images.githubusercontent.com/11330453/59197729-fd56f800-8b5f-11e9-84bf-bb126990647d.png)

Just wanted to check with you if this is intended behavior according to the `tidyverse` style guide or an unintended side-effect? 

I find the former formatting to be much legible than the latter, but not sure what the style guide has to say here.

**Comment by lorenzwalthert** [comment]
I am not sure I understand. If you refer to the styling regarding the spacing before `#`, I can say that we are working on this, see #258. You can always use `strict = FALSE`, which does not touch spaces if they are *at least* one around certain operators and comments:

``` r
styler::style_text("x   <- 1+ 1\nxyz <- 2", strict = FALSE)
#> x   <- 1 + 1
#> xyz <- 2
```

<sup>Created on 2019-06-10 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by IndrajeetPatil** [comment]
Yes, the spacing before `#` is what I was referring to! 
Good to see this is something that you are already working on. I will close this issue in favor of #258 then.
