### ISSUE TITLE
Extra reindentation for pipe calls when using variable asssigment

### ISSUE THREAD

**Issue by reddy-ia** [r-lib/styler#527]
Can we transform this:
![image](https://user-images.githubusercontent.com/52095862/60316687-48a73e00-9989-11e9-8577-50a0729755bf.png)

into this:
![image](https://user-images.githubusercontent.com/52095862/60316706-58bf1d80-9989-11e9-93e9-1491ba4d9e0f.png)

<br>
<br>

Similarly for functions:
from this 
![image](https://user-images.githubusercontent.com/52095862/60316818-ccf9c100-9989-11e9-8bce-7f63d7769c1e.png)
into this
![image](https://user-images.githubusercontent.com/52095862/60316826-ddaa3700-9989-11e9-8ce7-a115778de551.png)

**Comment by lorenzwalthert** [comment]
We probably could. But note that styler implements the [tidyverse style](https://style.tidyverse.org/) guide, which is not compatible with your suggestions. However, you can implement your own style guide. You find resources in the relevant [README](https://github.com/r-lib/styler#further-resources).

**Comment by lorenzwalthert** [comment]
Note that you can set the level of indention with the argument `indent_by` in `styler::tidyverse_style()`, which should turn 
```r
function() {
  x
}
```

into 
```r
function() {
    x
}
```

when you set `indent_by = 4` (defaults to 2).
