### ISSUE TITLE
Force "<-" alignment

### ISSUE THREAD

**Issue by Banana1530** [r-lib/styler#529]
Hi, align assignments seems a pretty natural desire but I haven't found how to set it so far. If such functionality exists, it would be great if someone could point it out. Thank you!

What I want is 

before styling
```R
a <- 1
aa <- 1
aaaa <- 1
```

after styling
```R
a    <- 1
aa   <- 1
aaaa <- 1
```

**Comment by lorenzwalthert** [comment]
It's not currently possible to 

* keep alignment if it is already there.
* force alignment if it is not there.

I doubt we'll ever support the second (which is the example you gave above), but there are efforts to keep the alignment if it is there already in the first place. Check #258. I think we can close this in favor of this issue.
