### ISSUE TITLE
Doesn't handle curly-curly syntax well

### ISSUE THREAD

**Issue by Moohan** [r-lib/styler#534]
I have some code which uses the new [Rlang curly curly syntax](https://www.tidyverse.org/articles/2019/06/rlang-0-4-0/) 

```
if (drop) {
    data <- data %>%
      dplyr::select(-{{drop_var}})
  }
```

styler will split out all the curly braces

```
if (drop) {
  data <- data %>%
    dplyr::select(-{
      {
        chi_var
      }
    })
}
```

**Comment by lorenzwalthert** [comment]
Can you provide session information? Curly-curly syntax was only added in #528 and not yet on CRAN. Running your example with the devel version from GitHub, I get the desired result:
``` r
styler::style_text("if (drop) {
  data <- data %>%
    dplyr::select(-{{ drop_var }})
}")
#> if (drop) {
#>   data <- data %>%
#>     dplyr::select(-{{ drop_var }})
#> }
```

<sup>Created on 2019-07-23 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by Moohan** [comment]
That's the issue then! I'm running styler 1.1.1 from CRAN but if I get the dev version it seems to style as expected.
