### ISSUE TITLE
Function arguments within R6 classes misaligned

### ISSUE THREAD

**Issue by michaelquinn32** [r-lib/styler#541]
Correctly formatted R6 classes have misaligned function arguments after applying styler.

``` r
styler::style_text('
  MyClass <- R6::R6Class(
    "MyClass",
    public = list(initialize = function(my_arg,
                                        my_named_arg = 1) {
        return(invisible())
      }
    ),
  )
')
#> MyClass <- R6::R6Class(
#>   "MyClass",
#>   public = list(initialize = function(my_arg,
#>                                         my_named_arg = 1) {
#>     return(invisible())
#>   }),
#> )
```

This seems related to #254 and #258, but it seems useful to explicitly track this separately.

**Comment by lorenzwalthert** [comment]
Thanks. I agree the other issues are (quite) different, so it's good to track this separately. I remember similar issues with function headers but can't find them now.

**Comment by lorenzwalthert** [comment]
One solution is to remove line breaks after `=` (`EQ_FORMALS`) in any case
```r
# before
function(x = 
    3, 
  v) NULL

# after
function(x = 3, v) NULL
``` 
This would simplify things quite a bit, although it's not the nicest solution.

**Comment by lorenzwalthert** [comment]
@michaelquinn32 I think I found a way to fix the bug. Do you want to test and see if it works in general? You can install this branch here: 
```r
remotes::install_github("lorenzwalthert/styler@no-linebreak-with-eq-formals")
```

**Comment by michaelquinn32** [comment]
That looks a lot better! Thank you!

**Comment by michaelquinn32** [comment]
This has an effect that relates to another issue in function signatures. I opened #549 to address those.

Thank you for the responsiveness and patience will all of these issues!
