### ISSUE TITLE
Enforce line break after + in ggplot2

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [r-lib/styler#544]
I'd love to see `styler::tidyverse_style()` enforce a line break after `+` in ggplot2 code, i.e.

```r
ggplot(data = mtcars, mapping = aes(x = mpg, y = vs)) + geom_point()
```

should be

```r
ggplot(data = mtcars, mapping = aes(x = mpg, y = vs)) + 
  geom_point()
```

Is this a feasible feature to implement?

**Comment by lorenzwalthert** [comment]
Can you point me to an existing rule in the tidyverse style guide that requires such a behavior? We generally only implement rules explicitly formulated there. Also, styler currently does not understand which namespace a token belongs to, i.e. it could not distinguish `+` from ggplot2 and the base `+`. Related issue: #247.

**Comment by lorenzwalthert** [comment]
One thing you could do is to adapt the tidyverse style guide and add line breaks after `+` when the token afterwards is a function call, which would avoid generating line breaks for simple arithmetic operations like `1 + 1`.

**Comment by mine-cetinkaya-rundel** [comment]
@lorenzwalthert As a reference, the advice around line breaks for ggplot2 are now in the style guide as well: https://style.tidyverse.org/ggplot2.html.

**Comment by lorenzwalthert** [comment]
I am a bit surprised to be honest that Hadley has accepted style advise that is so specific to a package in the style guide 😄. Anyways I think we might derive more general rules for arithmetic
operations that involve function call. For now, I implemented what you suggested. Can you have a look at the test files in #569 I added (called `ggplot2-in.R` for before and `ggplot2-out.R` for after) and tell me if these tests look reasonable? Also, I'd like you to install that version of styler with 
```r
remotes::install_github("r-lib/styler@569")
```
and style your files with it and tell me if the result is satisfying. Can you do that?

**Comment by vimal739** [comment]
Would love to see this feature added, easier to manage typing when using notebooks

**Comment by lorenzwalthert** [comment]
@vimal739 This feature is available in the latest CRAN release and any CRAN release after December 18, 2019.

**Comment by vimal739** [comment]
@lorenzwalthert Wow that's great, thanks much!
