### ISSUE TITLE
http:// images in README

### ISSUE THREAD

**Issue by krlmlr** [r-lib/styler#550]
give this:

![Screenshot from 2019-09-26 20-25-15](https://user-images.githubusercontent.com/1741643/65714620-c91a2f80-e09b-11e9-890f-f5849727a96f.png)

**Comment by lorenzwalthert** [comment]
Thanks.

**Comment by krlmlr** [comment]
Does `.travis.yml` need `cache: packages` ?

**Comment by lorenzwalthert** [comment]
I don't know. You can add it if you think it helps. I only noted that the travis builds are slower than the appveyor builds.
