### ISSUE TITLE
Styling Rmd notebooks causes cached chunk output to be lost

### ISSUE THREAD

**Issue by davidski** [r-lib/styler#565]
I've been adopting `styler` via pre-commit hooks to enforce `tidyverse_style()` for my repositories. When applied to Rmarkdown notebooks, a target modified by styler often causes all of the (in-line) cached chunk output to be lost. This is quite disruptive when trying to commit small elements of work in a single session.

A reprex is on RStudio Cloud at https://rstudio.cloud/project/753767. The `style_buster.Rmd` is a simple notebook that shows how this fails (or at least...fails how I want it to work 😉 ). 

 Any thoughts on how to work around this (or provide a better reprex) are greatly appreciated!

Thanks for all the work on this pacakge!

**Comment by lorenzwalthert** [comment]
Thanks. Actually I don't think this has to do with styler. If you manually edit the code, the same would happen. I think it has to do with the way knitr invalidates the cache. An option might be to open an issue in knitr and propose an alternative cache validation, e.g. one based on the hash from the parse table (without the token position, just token and text), not on the text directly. I can go into more details if you are interested. 
That said, I think there are good alternatives to making heavy use of the knitr cache, most notably, using a workflow manager like [drake](https://docs.ropensci.org/drake/). Not sure drake caches based on text for targets or on a parsed version of it, you'd have to try that to see if a target is rebuild when you add or remove spaces and line breaks.

PS: Were you using https://github.com/lorenzwalthert/precommit?

**Comment by davidski** [comment]
Thanks for the quick response! I feared this would be a knitr side issue. I'm pretty opaque on the knitr cache process (I have some other cache chunk issues that I've been struggling with in other contexts) and would love to hear the gory details if you have time to share them.

Drake is a super interesting project and one that I keep poking at around the edges. For my team's workflows (heavy EDA-style work via Rmarkdown notebooks), it hasn't quite worked out for us, but I keep looking to spent time to dive into drake and at least document out the rough spots. I'm still surprised this flow of small, frequent git commits when using cached chunks is so fragile. I must be using a rather unusual flow!

I am indeed using your precommit hooks! :smile: Thank you for that handy repository as well!

**Comment by lorenzwalthert** [comment]
I think it token change in your code, this won't work but spaces and newlines and comment changes are ignored by the following hash function: 

``` r
hash_code <- function(text) {
  # get a tabular representation of code
  parse_data <- getParseData(
    parse(text = text)
  )

  # just care about sequence and type of parsed data, not which line and 
  # column it sits on.
  parse_data <- parse_data[parse_data$token != "COMMENT",]
  rownames(parse_data) <- NULL
  digest::digest(parse_data[, c("token", "text", "terminal")])
}
# hence, the below is identical
hash_code("x <- 1")
#> [1] "243f19a4290020bc05e7f75bb8b1f679"
hash_code("x <-  1")
#> [1] "243f19a4290020bc05e7f75bb8b1f679"
hash_code("x <-  1 # comment")
#> [1] "243f19a4290020bc05e7f75bb8b1f679"


hash_code("dplyr::mutate(data, x = 3)")
#> [1] "0ff808c8870dc135bf904cafa4ed50ed"
hash_code("dplyr::mutate(data, x =3)")
#> [1] "0ff808c8870dc135bf904cafa4ed50ed"
hash_code("dplyr::mutate(data,x = 3)")
#> [1] "0ff808c8870dc135bf904cafa4ed50ed"
```

<sup>Created on 2019-12-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I think we could suggest to replace the hash function in knitr with something like this.

**Comment by lorenzwalthert** [comment]
I opened an issue in https://github.com/r-lib/styler/issues/565#issuecomment-561212430.
