### ISSUE TITLE
Keep empty line around comments

### ISSUE THREAD

**Issue by krlmlr** [r-lib/styler#632]
The empty line above the "defining b" comment should remain.

``` r
styler::style_text('
c(
  a = 1,
  
  # defining b
  b = 2
)
')
#> 
#> c(
#>   a = 1,
#>   # defining b
#>   b = 2
#> )
```

<sup>Created on 2020-04-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Follow-up to #630.

**Comment by lorenzwalthert** [comment]
It's now implemented for both blank lines above and below comments. Hope that works for you.
