### ISSUE TITLE
Add an option for suppressing all communication

### ISSUE THREAD

**Issue by michaelquinn32** [r-lib/styler#637]
Hi Lorenz!

We're using styler as a part of some tools that read from stdin and write to stdout. In that context it's very important that all messages are turned off, and that styler only output the styled code.

We've made some small modifications to the package to support this, and added an option for enabling and disabling the feature. Is this something that you would like added to the main package?

Thanks!

P.S. And if this came up before, apologies.

**Comment by lorenzwalthert** [comment]
Sure, I'd like to see that merged into upstream. Ther's already an issue for that: #375. We can discuss it further there if you like. Also note #634, a related API change not yet merged into master for dry-running styler.

**Comment by michaelquinn32** [comment]
The current implementation (which can change here of course), uses an option (styler.communicate)  and doesn't require an API change. It adds some conditional logic around the points of the code that produces messages, suppressing them when enabled.

**Comment by lorenzwalthert** [comment]
Ok. The advantage is probably that we don't have to pass the argument down to the innermost stacks that way. And I think usethis also has a `{packagename}.communicate` option, right? Then we should also use a subset or the same arguments this option has for consistency in r-lib/tidyverse probably.

**Comment by lorenzwalthert** [comment]
Closed with #640.
