### ISSUE TITLE
Ignore certain file types / directories in `style_file()`

### ISSUE THREAD

**Issue by pat-s** [r-lib/styler#656]
I would like {styler} to either

- ignore certain file types (in my case `.yml` files).
- certain directories (in my case `inst/`).

I know this exists in `style_pkg(exclude_dirs = )`. However, when invoking {styler} via {precommit}, `style_file()` is called which does not have this option.

This might be a bit tricky since `style_file` is explicitly called on a path by {precommit} and hence some preprocessing before calling it might need to happen?

**Comment by lorenzwalthert** [comment]
I don't think this is a styler problem, although #319 might be a related issue. If it's only about using pre-commit, use the `exclude:` key. You can find documentation and example here: https://lorenzwalthert.github.io/precommit/articles/available-hooks.html#spell-check

**Comment by pat-s** [comment]
Will setting a file type in `exclude` of the spell-check hook have an effect of what happens in the style-files hook? According to your link it might be as you do some copying but I cannot get it working.

I tried excluding all YAML files by adding `.*\.yml` to it and adding `exclude` to the style-files hook.
Still, my YAML files get styled.
What am I doing wrong?

Feel free to move the issue to {precommit} :)

**Comment by lorenzwalthert** [comment]
No you have to set the `exclude:` key in the styler hook. well `yml` or `yaml`? Like this:

```
# ...
    -   id: style-files
        exclude: >
            (?x)^(
                .*\.yaml
            )$

**Comment by pat-s** [comment]
Thanks. Still gets styled. And yes, it is `.yml`. 

Does it matter that the files lives in `inst/`?

**Comment by lorenzwalthert** [comment]
I don't get why you want to exclude them from the hook, they are not going to be changed anyways.

**Comment by pat-s** [comment]
> I don't get why you want to exclude them from the hook, they are not going to be changed anyways. What do you mean with gets styled? Not skipped from the pre-commit output during git commit?

The styler hook also styles `.yml` files for me. Not the ones listed in `.github` or `.travis.yml` but `.yml` files which live in `inst/`.
Specifically not the code gets styled, but superfluous blank lines.
However, in my case these are not superfluous but intended.
Or am I wrong and styler is not the hook responsible for this action?

**Comment by lorenzwalthert** [comment]
Are you sure it's the styler hook? I have the stong apprehension that it is in fact a hook like `https://github.com/lorenzwalthert/precommit/blob/master/.pre-commit-config.yaml#L45` or similar. Can you show the output of `git commit` that changes the file or maybe easier for you, the `.pre-commit-config.yaml` of the repo of concern?

**Comment by pat-s** [comment]
Ahh! I did not see this hook before.

Just tested it and indeed it is the `end-of-file-fixer` hook. 
Works fine if I exclude `.yml` there 🎉 

Sorry for the trouble! 
I was also confused why styler would touch .yml files 😅
