### ISSUE TITLE
Is there an format on save option

### ISSUE THREAD

**Issue by Kalaschnik** [r-lib/styler#658]
Is there any way (in RStudio) to setup to style the active document on Cmd+S / Ctrl+S?

**Comment by lorenzwalthert** [comment]
Hi @Kalaschnik, there is not, but there is https://github.com/rstudio/rstudio/issues/2563, so maybe upvote this to indicate your support or ask for the status of this. I recommend using https://github.com/lorenzwalthert/precommit for git repos.
