### ISSUE TITLE
Is cache size zero fine?

### ISSUE THREAD

**Issue by seed-of-apricot** [r-lib/styler#668]
I have activated R.cache but am not sure if this is working under my environment, seeing that the cache size is zero.

```r
> styler::cache_info()
Size:           0 bytes (421 cached expressions)
Last modified:  2020-09-17 21:19:08
Created:        2020-09-14 20:30:38
Location:       C:\Users\apricot\AppData\Local\R\R.cache/styler/1.3.2
Activated:      TRUE
```

The path seems slightly wrong (confusion between / and \) so does it possibly fail to find the cache path to writing the expressions?

**Comment by lorenzwalthert** [comment]
From the [docs](https://styler.r-lib.org/reference/cache_info.html): 
```
Note that the size consumed by the cache will always be displayed as zero because all the cache does is creating an empty file of size 0 bytes for every cached expression. The innode is excluded from this displayed size but negligible.
```

**Comment by lorenzwalthert** [comment]
I think we should probably turn the backslashes into forward slashes in `Location:`. I believe everything works fine in your case because you have some cached expressions.

**Comment by seed-of-apricot** [comment]
Understood, thank you! I see some files by hitting the command you have provided.
It's better for Windows users if you can fix the confusion.

**Comment by lorenzwalthert** [comment]
Cool. I am not a windows user. How do you make sure \ becomes / with base R? Can you post a reprex or make a PR for that?

**Comment by lorenzwalthert** [comment]
You'd have to normalize here: https://github.com/r-lib/styler/blob/ebbf3c10456e544c648adf6a6566bae2fc269b1a/R/utils-cache.R#L107
