### ISSUE TITLE
make use of new selection-based API in next release of rstudioapi?

### ISSUE THREAD

**Issue by kevinushey** [r-lib/styler#669]
The next version of RStudio will come with support for a visual editing mode, as described in https://rstudio.github.io/visual-markdown-editing/#/. Unfortunately, many of the pre-existing `rstudioapi` APIs are not compatible with visual editing mode, since they assume a line-based editor, where cursor positions can be referenced globally via [row, column] offsets. The new visual editor is cell-based and so does not map to the same abstraction as well.

To help alleviate this, we are introducing a few new APIs that addin authors can use to ensure their addins function both in visual and source mode. Would you be receptive to a PR making that possible?

**Comment by lorenzwalthert** [comment]
Sure, if you can make a PR that would be great.

**Comment by kevinushey** [comment]
No longer needed; the APIs used by `styler` should "just work" in visual mode with the latest daily builds of RStudio (v1.4.890+).

**Comment by lorenzwalthert** [comment]
@kevinushey it seems the styler addin does not work well with the visual mode as reported in #740. Can you have a look? Are we missing a minimal version requirement for `{rstudioapi}` or something like that?

**Comment by kevinushey** [comment]
Can you please file a separate issue that makes the actual problem more clear? Particularly, that switching from Visual mode to Source mode seems to mangle the editor undo stack in some cases (with a reproducible example)?

**Comment by jthomasmock** [comment]
Hi @kevinushey I originally opened the issue in `{styler}`, and have moved it to here at Lorenz' request.

https://github.com/r-lib/styler/issues/740#issue-817976625

I have copied the bulk of that post below. I can reproduce interactively, and have included a GIF of the behavior.

---

Problem: In Visual Markdown mode, styling the active selection in a code-chunk appears to correctly style the code, but malforms it on the plain-text side.

Switching back into plain-text mode, the code will be "fixed", but if you "undo" you can see there is an intermediate format that is completely malformed and has lost some characters. Undo a second time will revert back to the original, unstyled format.

Reprex below, and note this works fine in non-visual editor mode.

````
---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```



Use the `styler` package to "style" the code, intentionally awkwardly formatted and of sufficient length as an example.

```{r}
mpg %>%     filter(cyl   %in%c(4 , 6,     8))%>%slice_sample(n=30) %>% mutate(hwy_mpl = hwy/2.352)
```
````

Environment:
```
R version 4.0.1 (2020-06-06)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

## Packages of interest
styler V: 1.3.2
rstudioapi V: 0.13

$mode
[1] "desktop"

$version
[1] ‘1.4.1103’

$release_name
[1] "Wax Begonia"
```
Quick recording 
![Reprex-recording](https://user-images.githubusercontent.com/29187501/109394853-cb1a9a80-78ee-11eb-8c13-d1b0841c85e1.gif)

**Comment by lorenzwalthert** [comment]
@jthomasmock thanks. I think Kevin meant to post this in https://github.com/rstudio/rstudio, you are still in https://github.com/r-lib/styler.
