### ISSUE TITLE
Broken Heading in pgkdown site

### ISSUE THREAD

**Issue by assignUser** [r-lib/styler#671]
Something went wrong [here](https://styler.r-lib.org/articles/customizing_styler.html#levelname-1-root-token-short_text-lag_newlinesspaces-id-2):
![image](https://user-images.githubusercontent.com/16141871/93651337-7276d580-fa11-11ea-9829-a27ddc6200cf.png)

**Comment by lorenzwalthert** [comment]
Correct, thanks. Using `git blame`, I can see this was introduced with da1a78af10b16103e96c74ad53cf5bf1eeaf7d23. Should be fixed in #672.
