### ISSUE TITLE
Problems with unary operator +

### ISSUE THREAD

**Issue by davidchall** [r-lib/styler#696]
I've encountered errors when using the `+` unary operator under certain conditions. Here's a reprex:

``` r
library(styler)

style_text("+x")
#> +x
style_text("-sin(x)")
#> -sin(x)
style_text("+sin(x)")
#> Error in pd$child[[previous_non_comment(pd, first_plus)]]: attempt to select less than one element in get1index
```

<sup>Created on 2020-11-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lorenzwalthert** [comment]
Thanks @davidchal. Should be fixed now.
