### ISSUE TITLE
FR: Keep data.table chaining

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/styler#720]
It is pretty canonical in `data.table` to write "query chains" like

```
DT[ , sum(x), by = .(a, b)
   ][ , median(V1), by = a]
```

But `styler` doesn't like these:

```
writeLines("
DT[ , sum(x), by = .(a, b)
   ][ , median(V1), by = a]
", tmp <- tempfile(fileext = ".R"))
styler::style_file(tmp)

writeLines(readLines(tmp))
# DT[, sum(x), by = .(a, b)][, median(V1), by = a]
```

Would a rule to allow such chaining be in scope for `styler`?

**Comment by lorenzwalthert** [comment]
I indeed consider this to be out of scope for styler, as we currently only support the tidyverse style guide and I don't see this formatting compatible with it. However, you could do something like this to create your own style guide.

```r
data_table_style <- function(...) {
  sg <-tidyverse_style(...)
  new_set_line_break_before_closing_call <- function(pd, except_token_before = "COMMENT") {
    if (!is_function_call(pd) && !is_subset_expr(pd)) {
      return(pd)
    }
    npd <- nrow(pd)
    
    #<- this line changed: if token after closing is [ and there is any line break
    # assume it is multiline. in tidyverse_style(), we move the closing brace up
    is_multi_line <- any(pd$lag_newlines[seq2(3L, npd)] > 0) && last(pd$token_after) == "'['" 
    if (!is_multi_line) {
      exception <- which(pd$token_before %in% except_token_before)
      pd$lag_newlines[setdiff(npd, exception)] <- 0L
      return(pd)
    }
    pd$lag_newlines[npd] <- 1L
    pd
  }
  
  sg$line_break$set_line_break_before_closing_call <- new_set_line_break_before_closing_call
  # adapt this for the cache
  sg$style_guide_name <- "styler::tidyverse_style@https://github.com/r-lib"
  sg$style_guide_version <- '1.3.2.9000' # use your pkg version here
  sg
}

style_text('DT[ , sum(x), by = .(a, b)
   ][ , median(V1), by = a]', style = data_table_style)
#> DT[, sum(x), by = .(a, b)
#> ][, median(V1), by = a] 
```
The people from mlr(3) also have their own style guide documented here: https://github.com/mlr-org/mlr3/wiki/Style-Guide. Although I'd probably prefer now the name of the fork package not to be styler (so you can have two installations), but rather something like styler.mlr. I can assist you if you want to do something similar for data.table, but I think it's better to not clone all of styler for that, just make a very slick package with the code above and maybe add some unit tests (best case: all styler unit tests and adapt to the rules you change).

In addition, there is some (outdated) discussion of other style guides elsewhere, in particular in this comment: https://github.com/r-lib/styler/issues/340#issuecomment-593662092

**Comment by wagathu** [comment]
When running the above code, I get:

Error in is_subset_expr(pd) : could not find function "is_subset_expr"
