### ISSUE TITLE
Single-line pipes?

### ISSUE THREAD

**Issue by krlmlr** [r-lib/styler#74]
https://github.com/tidyverse/style/pull/28

**Comment by lorenzwalthert** [comment]
Reference ([#118](https://github.com/krlmlr/tidyr/pull/1/files#diff-37e1612efe8169526e62b2353acece14R93)).

**Comment by krlmlr** [comment]
``` r
styler::style_text("a %>% b()")
#> a %>%
#>   b()
```

The style guide PR has been merged now.

**Comment by lorenzwalthert** [comment]
So does that mean we do not add line breaks after pipes at all anymore?

**Comment by krlmlr** [comment]
Not if they fit on a single line. Looking into it right now.

**Comment by krlmlr** [comment]
Closed in 9e847afa.

**Comment by harrismcgehee** [comment]
How is "if they fit on a single line" defined? Is there a way to turn off single line pipes?

**Comment by lorenzwalthert** [comment]
If I am not mistaken there is currently no option to force a line break after `%>%`. @krlmlr maybe we should force it for `strict = TRUE`? Or is that option already overloaded? We could add another option to give granular control. 
Related #65.

**Comment by krlmlr** [comment]
They fit on a single line if they don't contain a line break. We currently don't care about line length, but when we have this, we should also break overly long pipes. Not sure if we should turn this on with `strict = TRUE` or define a new option.

**Comment by krlmlr** [comment]
For a one-time transformation, you could do `sed -r -i 's/([>]%[>])/\1\n    /g' R/*` and then apply *styler* (the `-i` option must be `-ibak` on OS X).

**Comment by lorenzwalthert** [comment]
Let's revisit that once we have implemented #247.
