### ISSUE TITLE
Styler malforms style in Visual Markdown mode

### ISSUE THREAD

**Issue by jthomasmock** [r-lib/styler#740]
Problem: In Visual Markdown mode, styling the active selection in a code-chunk appears to correctly style the code, but malforms it on the plain-text side.

Switching back into plain-text mode, the code will be "fixed", but if you "undo" you can see there is an intermediate format that is completely malformed and has lost some characters. Undo a second time will revert back to the original, unstyled format.

Reprex below, and note this works fine in non-visual editor mode.

````
---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```



Use the `styler` package to "style" the code, intentionally awkwardly formatted and of sufficient length as an example.

```{r}
mpg %>%     filter(cyl   %in%c(4 , 6,     8))%>%slice_sample(n=30) %>% mutate(hwy_mpl = hwy/2.352)
```
````

Environment:
```
R version 4.0.1 (2020-06-06)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

## Packages of interest
styler V: 1.3.2
rstudioapi V: 0.13

$mode
[1] "desktop"

$version
[1] ‘1.4.1103’

$release_name
[1] "Wax Begonia"
```

I realize this may be an RStudio issue rather than `styler` proper, and can crosspost if necessary.

Quick recording 
![Reprex-recording](https://user-images.githubusercontent.com/29187501/109394853-cb1a9a80-78ee-11eb-8c13-d1b0841c85e1.gif)

**Comment by lorenzwalthert** [comment]
Thanks for raising this. A similar issue was already discussed in https://github.com/r-lib/styler/issues/669 but then they thought no adaptions were required form our side to make styler work with the visual mode. I'll ping Kevin there and hope he can help.

**Comment by jthomasmock** [comment]
Thanks! I'm using `rstudio::api` v 0.13, and have edited the initial comment to also include that.

**Comment by kevinushey** [comment]
I think this can be closed since it's unlikely to be an issue in `styler`.

**Comment by lorenzwalthert** [comment]
@jthomasmock could you follow Kevins advice form https://github.com/r-lib/styler/issues/669#issuecomment-791621729 and file an issue in rstudio?

**Comment by jthomasmock** [comment]
Yup, make sense, thank you!
