### ISSUE TITLE
newlines in function calls

### ISSUE THREAD

**Issue by jamespeapen** [r-lib/styler#750]
styler removes the vertical alignment in function parameters:
```r
# before
write.table(data,
            "file.txt",
            sep="\t", 
            row.names=F,
            quote=F)


# after
write.table(data,
  "file.txt",
  sep = "\t", 
  row.names = F,
  quote = F
)
```

Is there a way to keep the vertical alignment or, if the indentation is reduced, to add a newline after the opening parenthesis:

```r
write.table(
  data,
  "file.txt",
  sep = "\t", 
  row.names = F, 
  quote = F
)
```
Thanks!

**Comment by lorenzwalthert** [comment]
This is expected. Your `# before` Is not compliant with the tidyverse style guide. And the like is not broken before the first argument because it’s not named. Please see section 2.5 in https://style.tidyverse.org/syntax.html#long-lines
