### ISSUE TITLE
Inconsistent behavior of base_indention

### ISSUE THREAD

**Issue by renkun-ken** [r-lib/styler#763]
Currently, `c("expr", "0")` is used in languageserver to preserve the indention of the cursor for on-type-formatting. We are trying to adopt the newly added `base_indention` in styler 1.4.0 instead of hacking into the stylers (https://github.com/REditorSupport/languageserver/issues/400). However, `base_indention` may produce inconsistent output:

```
> styler::style_text("x+1", base_indention = 2)                                                                                                    
  x + 1

> styler::style_text("x+1\n0", base_indention = 2)                                                                                                 
  x + 1
  0

> styler::style_text(c("x+1", "0"), base_indention = 2)                                                                                            
  x + 1
0

> styler::style_text(c("x+1", "x+2"), base_indention = 2)                                                                                          
  x + 1
  x + 2

> styler::style_text(c("x+1", "f"), base_indention = 2)                                                                                            
  x + 1
  f

> styler::style_text(c("x+1", "1"), base_indention = 2)                                                                                            
  x + 1
  1

> styler::style_text(c("  x+1", "1"), base_indention = 2)                                                                                          
  x + 1
1

> styler::style_text(c("  x+1\n1"), base_indention = 2)                                                                                            
  x + 1
1
```

**Comment by lorenzwalthert** [comment]
Thanks @renkun-ken. The problem seems a cache interaction. Expressions are (to my surprise) cached with their trailing spaces removed. This works only if we add the trailing spaces in the right place, which we don't currently. The problem only occurs if parts of your code are cached. When the whole text input cache can be used, this problem does not manifest.

**Comment by lorenzwalthert** [comment]
@renkun-ken can you try out #764? I ran your code and I think it does what it should. Please confirm.

**Comment by lorenzwalthert** [comment]
Also note similar problems were discussed in https://github.com/r-lib/styler/issues/641.

**Comment by renkun-ken** [comment]
@lorenzwalthert #764 works nicely, and we could use it now, thanks!

**Comment by lorenzwalthert** [comment]
This also affects the Addin. We'll do a bug-fix release soon.
