### ISSUE TITLE
Malformed file on nested code chunks

### ISSUE THREAD

**Issue by RoyalTS** [r-lib/styler#787]
I'm getting `Error: Malformed file!` when I try to run `styler` on @yihui's [template](
https://github.com/yihui/xaringan/blob/master/inst/rmarkdown/templates/xaringan/skeleton/skeleton.Rmd) for [xaringan](https://github.com/yihui/xaringan) presentations. As far as I can see that file is in no way malformed. In fact, it compiles just fine. Might the nested code blocks in the template be tripping up `styler`?

**Comment by lorenzwalthert** [comment]
Thanks. We can narrow the problemd down to this (raw) code being problematic


````md
`r ''````{r, highlight.output=c(1, 3)}
head(iris)
```
````
