### ISSUE TITLE
FR: fix up "dangling else"

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/styler#792]
`styler` doesn't fix up the following but I think it should:

```
foo <- function(x) {
  if (TRUE) {
    1
  }
  else {
    2
  }
}
```

(specifically, remove the newline to make line 4 `  } else {`)

It's not _strictly_ written in the section on conditionals but it seems implied to me: https://style.tidyverse.org/syntax.html#control-flow

**Comment by lorenzwalthert** [comment]
I agree.

**Comment by MichaelChirico** [comment]
In case it's any help, here's an xpath for detecting the issue on the `xmlparsetree` version of the `getParseData` tree:

```
previous_curly_path <-
  "preceding-sibling::IF/following-sibling::expr[2]/OP-RIGHT-BRACE"
# need to (?) repeat previous_curly_path since != will return true if there is
#   no such node. ditto for approach with not(@line1 = ...).
bad_expr_xpath <- sprintf(
  "//ELSE[%1$s and @line1 != %1$s/@line2]",
  previous_curly_path
)
```
