### ISSUE TITLE
feature request: new argument for `tidyverse_style()` to control assignment line

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/styler#795]
The `tidyverse` style guide outlines the following three acceptable forms of assignment:

<img width="600" alt="Screenshot 2021-05-06 at 10 04 55" src="https://user-images.githubusercontent.com/11330453/117264880-f623ec00-ae53-11eb-8be3-0276b4209077.png">

I was wondering if you would consider introducing a new argument (maybe called `assignment_line`) for `tidyverse_style()` function that can let the user choose from the first two available options (so possible values this argument can take: `"separate"` (default), `"same"`). This will make it easy to switch between the first two assignment styles if one changes their mind.

What do you think?

# Current behavior

``` r
styler::style_text("
iris_long <-
  iris %>%
  gather(measure, value, -Species)
")
#> 
#> iris_long <-
#>   iris %>%
#>   gather(measure, value, -Species)
```

<sup>Created on 2021-05-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

# Expected behavior 

- `assignment_line = "separate"` (backward compatible default)

``` r
styler::style_text("
iris_long <-
  iris %>%
  gather(measure, value, -Species)
", transformers = tidyverse_style(assignment_line = "separate"))
#> 
#> iris_long <-
#>   iris %>%
#>   gather(measure, value, -Species)
```

- `assignment_line = "same"`

``` r
styler::style_text("
iris_long <-
  iris %>%
  gather(measure, value, -Species)
", transformers = tidyverse_style(assignment_line = "same"))
#> 
#> iris_long <- iris %>%
#>   gather(measure, value, -Species)
```

**Comment by lorenzwalthert** [comment]
I am not sure this should be governed globally. I think it would make Ames to assume it tension along formatting by the user here and stick to the non-invasive paradigm of style there. In that case, it would be sufficient to leave the code as is in the two cases outlined in the tidyverse style guide....

**Comment by IndrajeetPatil** [comment]
Sure, I agree that, in the non-invasive paradigm of styling here, the default behavior can continue to be what it has thus far been: to leave the code as is in the two cases outlined.

But I was wondering if you would be willing to support a way for users to switch between these two options if they so wish to. This ensures that this global styling change would affect code _only when the user is expecting it_.

**Comment by IndrajeetPatil** [comment]
Also, although not in the pipe context, the above feature might also be helpful to change the following

``` r
styler::style_text("
                   x <-
    mean(mtcars$wt)
                   ")
#> 
#> x <-
#>   mean(mtcars$wt)
```

<sup>Created on 2021-05-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

into

``` r
styler::style_text("
                   x <-
    mean(mtcars$wt)
                   ")
#> 
#> x <- mean(mtcars$wt)
```

<sup>Created on 2021-05-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by lorenzwalthert** [comment]
Maybe I'll revisit this in the future but there are many other open issues that I want to prioritise, so let's postpone it for now.
