### ISSUE TITLE
Unwrapping multiple assignments -- intended change?

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/styler#808]
Some time between v1.3.2 and v1.4.0, `styler` started inlining multiple assignments:

```
# @ v1.3.2
tmp <- tempfile(fileext = '.R')
writeLines('a <-
  b <- 2', tmp)
styler::style_file(tmp)
system(paste('cat', tmp))
# a <-
#   b <- 2
```

```
# @ v1.4.0
tmp <- tempfile(fileext = '.R')
writeLines('a <-
  b <- 2', tmp)
styler::style_file(tmp)
system(paste('cat', tmp))
# a <- b <- 2
```

Is this change intended?

I don't see anything about it in the [release notes](https://github.com/r-lib/styler/releases); only this looks related:

> empty lines are now removed between pipes and assignments (#645, #710).

This behavior is also not described in the tidyverse guide, as near as I can tell.

My attempt to `git bisect` when the change showed up was not successful 😄

**Comment by lorenzwalthert** [comment]
Thanks @MichaelChirico. Indeed, this behaviour was not intended and an unintended side effect of the bullet you mention from the release note. If you are interested, you can make a PR to fix it (looking at the diff in #645 and #710), otherwise I might look into it at some point, but it does not have very high priority for me.

**Comment by MichaelChirico** [comment]
Thanks. Perhaps worth noting that I discovered the behavior because `styler` can now create very wide lines as a result, e.g. if we have

```
ImportantDataFrame$ImportantColumn1 <-
  ImportantDataFrame$ImportantColumn2 <-
  ComplicatedFunction(ImportantDataFrame$InputColumn)
```

`styler_file` will now create the huge line:

```
ImportantDataFrame$ImportantColumn1 <- ImportantDataFrame$ImportantColumn2 <- ComplicatedFunction(ImportantDataFrame$InputColumn)
```

This makes it more concerning than the minimal example in the issue body IMO

**Comment by lorenzwalthert** [comment]
I only partly agree because if there are line breaks, all the way through, styler does not seem to drop them:


``` r
styler::style_text('ImportantDataFrame$ImportantColumn1 <-
  ImportantDataFrame$ImportantColumn2 <-
  ComplicatedFunction(ImportantDataFrame$InputColumn)')
#> ImportantDataFrame$ImportantColumn1 <-
#>   ImportantDataFrame$ImportantColumn2 <-
#>   ComplicatedFunction(ImportantDataFrame$InputColumn)
```

<sup>Created on 2021-06-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by lorenzwalthert** [comment]
Apparently, `min` -> `pmin()` is the change we need. Filed a PR anyways xD
