### ISSUE TITLE
Code within pipelines get broken

### ISSUE THREAD

**Issue by laresbernardo** [r-lib/styler#815]
Hi! I've recently discovered this package and tried it on my [lares](https://github.com/laresbernardo/lares) package but it actually broke some codes when running `styler::style_file()`. Specifically, when `%>% {code} %>%` was used. For example:
```
data.frame(a = 1, b = 2) %>%
  {if (length(1) > 1) {
    mutate(., c = "c")
  } else {
    .
  }}
```
Using updated styler CRAN version 1.4.1 on 
```
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS  11.4
```

**Comment by lorenzwalthert** [comment]
Thanks for reaching out
This is what I get: 


``` r
code <- 'data.frame(a = 1, b = 2) %>%
  {if (length(1) > 1) {
    mutate(., c = "c")
  } else {
    .
  }}'

out <- styler::style_text(code)
waldo::compare(
  as.character(out),
  unlist(strsplit(code, "\n", fixed = TRUE))
)
#>     old                              | new                               
#> [1] "data.frame(a = 1, b = 2) %>% {" - "data.frame(a = 1, b = 2) %>%" [1]
#> [2] "  if (length(1) > 1) {"         - "  {if (length(1) > 1) {"      [2]
#> [3] "    mutate(., c = \"c\")"       | "    mutate(., c = \"c\")"     [3]
#> [4] "  } else {"                     | "  } else {"                   [4]
#> [5] "    ."                          | "    ."                        [5]
#> [6] "  }"                            - "  }}"                         [6]
#> [7] "}"                              -
```

<sup>Created on 2021-06-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Probably this is a caching issue. Can you run `styler::cache_deactivate()` and try if the problem persists? 

If not, I'd need you to make your cache available to me, the path to the cache can be displayed with `styler::cache_info()`. This does not expose any code you styled, because code is hashed and a file without content (you can open one to check).

**Comment by lorenzwalthert** [comment]
Are you referring to https://github.com/laresbernardo/lares/commit/b80225ed3f52835471209943bdadca61f946ce5d#diff-20186f6e7a523e6feb0b8e3680225195d4e9303aa0a42b0fefc37bf53b59ddcfL470?

**Comment by lorenzwalthert** [comment]
Ok, I have identified the problem. Adding braces around `.` in an else statement:

```r
# works
library(styler)
library(dplyr)
mtcars %>%
  mutate(
    x = 1
  ) %>%
  if (FALSE) {
    mutate(., country = 2)
  } else .
```

```r
# does not work
library(styler)
library(dplyr)
mtcars %>%
  mutate(
    x = 1
  ) %>%
  if (FALSE) {
    mutate(., country = 2)
  } else {
    .
  }
Error in if (.) FALSE else { : argument is not interpretable as logical
In addition: Warning message:
In if (.) FALSE else { :
  the condition has length > 1 and only the first element will be used

```

**Comment by lorenzwalthert** [comment]
We don’t add braces to if expressions in pipes anymore as of #816. Can you try the GitHub version and see if your tests pass?

**Comment by laresbernardo** [comment]
Sorry for the delayed reply. Yes, it worked perfect with the dummy example!! Thanks for fixing it so quick @lorenzwalthert

**Comment by lorenzwalthert** [comment]
Great. Thanks for reporting.
