### ISSUE TITLE
styler bumps #nolint comments in pipes to the next line

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/styler#821]
```
a <- b %>%
  left_join(c, by = c("d" = "e")) %>% # nolint
  dplyr::rename(f = g) %>%
  group_by_at(vars(
    h,
    i,
    j,
    contains("k")
  )) %>%
  # opq
  ungroup()
```

After `styler::style_file()`:

```
a <- b %>%
  left_join(c, by = c("d" = "e")) %>%
  # nolint
  dplyr::rename(f = g) %>%
  group_by_at(vars(
    h,
    i,
    j,
    contains("k")
  )) %>%
  # opq
  ungroup()
```

Obviously that turns off the `# nolint` skip which isn't great.

I have tried a few simpler versions of this test file to no avail and it doesn't cause the issue, I'm not sure what it is in particular about this file that's triggering the bump. Basically removing any of the expressions in the current version seems to "fix" the issue.

**Comment by lorenzwalthert** [comment]
Thanks @MichaelChirico, I agree. It's because lines are only broken for pipes that chain multiple expressions (introduced with #503). #822 should fix it.

**Comment by MichaelChirico** [comment]
Awesome :) thanks for the ⚡  fix!

**Comment by lorenzwalthert** [comment]
No problem. Please send me the billing address 🎂 😀.
