### ISSUE TITLE
removing non-roxygen empty lines in docs

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/styler#862]
If there is an empty line in `{roxygen2}` docs, `{styler}` will leave it be, which makes sense:

``` r
styler::style_text("
                   #' @rdname ggplot2-ggproto
                   #' @import ggplot2
#'
#' @keywords internal
                   ")
#> 
#> #' @rdname ggplot2-ggproto
#> #' @import ggplot2
#> #'
#> #' @keywords internal
```

But do you think it should remove an empty line inserted in the middle of docs?

```r
styler::style_text("
                   #' @rdname ggplot2-ggproto
#' @usage NULL

#' @keywords internal
                   ")
#> 
#> #' @rdname ggplot2-ggproto
#> #' @usage NULL
#> 
#> #' @keywords internal
```

<sup>Created on 2021-11-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I think it should since it is rarely intended that there be an empty non-docs line right in the middle of the documentation.

**Comment by lorenzwalthert** [comment]
I don't think {styler} shoud add roxygen comments here. First of all, because in RStudio, hitting enter in a roxygen code block already adds `#'` on the next line, so to create your second case above, you explicitly have to get rid of it. And styler is non-invasive. I know there are other editors too, but the majority of user uses RStudio.

Related: #827.

**Comment by IndrajeetPatil** [comment]
> I don't think {styler} shoud add roxygen comments here.

I wasn't imagining that that's what it should do. I was thinking that it should _remove_ the empty lines without roxygen.

So expected output would like this:

```r
styler::style_text("
                   #' @rdname ggplot2-ggproto
#' @usage NULL

#' @keywords internal
                   ")
#> 
#> #' @rdname ggplot2-ggproto
#> #' @usage NULL
#> #' @keywords internal
```

**Comment by lorenzwalthert** [comment]
Yes, sorry, I meant *removing*. If you have an empty line, I think it's fair to assume that you put it there on purpose, because hitting enter in a roxygen code example addes `#'` in RStudio (and potentially other editors).

**Comment by IndrajeetPatil** [comment]
Ah, yes. That makes sense.
