### ISSUE TITLE
Style only part of file that was changed? 

### ISSUE THREAD

**Issue by sebffischer** [r-lib/styler#864]
I was wondering whether it would be possible to implement a styler function that looks at the dif between the current buffer and the last  saved version and that then only styles those parts that were changed?

I am not sure how hard it is for styler to "know" what has to be styled such that styling the whole buffer is equivalent to styling only the selection but I can imagine it yielding a considerable increase in speed.

**Comment by lorenzwalthert** [comment]
We already cache styled output on two levels: while content plus top level expressions: https://styler.r-lib.org/dev/articles/caching.html

also we tue help file for `cache_info()`.

Hence, I think this is redundant.
