### ISSUE TITLE
Feature request: remove trailing blank lines

### ISSUE THREAD

**Issue by bersbersbers** [r-lib/styler#865]
I am surprised I could not find an existing issue about this. There is https://github.com/r-lib/styler/issues/335, but this is different since it's about all blank lines (which do not all raise a `lintr` warning), not just trailing ones (which do give one, consistently).

Consider this code:

```shell
cd `mktemp -d`
printf "a <- 1\n\n" > bug.R
R -q -s -e 'lintr::lint_dir(); styler::style_file("bug.R"); lintr::lint_dir()'
```
gives
```
bug.R:2:1: style: Trailing blank lines are superfluous.

^
Styling  1  files:
 bug.R ✔ 
────────────────────────────────────────
Status  Count   Legend 
✔       1       File unchanged.
ℹ       0       File changed.
✖       0       Styling threw an error.
────────────────────────────────────────
bug.R:2:1: style: Trailing blank lines are superfluous.

^
```

I'd like `styler` to remove one `\n`.

**Comment by lorenzwalthert** [comment]
Thanks @bersbersbers. I agree, but the problem only occurs when the expression is cached.

**Comment by bersbersbers** [comment]
Cool, thanks!
