### ISSUE TITLE
Rstudio styleR warning/error 'permission denied' - how to fix?

### ISSUE THREAD

**Issue by EngrStudent** [r-lib/styler#871]
(I originally asked in [stackoverflow ](https://stackoverflow.com/questions/70304670/rstudio-styler-warning-error-permission-denied-how-to-fix)and the suggest I submit as a bug)

**Setting:**    
I'm using Rstudio (2021.09.1.372, Ghost Orchid) on Ubuntu (18.04.6).

I'm trying to use the [StyleR package][1] in it (1.6.2)
(I originally asked in stackoverflow and the suggest I submit as a bug)

**Problem:**    
When I run the addin "style active file", I get the following:

    > styler:::style_active_file()
    Using style transformers `styler::tidyverse_style()`
    There were 26 warnings (use warnings() to see them)

It seemed excessive to get 26 warnings when I should get none.

When I typed "warnings()" It gives the following style of error, (user name replaced with <username>):

    24: In file.create(.) :
      cannot create file '/home/<username>/.cache/R/R.cache/styler/1.6.2/794e937fec743117749ff91168b080b2.Rcache', reason 'Permission denied'
    25: In file.create(.) :
      cannot create file '/home/<username>/.cache/R/R.cache/styler/1.6.2/1814394756134e6409ffa7a989012fb1.Rcache', reason 'Permission denied'
    26: In file.create(.) :
      cannot create file '/home/<username>/.cache/R/R.cache/styler/1.6.2/d1cf21420a8a356674775e8f5b28265b.Rcache', reason 'Permission denied'

This tells me that an essential part of how this works isn't working. 

**Questions:**    

 - **What is the source of the problem?**  I run rstudio with user permissions, but do I need to "sudo" it? That doesn't seem like the right answer.  Are files locked in the wrong place?
 - **How do I properly resolve this problem?**

Notes: I would not have used the "tidyverse" tag if a tag for the styler package was an option.  Did I do that wrong?

  [1]: https://github.com/r-lib/styler

**Comment by EngrStudent** [comment]
There is a suggestion in the stackoverflow comments that I do this:

`dir.create("/home/<username>/.cache/R/R.cache/styler/1.6.2/", recursive=TRUE)`

It already exists.  It is owned by root, not by my username.  

So then I went the .cache, then did this at the command line:
`sudo chown -R <username> R`

And when I rerun the styler command then I get no warnings.

**Comment by lorenzwalthert** [comment]
Ok. Thanks for the update. That’s true, but you might not always be able to make the directory writable as a user or use `sudo`.

**Comment by EngrStudent** [comment]
@lorenzwalthert - 

> Ok. Thanks for the update. That’s true, but you might not always be able to make the directory writable as a user or use `sudo`.

I strongly agree.  I think this is still open, and the thing that worked for me (outside of R) seems to have helped, and might point in a useful direction.

**Comment by lorenzwalthert** [comment]
See in the above linked issue that this was added to the next release. Depending on what they decide, we can leave this closed (and add a minimal version requirement for {R.cache} once it's out).

**Comment by HenrikBengtsson** [comment]
> It already exists. It is owned by root, not by my username.

Hi, author or **R.cache** here. Before anything else, under what circumstances do you end up with `$HOME/.cache` being owned by root and not the user? To me, this sounds like an extreme situation, but I might be wrong.

That folder is by de facto standards meant to be writable by the user, and is used by lots of other software tools, which then should also fail writing cache files. In R, I'd expect software relying on `tools::R_user_dir(..., which = "cache")` or **rappdirs** would also run into problems here.  (The one thing one could argue for here is that **R.cache** should silently accept lack of write permission and skip caching to file. But again, isn't this a very rare problem?)

**Comment by lorenzwalthert** [comment]
I think given that no one else had the problem since {styler} added caching functionality 2 years ago, it's indeed a rare situation, so I'd treat this with low priority in https://github.com/HenrikBengtsson/R.cache/issues/47.
