### ISSUE TITLE
Inconsistently setting end of text line break for `style_text()`

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/styler#887]
https://github.com/REditorSupport/languageserver/issues/462#issuecomment-1001990116

**Comment by lorenzwalthert** [comment]
I can reproduce the problem with the CRAN version of styler, but in the dev version, it seems already fixed and a duplicate of https://github.com/r-lib/styler/issues/865.

**Comment by lorenzwalthert** [comment]
``` r
packageVersion('styler')
#> [1] '1.6.2.9000'
library(styler)
cache_activate()
#> Using cache 1.6.2.9000 at /Users/lorenz/Library/Caches/org.R-project.R/R/R.cache/styler/1.6.2.9000.
as.character(style_text(c("print(1)", "")))
#> [1] "print(1)"
as.character(style_text(c("print(1)", ""))) 
#> [1] "print(1)"
as.character(style_text(c("print(1)", "", "", ""))) 
#> [1] "print(1)"
```

<sup>Created on 2021-12-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by lorenzwalthert** [comment]
@renkun-ken can you confirm?

**Comment by renkun-ken** [comment]
The latest dev could produce consistent result with the trailing blank line removed.
