### ISSUE TITLE
Weird Unicode involved output

### ISSUE THREAD

**Issue by pwang2** [r-lib/styler#897]
The space before the first element will output something nonsense.  
```
> styler::style_text('a <- c( "TΔ", "An")')
a <- c("TΔ",""An")
> styler::style_text('a <- c("TΔ", "An")')
a <- c("TΔ", "An")
```

The parsed data is nothing wrong.
<img width="400px" src="https://user-images.githubusercontent.com/1592014/148444343-b746e8a9-6ccb-4cee-b8d1-9dfce27099dd.png"/>

**Comment by lorenzwalthert** [comment]
Thank @pwang2. Are you on windows? Which {styler} version do you have?

**Comment by lorenzwalthert** [comment]
On macOS with {styler} dev and R 4.1, I get

``` r
styler::style_text('a <- c( "TΔ", "An")')
#> a <- c("TΔ", "An")
```

<sup>Created on 2022-01-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by pwang2** [comment]
Could be a 3.x thing. 
![image](https://user-images.githubusercontent.com/1592014/148554442-23edcb04-ca71-4d3e-a732-77a33cd8156c.png)

![image](https://user-images.githubusercontent.com/1592014/148554367-39b560f7-071b-485d-ad13-620d10db82a6.png)

**Comment by lorenzwalthert** [comment]
Can you install the dev version from GitHub and tell me if the error persists? We recently added stronger guarantees in #895.

**Comment by pwang2** [comment]
Looks like the same.
![image](https://user-images.githubusercontent.com/1592014/148555672-b74afe88-1623-43f5-938a-afc791d6c66b.png)

**Comment by lorenzwalthert** [comment]
Ok. Which R terminal? Linux usually does not have problems with unicode characters.

**Comment by pwang2** [comment]
Good call. A little complex with the terminal at my side.  I was using Windows Terminal + git bash(Cygwin) then SSH to a remote machine.  Let me try a more direct one.

**Comment by lorenzwalthert** [comment]
```r
tmp <- tempfile(fileext = ".R")
writeLines('a <- c( "TΔ", "An")', tmp)
styler::style_file(tmp)
readLines(tmp)
```

Can you try this?

**Comment by pwang2** [comment]
![image](https://user-images.githubusercontent.com/1592014/148558299-663bfefb-c80b-457d-8f9b-47b3765a39dd.png)

**Comment by lorenzwalthert** [comment]
This looks correct to me. What do you think?

**Comment by lorenzwalthert** [comment]
but you got an error, which is interesting.

**Comment by pwang2** [comment]
and the space before the first element is still there after style_file run.

**Comment by pwang2** [comment]
let me check my OS locale and use a clean VM to test, could be something tricky there.

**Comment by lorenzwalthert** [comment]
yes. It seems like you get an error in `styler:::write_utf8()`. What {rlang} version do you have?

**Comment by lorenzwalthert** [comment]
The error you get could be because we rely on a more recent {rlang} version than you have.

**Comment by pwang2** [comment]
I tested all historical versions till v1.0.0 dated back in 2017. all have the same output. 
![image](https://user-images.githubusercontent.com/1592014/148559072-2314c982-72b8-46b8-b8f8-ff605155d871.png)

**Comment by pwang2** [comment]
rlang version 0.4.10

**Comment by pwang2** [comment]
also, I realized it should not be a display issue. as it is complaining in my ALE vim plugin as well which should be using the buffer bytes directly.

**Comment by lorenzwalthert** [comment]
Locale and encoding of your R session also don't look super exotic...

**Comment by pwang2** [comment]
old code dies hard in a shared environment.  Luckily we could move towards containerized solution in the future.  I tested in an older R version 3.5, it seems okay to me(ingore the square Unicode below, as my tty not support Unicode).  it might be some of my environment issue. I will continue to exclude other factors to make it clearer.   Thank you for your tirelessness. 
```
> library(styler)
> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 10 (buster)

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.8.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.8.0

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] styler_1.6.2

loaded via a namespace (and not attached):
 [1] fansi_0.4.2       digest_0.6.27     utf8_1.2.1        crayon_1.4.1
 [5] R.methodsS3_1.8.1 lifecycle_1.0.0   backports_1.4.1   magrittr_2.0.1
 [9] pillar_1.5.1      rlang_0.4.10      R.utils_2.11.0    R.oo_1.24.0
[13] vctrs_0.3.7       ellipsis_0.3.1    tools_3.5.2       R.cache_0.15.0
[17] purrr_0.3.4       compiler_3.5.2    pkgconfig_2.0.3   tibble_3.1.0
> styler::style_text('a <- c( "TÎ", "An")')
a <- c("TÎ", "An")
Warning message:
Could not use colored = TRUE, as the package prettycode is not installed. Please install it if you want to see colored output or see `?print.vertical` for more information.
```

**Comment by lorenzwalthert** [comment]
Ok, thanks. What's strange though is that you get `unused argument encoding = 'native.enc'` when using `style_file()`.

**Comment by pwang2** [comment]
@lorenzwalthert , confirm this is caused by package `prettycode` which used to render the output in R REPL.  If we inspect the content using `iconv`, we could confirm the unicode output is correct. but when printed out, it adds the unneeded quote which is kinda a tricky situation to diagnose since we are mislead by the output of the repl which is touched by `prettycode` already. 

I saw `prettycode` package as a suggested dependency for styler, not sure if we are postprocessing the output using that.  Can you help quick confirm that?

**Comment by pwang2** [comment]
So, it turns out to be a bug of `prettycode` instead of `styler`.  :)
![image](https://user-images.githubusercontent.com/1592014/148585365-f82eabe5-7dc3-4cc0-be5a-0c21d3948786.png)

**Comment by pwang2** [comment]
When diving deeper, the extra quote was introduced by an internal function `replace_in_place` in `prettycode` package.  I have to admit I don't know the intention of the code here.  I will submit an issue in `prettycode` project.
![image](https://user-images.githubusercontent.com/1592014/148593384-da0be955-5cb8-4ad6-a2c8-12296573fc3b.png)

**Comment by lorenzwalthert** [comment]
Ok. Thanks for investigating. Do you also get tue problem work the current version of prettycode? Otherwise, we could add a minimal version requirement. Or tighten it if there is already one.

**Comment by pwang2** [comment]
Yes, I am using the latest version of prettycode.
