### ISSUE TITLE
Stop removing macrons

### ISSUE THREAD

**Issue by daniel-wrench** [r-lib/styler#907]
Is it possible to apply the style functions without it removing macrons from characters such as ā, ū? Thanks very much.

**Comment by MichaelChirico** [comment]
could you provide an example?

**Comment by daniel-wrench** [comment]
``` r
styler:::style_text("Whanau")
#> Whanau
```

<sup>Created on 2022-01-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by MichaelChirico** [comment]
I'm not reproducing that, could you provide more information (e.g. `sessionInfo()`)?

**Comment by daniel-wrench** [comment]
``` r
sessionInfo()
#> R version 4.1.2 (2021-11-01)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19042)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_New Zealand.1252  LC_CTYPE=English_New Zealand.1252   
#> [3] LC_MONETARY=English_New Zealand.1252 LC_NUMERIC=C                        
#> [5] LC_TIME=English_New Zealand.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] knitr_1.36        magrittr_2.0.1    R.cache_0.15.0    rlang_0.4.12     
#>  [5] fastmap_1.1.0     fansi_0.5.0       stringr_1.4.0     styler_1.6.2     
#>  [9] highr_0.9         tools_4.1.2       xfun_0.28         R.oo_1.24.0      
#> [13] utf8_1.2.2        withr_2.4.3       htmltools_0.5.2   ellipsis_0.3.2   
#> [17] yaml_2.2.1        digest_0.6.29     tibble_3.1.6      lifecycle_1.0.1  
#> [21] crayon_1.4.2      purrr_0.3.4       R.utils_2.11.0    vctrs_0.3.8      
#> [25] fs_1.5.1          glue_1.5.1        evaluate_0.14     rmarkdown_2.11   
#> [29] reprex_2.0.1      stringi_1.7.6     compiler_4.1.2    pillar_1.6.4     
#> [33] backports_1.3.0   R.methodsS3_1.8.1 pkgconfig_2.0.3
```

<sup>Created on 2022-01-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by MichaelChirico** [comment]
This is probably related to the general issue with non-ASCII `name`s in R on Windows. 

See e.g. https://developer.r-project.org/Blog/public/2021/12/07/upcoming-changes-in-r-4.2-on-windows/index.html and https://developer.r-project.org/Blog/public/2021/03/12/windows/utf-8-toolchain-and-cran-package-checks/index.html.

Are you able to try out the UCRT build of R? If so, does the problem persist there?

**Comment by daniel-wrench** [comment]
I installed the UCRT build of R 4.2 and tried it outside of RStudio and the problem was fixed. However upon opening RStudio there seemed to be a big issue with that build so I un-installed the build, and RStudio is working again now.

**Comment by MichaelChirico** [comment]
OK that's good to know... I'm not sure there's anything for styler to do in that case. I'll let Lorenz decide how to proceed.

**Comment by daniel-wrench** [comment]
Thanks very much for your help.

**Comment by lorenzwalthert** [comment]
Thanks @MichaelChirico for your help in resolving the issue 👍
