### ISSUE TITLE
Style Quarto documents (.qmds)

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [r-lib/styler#913]
Currently, running the "Style active file" addin (`styler:::style_active_file()`) on a [Quarto](https://quarto.org/) document (`.qmd`) gives the error `Can only style .R, .Rmd and .Rnw files.`. This is a feature request to extend styler functionality to Quarto documents. Thank you!

**Comment by lorenzwalthert** [comment]
It seems to me as `.qmd` has the  same semantics to declare code blocks as `.Rmd`, only the file extension is different. Can you confirm that?

**Comment by MichaelChirico** [comment]
it looks like there's likely to be some divergence, now or in the future:

> Quarto is a multi-language, next generation version of R Markdown from RStudio, and includes dozens of new features and capabilities (while at the same being able to render most existing Rmd files without modification).

**Comment by lorenzwalthert** [comment]
@JohannesNE are you interested in contributing this feature? It seems quite similar to your work in #824. @MichaelChirico I think the specs might change in the future, but I think it's unlikely that something as fundamental as how code fences are declared will change. These are stable things since the introduction of R Markdown and are also recognized by Jupyter (which quarto relies on also)

**Comment by mine-cetinkaya-rundel** [comment]
>It seems to me as `.qmd` has the same semantics to declare code blocks as `.Rmd`, only the file extension is different. Can you confirm that?

@lorenzwalthert Yes, that is correct!

**Comment by JohannesNE** [comment]
Thank you for reaching out. Unfortunately I am a bit too hung up on other
projects at the moment.

**Comment by lorenzwalthert** [comment]
Ok @JohannesNE, I appreciate tue quick response.

**Comment by lorenzwalthert** [comment]
@MichaelChirico or @mine-cetinkaya-rundel, if you are interested to contribute that feature, I'd be more than happy to provide guidance and code review. The git diff from #824 should be very helpful in implementing that feature, it's essentially the same.

**Comment by lorenzwalthert** [comment]
@mine-cetinkaya-rundel you want to try out `renv::install("r-lib/styler@931")` and tell me if it works for you?

**Comment by mine-cetinkaya-rundel** [comment]
@lorenzwalthert Just tried this on a `.qmd` file and it doesn't seem to work for me.

The error about not being able to style this type of file isn't there, but the style is not being corrected. This is the document I'm trying it on:

```
    ---
    format: html
    ---
    
    ## Quarto
    
    Some text...
    
    ```{r}
    library(tidyverse)
    
    ggplot(mtcars,aes(x=mpg,y=disp))+geom_point()
    ```
    
    ```{r}
    mtcars%>%
    filter(mpg>30)
    ```
```

**Comment by lorenzwalthert** [comment]
The Addin has not worked (with the file error), so I pushed 68e846d23e9893ed897ba8b894f65dbb15cde369 to fix this. However, I can't reproduce your problem. Can you provide more context of how you run {styler}. Also, RStudio sometimes requires re-opening the file I figured to see changes made by other processes.

**Comment by mine-cetinkaya-rundel** [comment]
@lorenzwalthert This works now, thank you!

**Comment by RoyalTS** [comment]
Now that Quarto has hit prime time, time to cut a release?

**Comment by lorenzwalthert** [comment]
Releases are generally a bit of work. You have voiced in several places that that you'd want one, which I understand, but there is no release planned in the next few weeks, maybe not months. You can already use that functionality now, also with pre-commit. If you want to contribute to {styler}, I suggest you contribute an easy issue like https://github.com/lorenzwalthert/precommit/issues/437. Interested?
