### ISSUE TITLE
Styler does not recognize code indentation in markdown

### ISSUE THREAD

**Issue by kaytif** [r-lib/styler#917]
To indent code for outputting code in a list form, it is not sufficient to indent only the backticks in code chunks. One must also indent the code itself, otherwise, the code sometimes appears awkwardly and some styling is removed when knitted. 

If only the backticks are indented then the styler does not recognize this and does not indent the code as well. Neither "style selection" nor "style active file" work for this. 

This is inefficient as one has to spend time and effort indenting the code properly. Also, in case someone forgets, the code may appear awkwardly in the knitted file. It would be useful if the styler could recognize when the backticks are indented and indent the remaining code itself. 

This is how the code looks when backticks are indented but the code is not
![Screenshot 2022-02-20 224524](https://user-images.githubusercontent.com/100077484/154848288-8ad4ff83-29bf-49c5-801a-08c122f93520.png)

This is how it looks in the knitted file. The styling is removed from lines 3 and 4.

![image](https://user-images.githubusercontent.com/100077484/154848358-c972aa61-9d1e-48af-98d0-6d42e6c8ece0.png)

**Comment by lorenzwalthert** [comment]
Thanks @kaytif for filing an issue here. I am not sure I can follow:

> To indent code for outputting code in a list form

Can you clarify that by adding a *reproduible example* (link to files, you can drag and drop into the text box) of how the input got transformed and how this is different from what you expect?
