### ISSUE TITLE
How to style code chunks with child documents?

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/styler#918]
For example, if I have the following chunk in my `.Rmd` file,

````r
```{r child="man/rmd-fragments/doc.Rmd"}
```
````

it is styled to

````r
```{r child="man/rmd-fragments/doc.Rmd"}

```
````

(Notice the added empty line.)

But if I have the same chunk in my `.R` file (e.g. in `roxygen2` docs),

```r
#' ```{r child="man/rmd-fragments/doc.Rmd"}
#' ```
```
it is not styled this way:

```r
#' ```{r child="man/rmd-fragments/doc.Rmd"}
#' ```
```

I couldn't find anything relevant about this in the tidyverse style guide, so wondering if the behaviour should be consistent across contexts?

**Comment by lorenzwalthert** [comment]
Thanks @IndrajeetPatil. Styling code fences in roxygen comments is not currently supported, see #770. This is the reason for the inconsistency, if you want. To resolve it, just manually format the roxygen code fence the way you want it and it won’t be changed by {styler}.

**Comment by IndrajeetPatil** [comment]
Thanks, Lorenz! 

Closing this in favor of #770 then 🙃

**Comment by MichaelChirico** [comment]
I think roxygen comments are one thing, but why is the blank line added in the first place?

as noted here:

https://github.com/r-lib/lintr/issues/909

this tends to trip lintr's trailing_blank_lines_linter

**Comment by lorenzwalthert** [comment]
Probably it comes from the idea that each valid file has an empty line at the end, but I agree it's probably not a good idea to use that logic here. I am open to avoid adding a spare line, but not sure if we should remove existing blank lines...

**Comment by IndrajeetPatil** [comment]
@cderv From `rmarkdown` best practices perspective, do you think one of these should be preferred over the other?

1.

````r
```{r child="man/rmd-fragments/doc.Rmd"}
```
````

2.

````r
```{r child="man/rmd-fragments/doc.Rmd"}

```
````

> I am open to avoid adding a spare line, but not sure if we should remove existing blank lines

@lorenzwalthert If both styles are equally acceptable practices, then, yes, I'd say that `{styler}` should not remove existing blank lines.

**Comment by IndrajeetPatil** [comment]
Thanks a lot, @cderv, for your valuable input! 

@lorenzwalthert I think we should go for the blank like approach then, i.e. remove blank lines even if they exist.

This would also be `{lintr}`-friendly, since otherwise such a blank line would produce "superfluous trailing blank line" lint.

**Comment by IndrajeetPatil** [comment]
Thank you, Lorenz, for the quick fix!  🙌

**Comment by lorenzwalthert** [comment]
Welcome.
