### ISSUE TITLE
Inconsistency for right square brackets in long subsetting expressions

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/styler#920]
Compare:

```
styler::style_text("
DF[DF$cond &
  DF$cond2, ]
")

# DF[DF$cond &
#   DF$cond2, ]
```

```
styler::style_text("
DF[
  DF$cond & DF$cond2, ]
")

# DF[
#   DF$cond & DF$cond2,
# ]
```

I am not sure any rules in the style guide apply here, but personally I find the trailing comma quite hard to read and so prefer keeping the `]` on the same line to emphasize the blank 2nd argument to `[`, so I would prefer if both cases behave as the first does.

**Comment by lorenzwalthert** [comment]
Similar to #921, I don't think so. Again, it's a taste question, but also a consistency question. Opening braces don't usually have code following them, nor do closing baces have code before them.
```r
(
  stuff here
)

{
  stuff here
}

[
  stuff here
]

stuff here [
  stuff here
] stuff here


test_that({'x', {
  my_fun()
})

etc.
```

To me, the fact that `DF$cond & DF$cond2,` is indented already shows that this is an expression within braces. Adding `[` on the same line creates an asymmetry to that line (as there is no opening brace) that is visually unpleasing IMO and not in line with how other brace expressions are formatted.
