### ISSUE TITLE
Change in R devel causes different error message for `_`, making {styler} fail R CMD check

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/styler#925]
I will soon be committing a change to R-devel that will change error
messages produced by the parser when the underscore character _ is
used inappropriately. styler currently tests for a specific message
and will fail once that change is committed. The test that will fail
is

`testthat::expect_error(...)` at test-escaping.R:14:2

It would be better to change this to not assume a particular message.

**Comment by lorenzwalthert** [comment]
Not yet committed into R devel: https://cran.r-project.org/web/checks/check_results_styler.html

**Comment by hadley** [comment]
This has just been committed, so let me know if there's anything I can do to help.

**Comment by lorenzwalthert** [comment]
Was it? I can't see any error in the CRAN results for R devel. I think I'll be able to fix that one myself, thanks, but if you want to help out in other issues, e.g. the ones you opened, that would be appreciated, e.g #926. My plan is to decrease my involvement with {styler} continuously and find other people to contribute code.

**Comment by hadley** [comment]
You don't see it because Luke deliberately patched R-devel to avoid styler failing; it still needs to be fixed.

**Comment by lorenzwalthert** [comment]
Ah ok. Then I'll make a CRAN submission early next week. I first wanted to wait and see it fail to have more context and ensure that the fix is effective, but then I'll just stop assuming a specific error message as Luke suggested.

**Comment by MichaelChirico** [comment]
you can try something like tryCatch(parse(text = '1 _'), error=identity) and ensure the message coming from styler matches that coming from R

**Comment by lorenzwalthert** [comment]
It's released now.
