### ISSUE TITLE
Require {} in function definitions?

### ISSUE THREAD

**Issue by hadley** [r-lib/styler#927]
i.e. should this

```R
as.POSIXct.fts <- function(x, tz = "", ...) as.POSIXct(zoo::index(x))
```

be restyled to this?

```R
as.POSIXct.fts <- function(x, tz = "", ...) {
  as.POSIXct(zoo::index(x))
}
```

**Comment by MichaelChirico** [comment]
is there a style guide rule about this?

what we enforce is: if >1 line, braces required, but if the definition can be inlined, ok to leave as is

**Comment by lorenzwalthert** [comment]
> what we enforce is: if >1 line, braces required, but if the definition can be inlined, ok to leave as is

That's what happens now:

``` r
styler::style_text('as.POSIXct.fts <- function(x, tz = "", ...) as.POSIXct(zoo::index(x))')
#> as.POSIXct.fts <- function(x, tz = "", ...) as.POSIXct(zoo::index(x))
```

<sup>Created on 2022-03-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
The [style guide](https://style.tidyverse.org/syntax.html#inline-statements) currently says

> Function calls that affect control flow (like [return()](https://rdrr.io/r/base/function.html), [stop()](https://rdrr.io/r/base/stop.html) or continue) should always go in their own {} block:

I'd be tempted to say that should also applies to functions, but it is often nice to have a single line function inside the body of a function, so maybe this is best left as is.
