### ISSUE TITLE
Edge case: Trailing `(` of parameter list and opening `{` of function scope are styled to be on different lines

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/styler#933]
I am guessing that introducing scope in parameter list is throwing off this alignment:

``` r
styler::style_text(
  "f1 <- function(x = {y <- 1; 2}, y = 0) {
    c(x, y)
   }"
)
#> f1 <- function(x =
#>                  {
#>                    y <- 1
#>                    2
#>                  },
#>                y = 0)
#> {
#>   c(x, y)
#> }
```

<sup>Created on 2022-03-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

Expected

```r
#>                y = 0) {
```

This deviates from tidyverse style guide [recommendation](https://style.tidyverse.org/functions.html):

![image](https://user-images.githubusercontent.com/11330453/159343910-77bcc2e2-149d-41cf-b837-0f8713ffce0d.png)

**Comment by lorenzwalthert** [comment]
Thanks @IndrajeetPatil. More minimal expample: 
``` r
styler::style_text(
  "f1 <- function(x = {1}, y = 0) {
    c(x, y)
   }"
)
#> f1 <- function(x =
#>                  {
#>                    1
#>                  },
#>                y = 0)
#> {
#>   c(x, y)
#> }
```

<sup>Created on 2022-03-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Whit the expectation that `{` stays on the same line as `y = 0`.
