### ISSUE TITLE
convert `%>%` into `|>`?

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/styler#937]
{formatR} offers this in https://github.com/yihui/formatR/releases/tag/v1.12. Maybe `tidyverse_style()` could have an argument for that.

**Comment by sebffischer** [comment]
wouldn't that sometimes break code as the operators behave differently?

**Comment by lorenzwalthert** [comment]
It would be optional. And it's aimed at being very simlar with release 2.0: https://www.tidyverse.org/blog/2020/11/magrittr-2-0-is-here/

**Comment by lorenzwalthert** [comment]
Out of scope.
