### ISSUE TITLE
Leading blank lines in a scope are not removed when a comment present

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/styler#951]
# without comment

``` r
styler::style_text(
  'test_that(
  desc = "bla",
  code = {

    expect_equal(1 + 1, 2)
  })'
)
#> test_that(
#>   desc = "bla",
#>   code = {
#>     expect_equal(1 + 1, 2)
#>   }
#> )
```

# with comment

```r
styler::style_text(
  'test_that(
  desc = "bla",
  code = {



    # comment
    expect_equal(1 + 1, 2)
  })'
)
#> test_that(
#>   desc = "bla",
#>   code = {
#> 
#> 
#> 
#>     # comment
#>     expect_equal(1 + 1, 2)
#>   }
#> )
```

<sup>Created on 2022-06-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by lorenzwalthert** [comment]
This is intended. SEE `NEWS.md`: 
> blank lines in function calls and headers are now removed, for the former only when there are no comments before or after the blank line ([#629](https://github.com/r-lib/styler/issues/629), [#630](https://github.com/r-lib/styler/issues/630), [#635](https://github.com/r-lib/styler/issues/635), [#723](https://github.com/r-lib/styler/issues/723)).

**Comment by IndrajeetPatil** [comment]
But, if I am not mistaken, this is neither a function call nor a function header, but rather a code block, right? 

In any case, do you not think this should be the expected behaviour?

This is quite likely to happen because developers add many `skip_` conditions for a given test block, and search and replace them with empty lines later when they are no longer needed. So it will be nice if _styler_ could clean up these unnecessary empty lines between the opening brace and the test code.

**Comment by lorenzwalthert** [comment]
Ok fine... Without adding more complexity, this will result in comments being moved to the next line though if they are on the same line as the opening brace. This is fine thouth I think, as `{` should be the last character on a line anywyas according to the style guide.

**Comment by lorenzwalthert** [comment]
@IndrajeetPatil thanks for the issue. I should just say though that I try to reduce my time spent on {styler} and that I don't know if I will fix issues with (for me) low priority in the future anymore. Maybe others like @krlmlr will jump in. If you feel like you want to contribute, I am happy to review pull request for issues like this. Just you know. Of course you can always file issues and unless they are not legit, I won't close them 😄

**Comment by lorenzwalthert** [comment]
This issue should be fixed iwth #952. You can inspect the diff to get a feel for how I did it.

**Comment by IndrajeetPatil** [comment]
Thanks for the quick fix, Lorenz!

> If you feel like you want to contribute, I am happy to review pull request for issues like this. 

I'd definitely like to contribute more, and would start doing so when I have a bit more time after July (especially #936 and #759).

**Comment by lorenzwalthert** [comment]
Great, I am happy to provide guidance in that. It's not that I want to stop working on {styler} tomorrow, but probably mid-term, e.g. start reducing gradually and onboard new contributors.
