### ISSUE TITLE
pgkdown page needs to be fixed

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/styler#953]
See GItHub Actions. I think they change the way the vignettes have to be specified in `_pkgdown.yml` in the latest release. See how it's fixed in precomit: https://github.com/lorenzwalthert/precommit/commit/3d5a7552fc2c2a986162a5763d543fc0eecc80a8, should be the same. Also, missing vignettes are only showed with https://github.com/r-lib/pkgdown/pull/2121.

**Comment by IndrajeetPatil** [comment]
Which of these vignettes do you actually want to include on the website?

```r
> pkgdown::check_pkgdown()
Error in `data_articles_index()`:
! Vignettes missing from index: gsoc_proposal/data_structures, gsoc_proposal/manipulating_nested_parse_data, introducing_styler, performance_improvements
```

**Comment by lorenzwalthert** [comment]
I'd like to exclude all of those. But I could not figure out how in {precommit}, e.g. with https://community.rstudio.com/t/how-to-exclude-a-vignette/11203. Maybe we first need to include them using the right syntax in `_pkgdown.yml` and then think about how to get rid of them. If you can't figure it out quickly, just delete them, I don't think we need them anymore plus anyone who wants to see them can just `git checkout v1.0.0`.

**Comment by IndrajeetPatil** [comment]
There is actually currently no way to exclude `.Rmd` present in `\vignettes` from `articles`. The solution suggested [here](https://github.com/r-lib/pkgdown/issues/1336) doesn't work. It just excludes these files from being shipped with CRAN submission, but they will still be present on the pkgdown website.

So, I'd say that we can just delete these (at this point) unnecessary files.

**Comment by lorenzwalthert** [comment]
Agree. Thanks.

**Comment by IndrajeetPatil** [comment]
Btw, the URL to Jupyterlab code formatter [here](https://styler.r-lib.org/dev/articles/third-party-integrations.html) leads to a page that does not exist: 

![image](https://user-images.githubusercontent.com/11330453/174179207-62788712-a6b2-41b0-bfe8-3ffff0d040d6.jpeg)
