### ISSUE TITLE
ANSI escape codes showing on the website

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/styler#954]
For example, see [here](https://styler.r-lib.org/dev/articles/styler.html)

<img width="940" alt="Screenshot 2022-06-16 at 12 45 05" src="https://user-images.githubusercontent.com/11330453/174054163-fb571429-2529-40a0-9489-da063d144a93.png">

**Comment by IndrajeetPatil** [comment]
I think setting `comment = "#>"` here might solve this issue:

https://github.com/r-lib/styler/blob/31e77cc123cdf5b218fa6e1abd30e4b99f1bb9d8/vignettes/styler.Rmd#L11

**Comment by lorenzwalthert** [comment]
Uhhhh not nice 😩. I think we should fix #953 and see if problem prevails with new pkgdown version.

**Comment by lorenzwalthert** [comment]
I think rather the problem is {prettycode}. It formats the output. We should disable it with `options(styler.colored_print.vertical = FALSE)` and see if that helps.

**Comment by lorenzwalthert** [comment]
For the relevant documentation parts only obviously.

**Comment by IndrajeetPatil** [comment]
There is one more issue left. Making a PR to fix it:

<img width="531" alt="Screenshot 2022-06-16 at 16 57 31" src="https://user-images.githubusercontent.com/11330453/174099192-e6b96bc6-4755-49fe-af8c-462c880bdecc.png">
