### ISSUE TITLE
{ gets bumped in compound while statement --> open curly violation

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/styler#966]
```r
styler::style_text('
while ({
  bad <- grepl("_", z)
  any(bad)
}) {
  TRUE
}
')
# while (
#   {
#     bad <- grepl("_", z)
#     any(bad)
#   })
# {
#   TRUE
# }
```

The `{` is bumped but the [style rules dictate `{` should be on the line with `)`](https://style.tidyverse.org/syntax.html#indenting):

> `{` should be the last character on the line. Related code (e.g., an `if` clause, a function declaration, a trailing comma, …) must be on the same line as the opening brace.

AFAIK clauses like `({ ... })` are generally fine, so I'm also not sure why `(` and `{` were separated...

**Comment by lorenzwalthert** [comment]
We solved it for functioncalls like `tryCatch()` and `testthat()`. If the curly expression is the last, `({` is allowed, with closing `})` on same line:

``` r
styler::style_text('tryCatch({
  code
})

tryCatch({
  code
  }, 
  x = 2
)')
#> tryCatch({
#>   code
#> })
#> 
#> tryCatch(
#>   {
#>     code
#>   },
#>   x = 2
#> )
```

<sup>Created on 2022-07-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by lorenzwalthert** [comment]
Reference: https://github.com/r-lib/styler/pull/543
