### ISSUE TITLE
use {fledge} for release management

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/styler#981]
Re: https://github.com/r-lib/styler/pull/977#issuecomment-1221475288

The problem I have with that approach is that I don't see from the documentation how you can make different sections in `NEWS.md`, which is [recommended by the tidyverse style guide](https://style.tidyverse.org/news.html#news-release). Can you confirm that this is not possible or how to work around it @krlmlr?

**Comment by krlmlr** [comment]
We now support a subset of conventional commits, these are translated into sections.

**Comment by lorenzwalthert** [comment]
Ok, I could not find the relevant section in the docs... After looking at the docs for > 15 mins, I still don't feel like I know how it works (maybe just me, it late?). I think the get started vignette and the README repeats itself a few times is not 100% clear with terminology, so I got a bit confused. Because after all it is not that complicated when I tried it out hands-on.


In particular, this section in the docs was confusing for me:

<img width="879" alt="Screenshot 2022-08-21 at 21 25 00" src="https://user-images.githubusercontent.com/10477073/185807547-52a2e039-7cf1-494a-905c-8d2f35edd638.png">

-> 'News is now composed' (wait, by `finalize_version()`) or by me previously?




<img width="942" alt="Screenshot 2022-08-21 at 21 45 52" src="https://user-images.githubusercontent.com/10477073/185808335-f95268ce-381a-4730-9c69-4cf022462e9f.png">

-> 'If you add to edit'? I don't understand that sentence.

**Comment by krlmlr** [comment]
Thanks for your feedback. Would a video have helped?

To clarify:

- fledge expands `NEWS.md`, that's its purpose
- "add to edit" is a typo, should be "after you add to `NEWS.md`" or "after you edit `NEWS.md`" or similar

**Comment by lorenzwalthert** [comment]
Thanks. 

> fledge expands NEWS.md, that's its purpose

That was clear from the beginning for me, but not how it would do that, when/if it would overwrite my manual edits etc, that I can't have an up to date `NEWS.md` unless you make a new release with `bump_version()`.

Yes, a video would definitively have helped, if I understand correctly, all I need to know to make it work is to know when I have to call `bump_version()`, when I can edit the changelog without getting overwritten and when to call `finalize()`. Thanks Kirill for your patience.

**Comment by lorenzwalthert** [comment]
Ok, I now used {fledge} for tag 1.7.002 🎉. Next step would be to update `CONTRIBUTING.md` to reflect these change, i.e. 
* Don't add news bullet to PR, 
* handle PR commit messages right so {fledge} can understand them.
* regularly run `bump_version()` and `finalize_version(push = TRUE)`.

**Comment by lorenzwalthert** [comment]
Also, @IndrajeetPatil in order to use PR tiles for {fledge}, I think we need to create explicit merge commits with PRs, as the home page says at https://cynkra.github.io/fledge/dev/.

**Comment by lorenzwalthert** [comment]
Sorry this has not worked for me. I can’t recall the exact problems but I got error messages sometimes and when merging, I don’t consistently set the title of the merge commit to make it into tie change log. Also, I find it much easier to just compile the channeling by reviewing all PR titles. If anyone else takes over maintenance of styler at some point, feel free to reopen.
