### ISSUE TITLE
Feature Request: Add new line after comma following function call

### ISSUE THREAD

**Issue by wdkrnls** [r-lib/styler#993]
I may be missing something since I just started using styler, but I don't understand why styler with the defaults thinks things like the following are readable code:

```r
fun_call(
  another_function_call(), yet_another_function_call_with_arg(x), and_another_call())
```

I think it is easier to read code when there are new lines after each of these internal function calls followed by a comma.

```r
fun_call(
  another_function_call(),
  yet_another_function_call_with_arg(x),
  and_another_call())
```
The above is a lot more readable.

Note that in my use case I am trying to automatically format code not in a file but as it is returned from R. `styler` works pretty well otherwise  helping me write papers where I show R code in a package in a fully reproducible automatic manner, but wide formatted stuff like the above just isn't something I want to place in a paper.

So, I guess I'm requesting an additional `line_break` rule. Maybe call it `set_line_break_after_comma_following_nested_function_call`?

**Comment by lorenzwalthert** [comment]
The code in your first code block is styled to with `style_text(), the Addin or `style_file()` and friends:
```r
fun_call(
  another_function_call(), yet_another_function_call_with_arg(x), and_another_call()
)
```

> Note that in my use case I am trying to automatically format code not in a file but as it is returned from R.
Not sure what you man. You can format within R with `style_text()`.

> So, I guess I'm requesting an additional line_break rule.
I don't think that's what you want, it already formats your code example (your first block).

**Comment by wdkrnls** [comment]
The first block with all the function calls in one line is not readable. The second block is readable for the same reason tidyverse style generally places new lines after pipes. For me `style_text` does the first block formatting (all on one line) and not the second (separate lines after each comma). At least, this is what I see in Rmarkdown. Having everything on one line doesn't work in a paper and I don't want to have to copy the code and manually style it. Are you saying maybe I need to be using the development version?

**Comment by krlmlr** [comment]
The original project motto was "non-invasive pretty printing". So, styler will not attempt to alter the perceived intent of the formatting.

A quick hack to get the desired result could be to replace all instances of, say `"), "` with `"),\n"` in your code, and reformat with styler. Or even replace all instances of `", "` with `",\n"` .

I haven't found anything on function calls in https://style.tidyverse.org, what am I missing?

I agree that multiple arguments on the same line may be confusing. We *could* consider being more invasive with `strict = TRUE`, and allow only two forms of function calls:

```r
call(with, all, arguments, in_(one, line))
call(
  with,
  all,
  arguments,
  on = c(separate, lines)
)
```

**Comment by MichaelChirico** [comment]
FWIW the relevant style guide section starts here https://style.tidyverse.org/syntax.html#long-lines

**Comment by lorenzwalthert** [comment]
> Maybe I am misunderstanding. Are you saying maybe I need to be using the development version?

No.

> For me style_text does the first block formatting (all on one line) 

Styler does not support breaking lines at a certain character yet, see #247.


> In short: I think 99% of humans would prefer to read the following: [one argument per line]

Adding a line break after each argument if a function call is multi-line is a duplicate of #926.

> I agree that multiple arguments on the same line may be confusing. We could consider being more invasive with strict = TRUE, and allow only two forms of function calls:

Yes, see #926. Also see https://github.com/gadenbuie/grkstyle.

**Comment by wdkrnls** [comment]
I really appreciate all the suggestions I have received in this thread. I think the suggestion from @krlmlr to just do some ad-hoc preprocessing before sending code to `style_text` will be good enough for writing my current paper.
