### ISSUE TITLE
Add branch protection rule?

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/styler#996]
So that contributors can't merge without any code review, even if CI/CD is all green.

<img width="816" alt="Screenshot 2022-09-12 at 16 19 42" src="https://user-images.githubusercontent.com/11330453/189678144-fd8cb89f-7f63-419d-9050-bfebb5d93a0a.png">

**Comment by lorenzwalthert** [comment]
Ok, yeah. I can update that. @krlmlr ok?

**Comment by krlmlr** [comment]
No preference.

**Comment by lorenzwalthert** [comment]
Done.
